import { StyleSheet } from 'react-native';
import { Colors, Spacing, BorderRadius, Typography, Backgrounds, GlowColors } from "@/constants/theme";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: "flex-end",
    zIndex: 9999,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Backgrounds.overlay,
    zIndex: 1,
  },
  drawer: {
    backgroundColor: Backgrounds.elevated,
    borderTopLeftRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
    maxHeight: "90%",
    minHeight: "60%",
    zIndex: 2,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderBottomWidth: 0,
  },
  handleContainer: {
    alignItems: "center",
    paddingVertical: Spacing.sm,
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: Colors.dark.textMuted,
    borderRadius: 2,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: Spacing["2xl"],
  },
  header: {
    position: "relative",
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.md,
  },
  headerGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 80,
  },
  headerContent: {
    position: "relative",
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.sm,
  },
  statusBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
  },
  statusText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "600",
  },
  closeButton: {
    padding: Spacing.xs,
  },
  title: {
    fontSize: Typography.h2.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
    marginBottom: Spacing.xs,
  },
  subtitle: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.textMuted,
  },
  tabBar: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.backgroundRoot,
    marginHorizontal: Spacing.lg,
  },
  tab: {
    flex: 1,
    alignItems: "center",
    paddingVertical: Spacing.sm,
    position: "relative",
  },
  tabActive: {},
  tabLabel: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginTop: Spacing.xs,
  },
  tabIndicator: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    borderRadius: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.xl,
  },
  tabContent: {
    flex: 1,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
    marginBottom: Spacing.lg,
  },
  statCard: {
    flex: 1,
    minWidth: "45%",
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    borderWidth: 1,
  },
  statValue: {
    fontSize: Typography.h1.fontSize,
    fontWeight: "700",
    marginBottom: Spacing.xs,
  },
  statLabel: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
  },
  infoSection: {
    marginBottom: Spacing.lg,
  },
  sectionTitle: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "600",
    color: Colors.dark.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: Spacing.sm,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  infoText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.textMuted,
  },
  playerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.xs,
    position: "relative",
    overflow: "visible",
    zIndex: 1,
  },
  playerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.dark.backgroundRoot,
    justifyContent: "center",
    alignItems: "center",
  },
  playerInitial: {
    fontSize: Typography.h4.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  playerInfo: {
    flex: 1,
  },
  playerName: {
    fontSize: Typography.small.fontSize,
    fontWeight: "500",
    color: Colors.dark.text,
  },
  playerStats: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
  },
  creditBadge: {
    backgroundColor: Colors.dark.successNeon + "20",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.xs,
    minWidth: 28,
    alignItems: "center",
  },
  creditBadgeWarning: {
    backgroundColor: Colors.dark.accentWarning + "30",
  },
  creditBadgeDebt: {
    backgroundColor: Colors.dark.error + "30",
  },
  creditBadgeText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "600",
    color: Colors.dark.successNeon,
  },
  creditBadgeTextWarning: {
    color: Colors.dark.accentWarning,
  },
  creditBadgeTextDebt: {
    color: Colors.dark.error,
  },
  playerMenuButton: {
    padding: Spacing.xs,
    marginLeft: Spacing.xs,
  },
  playerActionMenu: {
    position: "absolute",
    right: 0,
    bottom: 40,
    minWidth: 180,
    zIndex: 100,
    borderRadius: BorderRadius.lg,
    overflow: "hidden",
    shadowColor: Colors.dark.accentNeon,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 10,
  },
  playerActionMenuGradient: {
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.04)",
    padding: Spacing.sm,
  },
  playerActionMenuHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
  },
  playerActionMenuTitle: {
    fontSize: 10,
    fontWeight: "600",
    color: Colors.dark.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  playerActionDivider: {
    height: 1,
    backgroundColor: Backgrounds.elevated,
    marginVertical: Spacing.xs,
  },
  playerActionIconWrapper: {
    width: 28,
    height: 28,
    borderRadius: BorderRadius.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  playerActionItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.sm,
    borderRadius: BorderRadius.sm,
  },
  playerActionItemPressed: {
    backgroundColor: Backgrounds.elevated,
  },
  playerActionItemDanger: {
    marginTop: Spacing.xs,
  },
  playerActionItemOld: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.sm,
  },
  playerActionText: {
    flex: 1,
    fontSize: Typography.small.fontSize,
    fontWeight: "500",
  },
  reactivateButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    backgroundColor: Colors.dark.successNeon + "20",
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
  },
  reactivateButtonText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "600",
    color: Colors.dark.successNeon,
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: Spacing["2xl"],
  },
  emptyText: {
    fontSize: Typography.h4.fontSize,
    color: Colors.dark.textMuted,
    marginTop: Spacing.md,
  },
  emptySubtext: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.textMuted,
    marginTop: Spacing.xs,
    textAlign: "center",
  },
  timelineItem: {
    flexDirection: "row",
    marginBottom: Spacing.md,
  },
  timelineConnector: {
    width: 24,
    alignItems: "center",
  },
  timelineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: Colors.dark.textMuted,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: Colors.dark.backgroundRoot,
    marginTop: Spacing.xs,
  },
  timelineContent: {
    flex: 1,
    marginLeft: Spacing.sm,
    paddingBottom: Spacing.sm,
  },
  timelineHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  timelineDate: {
    fontSize: Typography.small.fontSize,
    fontWeight: "500",
    color: Colors.dark.text,
  },
  timelineStatus: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
  },
  timelineTime: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginTop: Spacing.xs,
  },
  timelineSessionTime: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    fontWeight: "500",
  },
  feedbackSummary: {
    flexDirection: "row",
    gap: Spacing.md,
    marginBottom: Spacing.lg,
  },
  feedbackStat: {
    flex: 1,
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    alignItems: "center",
  },
  feedbackStatValue: {
    fontSize: Typography.h2.fontSize,
    fontWeight: "700",
    color: Colors.dark.successNeon,
  },
  feedbackStatLabel: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginTop: Spacing.xs,
    textAlign: "center",
  },
  intensityBreakdown: {
    marginBottom: Spacing.lg,
  },
  intensityRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
    marginTop: Spacing.sm,
  },
  intensityChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    backgroundColor: Colors.dark.backgroundRoot,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
  },
  intensityText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.text,
    textTransform: "capitalize",
  },
  feedbackCard: {
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  feedbackHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.xs,
  },
  feedbackDate: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.text,
    fontWeight: "500",
  },
  intensityBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
  },
  intensityBadgeText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "500",
    textTransform: "capitalize",
  },
  feedbackNote: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.textMuted,
    marginTop: Spacing.xs,
  },
  feedbackTypeIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  feedbackPlayerName: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  feedbackTimestamp: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginTop: Spacing.xs,
  },
  xpBadge: {
    backgroundColor: GlowColors.primary + "20",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
  },
  xpBadgeText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "600",
    color: GlowColors.primary,
  },
  visibilityBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  progressSummary: {
    flexDirection: "row",
    gap: Spacing.md,
    marginBottom: Spacing.lg,
  },
  progressStat: {
    flex: 1,
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    alignItems: "center",
  },
  progressStatValue: {
    fontSize: Typography.h2.fontSize,
    fontWeight: "700",
    color: Colors.dark.gold,
  },
  progressStatLabel: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginTop: Spacing.xs,
    textAlign: "center",
  },
  playerProgressCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  playerRank: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Colors.dark.gold + "20",
    alignItems: "center",
    justifyContent: "center",
    marginRight: Spacing.sm,
  },
  rankNumber: {
    fontSize: Typography.small.fontSize,
    fontWeight: "700",
    color: Colors.dark.gold,
  },
  playerProgressInfo: {
    flex: 1,
  },
  playerProgressName: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  playerProgressSessions: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
  },
  playerXpBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    backgroundColor: Colors.dark.gold + "15",
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
  },
  playerXpValue: {
    fontSize: Typography.small.fontSize,
    fontWeight: "600",
    color: Colors.dark.gold,
  },
  assessButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.xpCyan + "15",
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
    marginRight: Spacing.xs,
  },
  assessButtonText: {
    fontSize: Typography.small.fontSize,
    fontWeight: "600",
    color: Colors.dark.xpCyan,
  },
  // Add Player Modal styles
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.sm,
  },
  editMaxPlayersRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  maxPlayersInput: {
    width: 32,
    height: 28,
    backgroundColor: Colors.dark.backgroundRoot,
    borderWidth: 1,
    borderColor: Colors.dark.successNeon,
    borderRadius: BorderRadius.sm,
    color: Colors.dark.text,
    textAlign: "center",
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    paddingHorizontal: 4,
    marginHorizontal: 2,
  },
  saveMaxPlayersBtn: {
    marginLeft: Spacing.sm,
    padding: 4,
  },
  cancelMaxPlayersBtn: {
    marginLeft: Spacing.xs,
    padding: 4,
  },
  editableTitle: {
    flexDirection: "row",
    alignItems: "center",
  },
  addPlayerButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    backgroundColor: Colors.dark.successNeon + "20",
    borderRadius: BorderRadius.md,
  },
  addPlayerButtonText: {
    fontSize: Typography.small.fontSize,
    fontWeight: "600",
    color: Colors.dark.successNeon,
  },
  emptyAddButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.lg,
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: Colors.dark.successNeon + "50",
  },
  emptyAddText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.successNeon,
  },
  addPlayerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.backgroundRoot,
  },
  addPlayerTitle: {
    fontSize: Typography.h4.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  addPlayerContent: {
    flex: 1,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    marginBottom: Spacing.md,
  },
  searchInput: {
    flex: 1,
    paddingVertical: Spacing.md,
    paddingLeft: Spacing.sm,
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
  },
  playerList: {
    flex: 1,
  },
  noPlayersText: {
    textAlign: "center",
    color: Colors.dark.textMuted,
    paddingVertical: Spacing.xl,
  },
  selectablePlayerRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  selectedPlayerName: {
    fontSize: Typography.h3.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
    textAlign: "center",
    marginBottom: Spacing.xl,
  },
  dateLabel: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.textMuted,
    marginBottom: Spacing.sm,
  },
  datePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.dark.successNeon + "30",
  },
  datePickerText: {
    fontSize: Typography.h4.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  webDateInput: {
    flex: 1,
    fontSize: Typography.h4.fontSize,
    fontWeight: "600",
    color: Colors.dark.successNeon,
    padding: 0,
    marginLeft: Spacing.sm,
  },
  saveButton: {
    backgroundColor: Colors.dark.successNeon,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    alignItems: "center",
    marginTop: Spacing.md,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "700",
    color: Colors.dark.backgroundRoot,
  },
  backfillSubtitle: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.textMuted,
    marginBottom: Spacing.lg,
  },
  attendanceRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  attendanceRowSelected: {
    borderWidth: 1,
    borderColor: Colors.dark.successNeon,
  },
  attendanceCheck: {
    marginRight: Spacing.md,
  },
  attendanceInfo: {
    flex: 1,
  },
  attendanceDate: {
    fontSize: Typography.body.fontSize,
    fontWeight: "500",
    color: Colors.dark.text,
  },
  attendanceWeek: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
  },
  packageCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.lg,
    marginBottom: Spacing.sm,
    borderWidth: 1,
    borderColor: "transparent",
  },
  packageCardSelected: {
    borderColor: Colors.dark.successNeon,
  },
  packageCardFlex: {
    flex: 1,
    marginBottom: 0,
  },
  templateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  templateDeleteButton: {
    padding: Spacing.md,
    backgroundColor: Colors.dark.error + "15",
    borderRadius: BorderRadius.md,
    alignItems: "center",
    justifyContent: "center",
  },
  packageInfo: {
    flex: 1,
  },
  packageName: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  packageDetails: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginTop: Spacing.xs,
  },
  packagePrice: {
    fontSize: Typography.h4.fontSize,
    fontWeight: "700",
    color: Colors.dark.successNeon,
  },
  skipButton: {
    paddingVertical: Spacing.lg,
    alignItems: "center",
    marginTop: Spacing.md,
  },
  skipButtonDisabled: {
    opacity: 0.5,
  },
  skipButtonText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.textMuted,
    textDecorationLine: "underline",
  },
  createPackageButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.dark.successNeon,
    borderStyle: "dashed",
    marginTop: Spacing.lg,
    marginBottom: Spacing.lg,
  },
  createPackageButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.successNeon,
  },
  infoBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: Spacing.sm,
    backgroundColor: Backgrounds.surface,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.lg,
  },
  infoBoxText: {
    flex: 1,
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    lineHeight: 18,
  },
  creditAccordion: {
    marginBottom: Spacing.md,
    borderRadius: BorderRadius.lg,
    overflow: "hidden",
    backgroundColor: Backgrounds.card,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  creditAccordionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: Spacing.md,
  },
  creditAccordionHeaderExpanded: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
  },
  creditAccordionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
  },
  creditTypeIcon: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.md,
    alignItems: "center",
    justifyContent: "center",
  },
  creditAccordionTitle: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  creditAccordionSubtitle: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  creditOptionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  creditOption: {
    width: "48%",
    aspectRatio: 1.3,
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: BorderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "transparent",
  },
  creditOptionSelected: {
    borderColor: Colors.dark.successNeon,
    backgroundColor: Colors.dark.successNeon + "15",
  },
  creditOptionCredits: {
    fontSize: 28,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  creditOptionLabel: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  creditOptionPrice: {
    fontSize: Typography.small.fontSize,
    fontWeight: "600",
    color: Colors.dark.successNeon,
    marginTop: Spacing.xs,
  },
  creditOptionTextSelected: {
    color: Colors.dark.successNeon,
  },
  assignPackageButton: {
    backgroundColor: Colors.dark.successNeon,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    alignItems: "center",
    marginTop: Spacing.md,
  },
  assignPackageButtonDisabled: {
    opacity: 0.5,
  },
  assignPackageButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.backgroundRoot,
  },
  templateSection: {
    marginTop: Spacing.lg,
    paddingTop: Spacing.lg,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.06)",
  },
  templateSectionTitle: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginBottom: Spacing.md,
  },
  createPackageForm: {
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.lg,
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.dark.successNeon,
  },
  createPackageTitle: {
    fontSize: Typography.body.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
    marginBottom: Spacing.lg,
  },
  formField: {
    marginBottom: Spacing.md,
  },
  formRow: {
    flexDirection: "row",
    marginBottom: Spacing.sm,
  },
  formLabel: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "500",
    color: Colors.dark.textMuted,
    marginBottom: Spacing.xs,
  },
  formInput: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.sm,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  totalPricePreview: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.successNeon,
    textAlign: "center",
    marginBottom: Spacing.lg,
  },
  formActions: {
    flexDirection: "row",
    gap: Spacing.md,
  },
  formCancelButton: {
    flex: 1,
    paddingVertical: Spacing.md,
    alignItems: "center",
    borderRadius: BorderRadius.md,
    backgroundColor: Backgrounds.surface,
  },
  formCancelButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "500",
    color: Colors.dark.textMuted,
  },
  formSaveButton: {
    flex: 1,
    paddingVertical: Spacing.md,
    alignItems: "center",
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.dark.successNeon,
  },
  formSaveButtonDisabled: {
    opacity: 0.5,
  },
  formSaveButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.backgroundRoot,
  },
  timelineContentClickable: {
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.sm,
    padding: Spacing.sm,
    marginLeft: -Spacing.sm,
  },
  timelineStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  attendanceModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.lg,
  },
  attendanceModalTitle: {
    fontSize: Typography.h3.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  attendanceModalDate: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.textMuted,
  },
  attendancePlayerRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.lg,
    marginBottom: Spacing.sm,
  },
  attendancePlayerInfo: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  attendancePlayerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.dark.successNeon + "20",
    alignItems: "center",
    justifyContent: "center",
    marginRight: Spacing.md,
  },
  attendancePlayerInitial: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.successNeon,
  },
  attendancePlayerName: {
    fontSize: Typography.body.fontSize,
    fontWeight: "500",
    color: Colors.dark.text,
  },
  attendanceToggle: {
    flexDirection: "row",
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: BorderRadius.md,
    padding: Spacing.xs,
  },
  attendanceToggleOption: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
  },
  attendanceToggleActive: {
    backgroundColor: Colors.dark.successNeon,
  },
  attendanceToggleAbsent: {
    backgroundColor: Colors.dark.error,
  },
  attendanceToggleVacation: {
    backgroundColor: Colors.dark.gold,
  },
  attendanceToggleText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "600",
    color: Colors.dark.textMuted,
  },
  attendanceToggleTextActive: {
    color: Colors.dark.backgroundRoot,
  },
  attendanceActions: {
    marginTop: Spacing.xl,
    gap: Spacing.md,
  },
  cancelSessionButton: {
    backgroundColor: Colors.dark.error + "20",
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.dark.error,
    flexDirection: "row",
    justifyContent: "center",
    gap: Spacing.sm,
    marginTop: Spacing.md,
  },
  cancelSessionButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.error,
  },
  deleteSessionButton: {
    backgroundColor: "#FF444420",
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#FF4444",
    flexDirection: "row",
    justifyContent: "center",
    gap: Spacing.sm,
    marginTop: Spacing.md,
  },
  deleteSessionButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: "#FF4444",
  },
  webTimePickerRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  webTimeInput: {
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    fontSize: Typography.h3.fontSize,
    fontWeight: "600",
    color: Colors.dark.accentCyan,
    textAlign: "center",
    minWidth: 100,
    borderWidth: 1,
    borderColor: Colors.dark.accentCyan + "40",
  },
  timePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.dark.accentCyan + "40",
  },
  timePickerText: {
    fontSize: Typography.h3.fontSize,
    fontWeight: "600",
    color: Colors.dark.accentCyan,
  },
  transferButton: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    flexDirection: "row",
    justifyContent: "center",
    gap: Spacing.sm,
  },
  transferButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  transferModalContent: {
    backgroundColor: Backgrounds.card,
    borderTopLeftRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
    padding: Spacing.lg,
    maxHeight: "75%",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderBottomWidth: 0,
  },
  transferModalGlow: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 120,
    borderTopLeftRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
  },
  transferModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: Spacing.lg,
    zIndex: 1,
  },
  transferModalTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
  },
  transferIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: Colors.dark.accentCyan + "20",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.dark.accentCyan + "40",
  },
  transferModalTitle: {
    fontSize: Typography.h2.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
    letterSpacing: 0.3,
  },
  transferModalSubtitle: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  transferCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.dark.textMuted + "30",
    alignItems: "center",
    justifyContent: "center",
  },
  transferInfoCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: Colors.dark.accentCyan + "10",
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    gap: Spacing.sm,
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.dark.accentCyan + "25",
  },
  transferInfoText: {
    flex: 1,
    fontSize: Typography.small.fontSize,
    color: Colors.dark.textMuted,
    lineHeight: 18,
  },
  transferSectionLabel: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "600",
    color: Colors.dark.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: Spacing.sm,
  },
  transferCoachList: {
    flex: 1,
    marginBottom: Spacing.lg,
  },
  noCoachesContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.xl * 2,
    gap: Spacing.md,
  },
  noCoachesText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.textMuted,
  },
  transferCoachCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: Spacing.md,
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.lg,
    marginBottom: Spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    overflow: "hidden",
  },
  transferCoachCardActive: {
    borderColor: GlowColors.primary,
  },
  transferCoachAvatar: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: Colors.dark.textMuted + "25",
    alignItems: "center",
    justifyContent: "center",
    marginRight: Spacing.md,
  },
  transferCoachAvatarActive: {
    backgroundColor: GlowColors.primary + "30",
  },
  transferCoachAvatarText: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.dark.textMuted,
  },
  transferCoachAvatarTextActive: {
    color: GlowColors.primary,
  },
  transferCoachInfo: {
    flex: 1,
  },
  transferCoachName: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  transferCoachRole: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  transferCheckmark: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: GlowColors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  transferRadio: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: Colors.dark.textMuted + "50",
  },
  transferActions: {
    gap: Spacing.sm,
  },
  transferConfirmButton: {
    borderRadius: BorderRadius.md,
    overflow: "hidden",
  },
  transferConfirmButtonDisabled: {
    opacity: 0.6,
  },
  transferConfirmGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    gap: Spacing.sm,
  },
  transferConfirmText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "700",
    color: "rgba(255, 255, 255, 0.06)",
  },
  transferConfirmTextDisabled: {
    color: Colors.dark.textMuted,
  },
  restoreModalContent: {
    backgroundColor: Backgrounds.card,
    borderTopLeftRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
    padding: Spacing.lg,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderBottomWidth: 0,
    zIndex: 10,
  },
  restoreModalGlow: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 100,
    borderTopLeftRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
  },
  restoreModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.lg,
  },
  restoreModalTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  restoreModalTitle: {
    fontSize: Typography.h2.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  restoreCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Backgrounds.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  restoreSessionContent: {
    alignItems: "center",
    paddingVertical: Spacing.md,
  },
  restoreSessionCard: {
    width: "100%",
    marginBottom: Spacing.lg,
    borderRadius: BorderRadius.lg,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colors.dark.accentCyan + "40",
  },
  restoreSessionCardGradient: {
    padding: Spacing.xl,
    alignItems: "center",
  },
  restoreSessionIconContainer: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: Colors.dark.accentCyan + "20",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.md,
    borderWidth: 2,
    borderColor: Colors.dark.accentCyan + "50",
  },
  restoreSessionDate: {
    fontSize: 22,
    fontWeight: "700",
    color: Colors.dark.text,
    marginBottom: Spacing.xs,
  },
  restoreSessionWeek: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.accentCyan,
  },
  restoreSessionDescription: {
    fontSize: Typography.body.fontSize,
    fontWeight: "500",
    color: Colors.dark.text,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: Spacing.xl,
    paddingHorizontal: Spacing.md,
  },
  sectionLabel: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "600",
    color: "#FFFFFF",
    textTransform: "uppercase" as const,
    letterSpacing: 1,
  },
  restoreButton: {
    width: "100%",
    borderRadius: BorderRadius.md,
    overflow: "hidden",
  },
  restoreButtonGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md + 2,
    paddingHorizontal: Spacing.xl,
  },
  restoreButtonPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.98 }],
  },
  restoreButtonDisabled: {
    opacity: 0.5,
  },
  restoreButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  creditHintBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    marginTop: Spacing.lg,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
  },
  creditHintBoxPrivate: {
    borderColor: Colors.dark.sessionPrivate + "40",
    backgroundColor: Colors.dark.sessionPrivate + "10",
  },
  creditHintBoxSemi: {
    borderColor: Colors.dark.sessionSemiPrivate + "40",
    backgroundColor: Colors.dark.sessionSemiPrivate + "10",
  },
  creditHint: {
    fontSize: Typography.caption.fontSize,
    textAlign: "center",
  },
  creditHintPrivate: {
    color: Colors.dark.sessionPrivate,
  },
  creditHintSemi: {
    color: Colors.dark.sessionSemiPrivate,
  },
  deleteSeriesSection: {
    marginTop: Spacing.xl,
    paddingTop: Spacing.lg,
    borderTopWidth: 1,
    borderTopColor: Colors.dark.border,
    gap: Spacing.md,
  },
  extendSeriesButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.dark.accent + "40",
    backgroundColor: Colors.dark.accent + "10",
    marginBottom: Spacing.sm,
  },
  extendSeriesButtonDisabled: {
    opacity: 0.5,
  },
  extendSeriesButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.accent,
  },
  completeSeriesButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.dark.successNeon + "40",
    backgroundColor: Colors.dark.successNeon + "10",
  },
  completeSeriesButtonDisabled: {
    opacity: 0.5,
  },
  completeSeriesButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.successNeon,
  },
  completedBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.dark.successNeon + "15",
    borderWidth: 1,
    borderColor: Colors.dark.successNeon + "30",
  },
  completedBadgeText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.successNeon,
  },
  completedDateText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginLeft: Spacing.sm,
  },
  deleteSeriesButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    backgroundColor: Colors.dark.error + "15",
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.dark.error + "40",
  },
  deleteSeriesButtonDisabled: {
    opacity: 0.5,
  },
  deleteSeriesButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.error,
  },
  modalContent: {
    backgroundColor: Backgrounds.card,
    borderTopLeftRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderBottomWidth: 0,
  },
  modalContentElevated: {
    position: "relative",
    zIndex: 10,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.md,
  },
  modalTitle: {
    fontSize: Typography.h3.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  modalSubtitle: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.textMuted,
    marginBottom: Spacing.lg,
  },
  dateFieldsRow: {
    flexDirection: "row",
    gap: Spacing.md,
    marginBottom: Spacing.lg,
  },
  dateField: {
    flex: 1,
  },
  fieldLabel: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginBottom: Spacing.xs,
  },
  dateButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.dark.backgroundTertiary,
  },
  dateButtonText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
  },
  reasonField: {
    marginBottom: Spacing.lg,
  },
  reasonInput: {
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
    borderWidth: 1,
    borderColor: Colors.dark.backgroundTertiary,
  },
  modalActions: {
    flexDirection: "row",
    gap: Spacing.md,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.dark.backgroundTertiary,
  },
  cancelButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  confirmButton: {
    flex: 1,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    alignItems: "center",
    backgroundColor: Colors.dark.successNeon,
  },
  pauseConfirmButton: {
    backgroundColor: Colors.dark.gold,
  },
  removeConfirmButton: {
    backgroundColor: Colors.dark.error,
  },
  confirmButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.backgroundRoot,
  },
  confirmButtonDisabled: {
    opacity: 0.5,
  },
  dateValidationError: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.error,
    marginBottom: Spacing.md,
    textAlign: "center",
  },
  planTabContainer: {
    padding: Spacing.lg,
  },
  planHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  planHeaderTitle: {
    fontSize: Typography.h3.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  planHeaderSubtitle: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.textMuted,
    marginBottom: Spacing.lg,
  },
  planEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing["2xl"],
  },
  planEmptyTitle: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
    marginTop: Spacing.md,
  },
  planEmptySubtitle: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginTop: Spacing.xs,
    textAlign: "center",
  },
  planSessionsList: {
    marginBottom: Spacing.lg,
  },
  planSectionTitle: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "600",
    color: Colors.dark.textMuted,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: Spacing.md,
  },
  planSessionCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  planSessionInfo: {
    flex: 1,
  },
  planSessionDate: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  planSessionTime: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  planSessionStatus: {
    marginLeft: Spacing.md,
  },
  planReadyBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.successNeon + "20",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
  },
  planReadyText: {
    fontSize: Typography.small.fontSize,
    fontWeight: "600",
    color: Colors.dark.successNeon,
  },
  planNeededBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.gold + "20",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
  },
  planNeededText: {
    fontSize: Typography.small.fontSize,
    fontWeight: "600",
    color: Colors.dark.gold,
  },
  planMoreText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    textAlign: "center",
    marginTop: Spacing.sm,
  },
  planTemplatesSection: {
    marginTop: Spacing.md,
  },
  planActionButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    gap: Spacing.md,
  },
  planActionText: {
    flex: 1,
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
  },
  extendModalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: Spacing.lg,
  },
  extendModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Backgrounds.overlay,
  },
  extendModalContent: {
    backgroundColor: Backgrounds.elevated,
    borderRadius: BorderRadius.xl,
    padding: Spacing.xl,
    width: "100%",
    maxWidth: 380,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 16,
  },
  extendModalHeader: {
    alignItems: "center",
    marginBottom: Spacing.xl,
  },
  extendModalTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: Colors.dark.text,
    marginTop: Spacing.md,
  },
  extendModalSubtitle: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.textSecondary,
    marginTop: Spacing.xs,
    textAlign: "center",
  },
  extendModalLabel: {
    fontSize: Typography.small.fontSize,
    fontWeight: "600",
    color: Colors.dark.textSecondary,
    marginBottom: Spacing.md,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  weekOptionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
    marginBottom: Spacing.xl,
  },
  weekOption: {
    width: "30%",
    aspectRatio: 1.2,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.dark.border,
    backgroundColor: Backgrounds.card,
  },
  weekOptionSelected: {
    borderColor: Colors.dark.accent,
    backgroundColor: Colors.dark.accent + "20",
  },
  weekOptionText: {
    fontSize: 24,
    fontWeight: "700",
    color: Colors.dark.textSecondary,
  },
  weekOptionTextSelected: {
    color: Colors.dark.accent,
  },
  weekOptionSubtext: {
    fontSize: 11,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  weekOptionSubtextSelected: {
    color: Colors.dark.accent,
  },
  extendModalFooter: {
    flexDirection: "row",
    gap: Spacing.md,
  },
  extendCancelButton: {
    flex: 1,
    paddingVertical: Spacing.md,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.dark.border,
  },
  extendCancelButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.textSecondary,
  },
  extendConfirmButton: {
    flex: 2,
    borderRadius: BorderRadius.md,
    overflow: "hidden",
  },
  extendConfirmGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
  },
  extendConfirmButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "700",
    color: Colors.dark.backgroundRoot,
  },
  guestBadge: {
    backgroundColor: Colors.dark.orange + "25",
    borderWidth: 1,
    borderColor: Colors.dark.orange + "50",
    borderRadius: BorderRadius.xs,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  guestBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.dark.orange,
    letterSpacing: 0.5,
  },
  guestToggleContainer: {
    marginTop: Spacing.lg,
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.dark.orange + "20",
  },
  guestToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  guestToggleLabel: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  guestToggleSubtext: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  guestToggleSwitch: {
    width: 48,
    height: 28,
    borderRadius: 14,
    backgroundColor: Colors.dark.textMuted + "40",
    justifyContent: "center",
    padding: 2,
  },
  guestToggleSwitchActive: {
    backgroundColor: Colors.dark.orange,
  },
  guestToggleKnob: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colors.dark.text,
  },
  guestToggleKnobActive: {
    alignSelf: "flex-end",
    backgroundColor: Colors.dark.backgroundRoot,
  },
  guestDateSection: {
    marginTop: Spacing.md,
    gap: Spacing.sm,
  },
  guestDateLabel: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "600",
    color: Colors.dark.orange,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  guestQuickButtons: {
    flexDirection: "row",
    gap: Spacing.sm,
  },
  guestQuickBtn: {
    flex: 1,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.dark.backgroundDefault,
    borderWidth: 1,
    borderColor: Colors.dark.textMuted + "30",
    alignItems: "center",
  },
  guestQuickBtnActive: {
    borderColor: Colors.dark.orange,
    backgroundColor: Colors.dark.orange + "15",
  },
  guestQuickBtnText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "600",
    color: Colors.dark.textMuted,
  },
  guestQuickBtnTextActive: {
    color: Colors.dark.orange,
  },
  smartFillCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.dark.orange + "20",
  },
  smartFillAddBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.orange,
    borderRadius: BorderRadius.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
  },
});
