-- Data migration: HEAD catalog import for Glow Market (Task #233)
-- Applied directly to DB; this file serves as a reproducible record of the changes made.

-- Step 1: Ensure brand column exists (also in 0006_shop_product_brand.sql)
ALTER TABLE shop_products ADD COLUMN IF NOT EXISTS brand varchar(100);

-- Step 2: Ensure cat-clothing and cat-footwear categories exist
INSERT INTO shop_categories (id, academy_id, name, slug, description, icon_name, icon_color, is_active, "order")
VALUES 
  ('cat-clothing', 'default-academy', 'Clothing', 'clothing', 'HEAD sportswear and apparel', 'disc', '#00D9FF', true, 6),
  ('cat-footwear', 'default-academy', 'Footwear', 'footwear', 'HEAD tennis shoes', 'chevron-up', '#00D9FF', true, 5)
ON CONFLICT (id) DO NOTHING;

-- Step 3: Remove demo products (deactivate prod-wilson-pro due to FK constraint from shop_order_items)
DELETE FROM shop_products WHERE id IN ('prod-wilson-bag','prod-head-speed','prod-asics-gel','prod-nike-court','prod-luxilon-alu');
UPDATE shop_products SET is_active = false WHERE id = 'prod-wilson-pro';

-- Step 4: Set brand = 'HEAD' on all existing active products for default-academy
UPDATE shop_products SET brand = 'HEAD' WHERE academy_id = 'default-academy' AND is_active = true AND brand IS NULL;

-- Step 5: Import HEAD rackets (cat-rackets)
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD 17 inch Junior Tennis Racquet Paw Patrol Edition', 'head-17-inch-junior-tennis-racquet-paw-patrol-edition', 'Junior 17 inch racquet', 194.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/06/232225_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD 19 inch Junior Tennis Racquet Paw Patrol Edition', 'head-19-inch-junior-tennis-racquet-paw-patrol-edition', 'Junior 19 inch racquet', 194.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/06/232215_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD 21 inch Junior Tennis Racquet Paw Patrol Edition', 'head-21-inch-junior-tennis-racquet-paw-patrol-edition', 'Junior 21 inch racquet', 194.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/06/232205_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Boom Junior 25 inch Tennis Racquet', 'head-boom-junior-25-inch-tennis-racquet', 'Junior 25 inch Boom racquet', 661.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2026/01/230174_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Boom Junior 26 inch Tennis Racquet', 'head-boom-junior-26-inch-tennis-racquet', 'Junior 26 inch Boom racquet', 661.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/230164_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Boom MP L Tennis Racquet Alternate Design', 'head-boom-mp-l-tennis-racquet-alternate-design', 'Adult Boom MP L Alternate Design racquet', 1344.00, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2024/06/230424_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Boom MP Tennis Racquet', 'head-boom-mp-tennis-racquet', 'Adult Boom MP racquet', 1396.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/230114_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Boom MP Tennis Racquet Alternate Design', 'head-boom-mp-tennis-racquet-alternate-design', 'Adult Boom MP Alternate Design racquet', 1396.50, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2024/06/230414_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Boom Pro Tennis Racquet', 'head-boom-pro-tennis-racquet', 'Adult Boom Pro racquet', 1438.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/230104_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Boom Team L Tennis Racquet', 'head-boom-team-l-tennis-racquet', 'Adult Boom Team L racquet', 1202.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/230144_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Boom Team L Tennis Racquet Alternate Design', 'head-boom-team-l-tennis-racquet-alternate-design', 'Adult Boom Team L Alternate Design racquet', 1202.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/230444_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Boom Team Tennis Racquet', 'head-boom-team-tennis-racquet', 'Adult Boom Team racquet', 1155.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/230134_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Coco 17 inch junior Tennis Racquet', 'head-coco-17-inch-junior-tennis-racquet', 'Junior 17 inch racquet', 178.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235844_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Coco 19 inch junior Tennis Racquet', 'head-coco-19-inch-junior-tennis-racquet', 'Junior 19 inch racquet', 178.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235834_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Coco 21 inch junior Tennis Racquet', 'head-coco-21-inch-junior-tennis-racquet', 'Junior 21 inch racquet', 178.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235824_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Coco 23 inch junior Tennis Racquet', 'head-coco-23-inch-junior-tennis-racquet', 'Junior 23 inch racquet', 178.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235814_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Coco 25 inch junior Tennis Racquet', 'head-coco-25-inch-junior-tennis-racquet', 'Junior 25 inch racquet', 178.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235804_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Extreme Elite 2024 Tennis Racquet', 'head-extreme-elite-2024-tennis-racquet', 'Adult Extreme Elite 2024 racquet', 840.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/07/231144_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Extreme Junior 21 inch Tennis Racquet', 'head-extreme-junior-21-inch-tennis-racquet', 'Junior 21 inch Extreme racquet', 220.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/06/231434_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Extreme Junior 23 inch Tennis Racquet', 'head-extreme-junior-23-inch-tennis-racquet', 'Junior 23 inch Extreme racquet', 220.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/01/231424_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Extreme Junior 25 inch Tennis Racquet', 'head-extreme-junior-25-inch-tennis-racquet', 'Junior 25 inch Extreme racquet', 220.50, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2025/01/231414_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Extreme Junior 26 inch Tennis Racquet', 'head-extreme-junior-26-inch-tennis-racquet', 'Junior 26 inch Extreme racquet', 220.50, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2025/01/231404_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Extreme MP 2024 Tennis Racquet', 'head-extreme-mp-2024-tennis-racquet', 'Adult Extreme MP 2024 racquet', 1328.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/07/231114_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Extreme MP L 2024 Tennis Racquet', 'head-extreme-mp-l-2024-tennis-racquet', 'Adult Extreme MP L 2024 racquet', 1260.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/07/231124_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Extreme MP L Tennis Racquet', 'head-extreme-mp-l-tennis-racquet', 'Adult Extreme MP L racquet', 1144.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235322_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Extreme Pro 2024 Tennis Racquet', 'head-extreme-pro-2024-tennis-racquet', 'Adult Extreme Pro 2024 racquet', 1365.00, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2024/07/231104_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Extreme Tour Tennis Racquet', 'head-extreme-tour-tennis-racquet', 'Adult Extreme Tour racquet', 1249.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235302_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Geo Speed Tennis Racquet', 'head-geo-speed-tennis-racquet', 'Adult Geo Speed racquet', 309.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/01/231375_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Gravity MP 2025 Tennis Racquet', 'head-gravity-mp-2025-tennis-racquet', 'Adult Gravity MP 2025 racquet', 1433.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/01/231125_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Gravity MP L 2025 Tennis Racquet', 'head-gravity-mp-l-2025-tennis-racquet', 'Adult Gravity MP L 2025 racquet', 1396.50, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2025/01/231135_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Gravity Pro 2025 Tennis Racquet', 'head-gravity-pro-2025-tennis-racquet', 'Adult Gravity Pro 2025 racquet', 1438.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/01/231105_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Gravity Pro Tennis Racquet', 'head-gravity-pro-tennis-racquet', 'Adult Gravity Pro racquet', 1438.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235303_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Gravity Team L Tennis Racquet', 'head-gravity-team-l-tennis-racquet', 'Adult Gravity Team L racquet', 1202.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235353_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Gravity Team Tennis Racquet', 'head-gravity-team-tennis-racquet', 'Adult Gravity Team racquet', 1328.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235343_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Gravity Tour 2025 Tennis Racquet', 'head-gravity-tour-2025-tennis-racquet', 'Adult Gravity Tour 2025 racquet', 1433.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/01/231115_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Gravity Tour Tennis Racquet', 'head-gravity-tour-tennis-racquet', 'Adult Gravity Tour racquet', 1433.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235313_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD IG Challenge MP Tennis Racquet', 'head-ig-challenge-mp-tennis-racquet', 'Adult IG Challenge MP racquet', 614.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235404_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD IG Challenge TEAM L Tennis Racquet', 'head-ig-challenge-team-l-tennis-racquet', 'Adult IG Challenge Team L racquet', 582.75, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235444_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD IG Challenge TEAM Tennis Racquet', 'head-ig-challenge-team-tennis-racquet', 'Adult IG Challenge Team racquet', 598.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235424_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD IG Speed Jr. 23 inch Tennis Racquet', 'head-ig-speed-jr-23-inch-tennis-racquet', 'Junior 23 inch IG Speed racquet', 309.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/230024_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD IG Speed Junior 25 inch Tennis Racquet', 'head-ig-speed-junior-25-inch-tennis-racquet', 'Junior 25 inch IG Speed racquet', 341.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/230014_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD IG Speed Junior 26 inch Tennis Racquet', 'head-ig-speed-junior-26-inch-tennis-racquet', 'Junior 26 inch IG Speed racquet', 367.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/230004_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Instinct MP 2025 Tennis Racquet', 'head-instinct-mp-2025-tennis-racquet', 'Adult Instinct MP 2025 racquet', 1065.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/12/232005_1-1-595x595.png', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Instinct Team 2025 Tennis Racquet', 'head-instinct-team-2025-tennis-racquet', 'Adult Instinct Team 2025 racquet', 971.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/12/232015_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Instinct Team L 2025 Tennis Racquet', 'head-instinct-team-l-2025-tennis-racquet', 'Adult Instinct Team L 2025 racquet', 924.00, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2024/12/232025_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD MX Attitude COMP Tennis Racquet', 'head-mx-attitude-comp-tennis-racquet', 'Adult MX Attitude Comp racquet', 388.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/234733_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD MX Attitude COMP Tennis Racquet Blue', 'head-mx-attitude-comp-tennis-racquet-blue', 'Adult MX Attitude Comp racquet', 388.50, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2025/06/231325_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD MX Attitude ELITE Tennis Racquet Pink', 'head-mx-attitude-elite-tennis-racquet-pink', 'Adult MX Attitude Elite racquet', 357.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/06/231355_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD MX Attitude ELITE Tennis Racquet Yellow', 'head-mx-attitude-elite-tennis-racquet-yellow', 'Adult MX Attitude Elite racquet', 357.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/06/231345_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Mx Attitude Suprm Tennis Racquet Black', 'head-mx-attitude-suprm-tennis-racquet-black', 'Adult MX Attitude Supreme racquet', 477.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2026/01/231305_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD MX Attitude SUPRM Tennis Racquet Mint', 'head-mx-attitude-suprm-tennis-racquet-mint', 'Adult MX Attitude Supreme racquet', 477.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/06/231315_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD MX Spark COMP Tennis Racquet', 'head-mx-spark-comp-tennis-racquet', 'Adult MX Spark Comp racquet', 388.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235334_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD MX Spark SUPRM Tennis Racquet', 'head-mx-spark-suprm-tennis-racquet', 'Adult MX Spark Supreme racquet', 477.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235314_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD MXG 3 Tennis Racquet', 'head-mxg-3-tennis-racquet', 'Adult MXG 3 racquet', 1365.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/238707_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Novak 17 inch junior Tennis Racquet', 'head-novak-17-inch-junior-tennis-racquet', 'Junior 17 inch racquet', 178.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/08/235044_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Novak 19 inch junior Tennis Racquet', 'head-novak-19-inch-junior-tennis-racquet', 'Junior 19 inch racquet', 178.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235034_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Novak 21 inch junior Tennis Racquet', 'head-novak-21-inch-junior-tennis-racquet', 'Junior 21 inch racquet', 178.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235024_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Novak 23 inch junior Tennis Racquet', 'head-novak-23-inch-junior-tennis-racquet', 'Junior 23 inch racquet', 178.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235014_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Novak 25 inch junior Tennis Racquet', 'head-novak-25-inch-junior-tennis-racquet', 'Junior 25 inch racquet', 178.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235004_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Prestige MP Tennis Racquet', 'head-prestige-mp-tennis-racquet', 'Adult Prestige MP racquet', 1433.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/236123_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Radical Junior 23 inch Tennis Racquet', 'head-radical-junior-23-inch-tennis-racquet', 'Junior 23 inch Radical racquet', 220.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/01/231425_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Radical Junior 25 inch Tennis Racquet', 'head-radical-junior-25-inch-tennis-racquet', 'Junior 25 inch Radical racquet', 220.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2025/01/231415_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Radical Junior 26 inch Tennis Racquet', 'head-radical-junior-26-inch-tennis-racquet', 'Junior 26 inch Radical racquet', 220.50, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2025/01/231405_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Radical MP Tennis Racquet', 'head-radical-mp-tennis-racquet', 'Adult Radical MP racquet', 1312.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235113_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Radical Pro Tennis Racquet', 'head-radical-pro-tennis-racquet', 'Adult Radical Pro racquet', 1312.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235103_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Radical Team L Tennis Racquet', 'head-radical-team-l-tennis-racquet', 'Adult Radical Team L racquet', 1155.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235133_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Radical Team Tennis Racquet', 'head-radical-team-tennis-racquet', 'Adult Radical Team racquet', 1260.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/235123_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Speed Elite Tennis Racquet', 'head-speed-elite-tennis-racquet', 'Adult Speed Elite racquet', 871.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2026/01/232106_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Speed Junior 25 inch Tennis Racquet', 'head-speed-junior-25-inch-tennis-racquet', 'Junior 25 inch Speed racquet', 152.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/236064_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Speed Junior 26 inch Tennis Racquet', 'head-speed-junior-26-inch-tennis-racquet', 'Junior 26 inch Speed racquet', 630.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/236054_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Speed MP L Tennis Racquet', 'head-speed-mp-l-tennis-racquet', 'Adult Speed MP L racquet', 1365.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/236024_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Speed MP Legend Limited Edition Tennis Racquet', 'head-speed-mp-legend-limited-edition-tennis-racquet', 'Adult Speed MP Legend Limited Edition racquet', 1433.25, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2025/08/232076_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Speed MP Tennis Racquet', 'head-speed-mp-tennis-racquet', 'Adult Speed MP racquet', 1386.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/236014_1-595x595.jpg', true, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Speed MP UL Tennis Racquet', 'head-speed-mp-ul-tennis-racquet', 'Adult Speed MP UL racquet', 1207.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2026/01/232046_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Speed Pro Legend Limited Edition Tennis Racquet', 'head-speed-pro-legend-limited-edition-tennis-racquet', 'Adult Speed Pro Legend Limited Edition racquet', 1438.50, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2025/08/232066_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Speed Pro Tennis Racquet', 'head-speed-pro-tennis-racquet', 'Adult Speed Pro racquet', 1396.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/236004_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Speed Team Tennis Racquet', 'head-speed-team-tennis-racquet', 'Adult Speed Team racquet', 1281.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/236034_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Speed Tour Tennis Racquet', 'head-speed-tour-tennis-racquet', 'Adult Speed Tour racquet', 1396.50, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2026/01/232016_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Ti. Conquest Tennis Racquet', 'head-ti-conquest-tennis-racquet', 'Adult Ti. Conquest racquet', 204.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/230394-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Ti. Radical Elite Tennis Racquet', 'head-ti-radical-elite-tennis-racquet', 'Adult Ti. Radical Elite racquet', 278.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/233402_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'HEAD Tour Pro Tennis Racquet', 'head-tour-pro-tennis-racquet', 'Adult Tour Pro racquet', 210.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/230384-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-rackets', 'Wilson Pro Staff 97', 'wilson-pro-staff-97', 'Pro-level racket for precision players', 1299.00, 'AED', 10, 'https://images.unsplash.com/photo-1617883861744-13b534e3b928?w=400', false, false, NULL, true, 1, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;

-- Step 5b: Import HEAD strings & grips (cat-strings)
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Dual Absorbing replacement grip', 'head-dual-absorbing-replacement-grip', 'Replacement grip', 36.75, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2024/07/285034_BK-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD FXP Tennis String', 'head-fxp-tennis-string', 'Individual set.', 89.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281006_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Hawk Rough Tennis String', 'head-hawk-rough-tennis-string', 'Individual set.', 84.00, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281126-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Hawk Tennis String', 'head-hawk-tennis-string', 'Individual set.', 105.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281103_BK-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Hawk Tennis String Reel', 'head-hawk-tennis-string-reel', '200m reel.', 735.00, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281113_BK-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Hawk Touch Tennis String', 'head-hawk-touch-tennis-string', 'Individual set.', 105.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/07/281204_AN-595x595.jpg', true, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Hawk Touch Tennis String Reel', 'head-hawk-touch-tennis-string-reel', '200m reel.', 918.75, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281234-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Hydrosorb Comfort replacement grip', 'head-hydrosorb-comfort-replacement-grip', 'Replacement grip', 36.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/285313_BK-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Hydrosorb Pro replacement grip', 'head-hydrosorb-pro-replacement-grip', 'Replacement grip', 36.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/285303_BK-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Hydrosorb replacement grip', 'head-hydrosorb-replacement-grip', 'Replacement grip', 36.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/285014_BKRD-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Intellitour Tennis String', 'head-intellitour-tennis-string', 'Individual set.', 89.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281002_GR-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Intellitour Tennis String Reel', 'head-intellitour-tennis-string-reel', '200m reel.', 966.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/12/281012_NT-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Lynx Tennis String', 'head-lynx-tennis-string', 'Individual set.', 68.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281784_AN-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Lynx Tennis String Reel', 'head-lynx-tennis-string-reel', '200m reel.', 729.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281794_AN-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Lynx Touch Tennis String', 'head-lynx-touch-tennis-string', 'Individual set.', 48.30, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/08/281042-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Lynx Touch Tennis String Reel', 'head-lynx-touch-tennis-string-reel', '200m reel.', 840.00, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281052_1-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Lynx Tour Tennis String', 'head-lynx-tour-tennis-string', 'Individual set.', 68.25, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281790_CP-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Lynx Tour Tennis String Reel', 'head-lynx-tour-tennis-string-reel', '200m reel.', 840.00, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281799_CP-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Master Tennis String', 'head-master-tennis-string', 'Individual set.', 15.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281023_WH-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Master Tennis String Reel', 'head-master-tennis-string-reel', '200m reel.', 231.00, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281033_NT-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Padel Pro Overgrips box of 60 pcs', 'head-padel-pro-overgrips-box-of-60-pcs', 'Padel overgrip bulk box of 60', 582.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/285121_BK-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Padel Pro Overgrips pack of 3 pcs', 'head-padel-pro-overgrips-pack-of-3-pcs', 'Padel overgrip pack of 3', 37.80, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2021/05/head_favicon.png', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Prestige Pro Overgrip pack of 3 pcs', 'head-prestige-pro-overgrip-pack-of-3-pcs', 'Overgrip pack of 3', 33.60, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2021/05/head_favicon.png', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Prime Tour Overgrip pack of 3 pcs', 'head-prime-tour-overgrip-pack-of-3-pcs', 'Overgrip pack of 3', 31.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2021/05/head_favicon.png', true, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Prime Tour Overgrips box of 60 pcs', 'head-prime-tour-overgrips-box-of-60-pcs', 'Overgrip bulk box of 60', 582.75, 'AED', 0, 'https://www.elpanonline.com/wp-content/uploads/2024/06/285661_BK-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Pro Grip Pack of 3 pcs', 'head-pro-grip-pack-of-3-pcs', 'Grip pack of 3', 50.40, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/08/285702-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD RIP Control Tennis String', 'head-rip-control-tennis-string', 'Individual set.', 78.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281099_BK-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Sonic Pro Tennis String', 'head-sonic-pro-tennis-string', 'Individual set.', 57.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281028_BK-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Sonic Pro Tennis String Reel', 'head-sonic-pro-tennis-string-reel', '200m reel.', 640.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281128_BK-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Super Comp Overgrip pack of 3 pcs', 'head-super-comp-overgrip-pack-of-3-pcs', 'Overgrip pack of 3', 31.50, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2021/05/head_favicon.png', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Synthetic Gut Tennis String', 'head-synthetic-gut-tennis-string', 'Individual set.', 29.40, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281111_BK-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Velocity MLT Tennis String', 'head-velocity-mlt-tennis-string', 'Individual set.', 57.75, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/06/281404_BK-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Xtreme Track Overwrap Pack of 3pcs', 'head-xtreme-track-overwrap-pack-of-3pcs', 'Overgrip pack of 3', 29.40, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2024/08/285124_BK-595x595.jpg', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;
INSERT INTO shop_products (academy_id, category_id, name, slug, short_description, price, currency, stock_quantity, image_url, is_featured, is_active, brand, track_inventory, "order", tags) VALUES ('default-academy', 'cat-strings', 'HEAD Xtremesoft Overgrip pack of 3 pcs', 'head-xtremesoft-overgrip-pack-of-3-pcs', 'Overgrip pack of 3', 29.40, 'AED', 10, 'https://www.elpanonline.com/wp-content/uploads/2021/05/head_favicon.png', false, true, 'HEAD', true, 0, '[]'::jsonb) ON CONFLICT (academy_id, slug) DO NOTHING;

-- Step 6: Set featured products (6 curated flagship items - one per major category)
UPDATE shop_products SET is_featured = false WHERE academy_id = 'default-academy';
UPDATE shop_products SET is_featured = true WHERE academy_id = 'default-academy' AND name = 'HEAD Speed MP Tennis Racquet';
UPDATE shop_products SET is_featured = true WHERE academy_id = 'default-academy' AND name = 'HEAD Hawk Touch Tennis String';
UPDATE shop_products SET is_featured = true WHERE academy_id = 'default-academy' AND name = 'HEAD Prime Tour Overgrip pack of 3 pcs';
UPDATE shop_products SET is_featured = true WHERE academy_id = 'default-academy' AND name LIKE '%Tour Backpack%Orange%';
UPDATE shop_products SET is_featured = true WHERE academy_id = 'default-academy' AND name = 'HEAD Sprint Pro 4.0 Men''s Tennis Shoes';
UPDATE shop_products SET is_featured = true WHERE academy_id = 'default-academy' AND name LIKE '%Club 25 Tech Polo%Men%'
  AND id = (SELECT id FROM shop_products WHERE academy_id = 'default-academy' AND name LIKE '%Club 25 Tech Polo%Men%' ORDER BY name LIMIT 1);

-- Step 7: Fix any image_url values that captured srcset content (cleanup to single 595x595 URL)
UPDATE shop_products 
SET image_url = REGEXP_REPLACE(image_url, '^.*?(https://www\.elpanonline\.com/wp-content/uploads/[^\s]+595x595\.[a-z]+).*$', '\1')
WHERE academy_id = 'default-academy' AND image_url LIKE '% %'
AND image_url ~ 'https://www\.elpanonline\.com/wp-content/uploads/[^\s]+595x595\.[a-z]+';

-- Verification summary (run to confirm):
-- SELECT category_id, count(*) FROM shop_products WHERE academy_id = 'default-academy' AND is_active = true GROUP BY category_id ORDER BY category_id;
-- Expected: cat-balls=14, cat-clothing=39, cat-footwear=30, cat-gear=59, cat-rackets=81, cat-strings=34
