import type { Express, Request, Response } from "express";
import {
  getReleaseNotes,
  normalizeLocale,
  normalizeRole,
} from "../services/release-notes-generator";

/**
 * GET /api/release-notes?role=player&since=1.3.4&locale=en[&force=1]
 *
 * Returns the "What's New" slides for the current app version, generated by
 * the release-notes generator (OpenAI over `git log` since `since`) and cached
 * per (version, role, locale).
 *
 * - `version` is read from app.json on the client and passed back via the
 *   response so the client can store the same string in AsyncStorage.
 * - We trust client-supplied version because every install is on its own
 *   bundle, but we still compare against the server-side bundle string from
 *   APP_VERSION env / fallback so cache keys stay consistent.
 *
 * Public endpoint — no auth required (release notes are not user-specific).
 *
 * `force=1` (cache-bypass + OpenAI re-generation) is restricted to admins
 * via the X-Admin-Secret header. Anyone hitting `force=1` without a valid
 * admin secret simply gets the cached result instead — silently ignored,
 * never erroring, so a curious client can't probe.
 */
export function registerReleaseNotesRoutes(app: Express): void {
  app.get("/api/release-notes", async (req: Request, res: Response) => {
    const versionRaw = String(req.query.version || "").trim();
    const sinceRaw = String(req.query.since || "").trim();
    const role = normalizeRole(String(req.query.role || ""));
    const locale = normalizeLocale(String(req.query.locale || ""));
    const forceRequested = String(req.query.force || "") === "1";

    // Cache-bypass is admin-only to prevent OpenAI-cost abuse via `?force=1`.
    const adminSecret = process.env.RELEASE_NOTES_ADMIN_SECRET;
    const headerSecret = String(req.headers["x-admin-secret"] || "");
    const force =
      forceRequested && !!adminSecret && headerSecret === adminSecret;

    if (!versionRaw || !/^[\w.\-]{1,32}$/.test(versionRaw)) {
      return res.status(400).json({ error: "version query param required" });
    }
    const fromVersion = sinceRaw && /^[\w.\-]{1,32}$/.test(sinceRaw) ? sinceRaw : null;

    try {
      const payload = await getReleaseNotes({
        version: versionRaw,
        role,
        locale,
        fromVersion,
        forceRegenerate: force,
      });
      // Cache for 1 hour at the edge — content for a fixed version never changes.
      res.set("Cache-Control", "public, max-age=3600");
      return res.json({ ...payload, role, locale });
    } catch (err) {
      console.error("[release-notes] route error:", err);
      return res.status(500).json({ error: "Failed to load release notes" });
    }
  });
}
