import { StyleSheet, Platform } from "react-native";
import { Colors, Spacing, BorderRadius, Typography, Backgrounds } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.dark.backgroundRoot,
  },
  centered: {
    justifyContent: "center",
    alignItems: "center",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: Spacing.xl,
    gap: Spacing.md,
  },
  loadingText: {
    color: Colors.dark.textMuted,
    fontSize: Typography.body.fontSize,
    marginTop: Spacing.sm,
  },
  headerGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 150,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  title: {
    ...Typography.h2,
    color: Colors.dark.text,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  addButton: {
    width: 44,
    height: 44,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.dark.orange,
    alignItems: "center",
    justifyContent: "center",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Backgrounds.card,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.md,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.md,
    gap: Spacing.sm,
  },
  searchInput: {
    flex: 1,
    ...Typography.body,
    color: Colors.dark.text,
    paddingVertical: Spacing.md,
  },
  filterToggle: {
    padding: Spacing.xs,
    marginLeft: Spacing.xs,
  },
  filterToggleActive: {
    backgroundColor: `${Colors.dark.orange}20`,
    borderRadius: BorderRadius.sm,
  },
  filterBadge: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.dark.orange,
    alignItems: "center",
    justifyContent: "center",
  },
  filterBadgeText: {
    ...Typography.small,
    fontSize: 10,
    color: Colors.dark.text,
    fontWeight: "700",
  },
  filterContainer: {
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    backgroundColor: Backgrounds.card,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.md,
    borderRadius: BorderRadius.md,
    gap: Spacing.sm,
  },
  filterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  filterLabel: {
    ...Typography.small,
    color: Colors.dark.textMuted,
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    width: 45,
  },
  filterChipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    flex: 1,
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  filterChipActive: {
    backgroundColor: `${Colors.dark.orange}20`,
    borderColor: Colors.dark.orange,
  },
  filterChipText: {
    ...Typography.small,
    color: Colors.dark.textMuted,
    fontSize: 12,
  },
  filterChipTextActive: {
    color: Colors.dark.orange,
    fontWeight: "600",
  },
  chipDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  filterDivider: {
    width: 1,
    height: 36,
    backgroundColor: Colors.dark.border,
    marginHorizontal: Spacing.xs,
  },
  clearFiltersButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.xs,
    paddingVertical: Spacing.sm,
    marginTop: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.dark.border,
  },
  clearFiltersText: {
    ...Typography.small,
    color: Colors.dark.orange,
    fontSize: 12,
  },
  list: {
    padding: Spacing.lg,
    paddingTop: 0,
  },
  playerCard: {
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    backgroundColor: Backgrounds.card,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderRadius: BorderRadius.md,
  },
  playerCardTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
  },
  playerCardBottom: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
    marginTop: Spacing.sm,
    paddingLeft: 52,
  },
  playerAvatar: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.full,
    backgroundColor: Backgrounds.card,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  playerInfo: {
    flex: 1,
  },
  playerName: {
    fontSize: 15,
    color: Colors.dark.text,
    fontWeight: "600",
  },
  playerEmail: {
    fontSize: 12,
    color: Colors.dark.textMuted,
    marginTop: 1,
  },
  ballBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
    gap: 4,
  },
  ballDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  ballText: {
    ...Typography.caption,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  levelText: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
  },
  coachText: {
    ...Typography.caption,
    color: Colors.dark.xpCyan,
  },
  creditsContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  creditsBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
    gap: 4,
  },
  invoiceBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: BorderRadius.sm,
    gap: 3,
  },
  invoiceBadgeText: {
    fontSize: 10,
    fontWeight: "700",
  },
  creditsText: {
    ...Typography.caption,
    fontWeight: "700",
  },
  playerCardWrapper: {
    marginBottom: Spacing.sm,
  },
  playerCardExpanded: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    marginBottom: 0,
    borderBottomWidth: 0,
  },
  expandedContent: {
    backgroundColor: Backgrounds.card,
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderBottomLeftRadius: BorderRadius.md,
    borderBottomRightRadius: BorderRadius.md,
    padding: Spacing.lg,
    paddingTop: Spacing.md,
  },
  quickStatsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingBottom: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
    marginBottom: Spacing.md,
  },
  quickStat: {
    alignItems: "center",
  },
  quickStatValue: {
    ...Typography.h3,
    color: Colors.dark.text,
    fontWeight: "700",
  },
  quickStatLabel: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  expandedActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.dark.successNeon + "15",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
  },
  actionButtonText: {
    ...Typography.caption,
    color: Colors.dark.successNeon,
    fontWeight: "600",
  },
  viewMoreButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginLeft: "auto",
  },
  viewMoreText: {
    ...Typography.caption,
    color: Colors.dark.primary,
  },
  packagesSummary: {
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    borderRadius: BorderRadius.sm,
    padding: Spacing.md,
  },
  packagesSummaryTitle: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    marginBottom: Spacing.sm,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  packageSummaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  packageSummaryName: {
    ...Typography.small,
    color: Colors.dark.text,
  },
  packageSummaryCredits: {
    ...Typography.small,
    fontWeight: "700",
  },
  inlineLoadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    padding: Spacing.lg,
  },
  inlineLoadingText: {
    ...Typography.small,
    color: Colors.dark.textMuted,
  },
  noDataText: {
    ...Typography.small,
    color: Colors.dark.textMuted,
    textAlign: "center",
    padding: Spacing.md,
  },
  inlineProfileScroll: {
    flex: 1,
  },
  inlineProfileContent: {
    padding: Spacing.lg,
  },
  inlineProfileHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.lg,
    paddingBottom: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  backButtonText: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "600",
  },
  deletePlayerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    padding: Spacing.md,
    marginTop: Spacing.lg,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.dark.error + "40",
  },
  deletePlayerText: {
    ...Typography.body,
    color: Colors.dark.error,
  },
  emptyState: {
    alignItems: "center",
    paddingTop: 100,
  },
  emptyText: {
    ...Typography.body,
    color: Colors.dark.textMuted,
    marginTop: Spacing.md,
  },
  emptySubtext: {
    ...Typography.small,
    color: Colors.dark.textMuted,
    marginTop: Spacing.xs,
  },
  errorText: {
    ...Typography.body,
    color: Colors.dark.error,
    marginTop: Spacing.md,
  },
  retryButton: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: Spacing.lg,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.dark.orange,
    borderRadius: BorderRadius.md,
  },
  retryButtonText: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "600",
  },
  modalContainer: {
    flex: 1,
    backgroundColor: Colors.dark.backgroundRoot,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
  },
  modalTitle: {
    ...Typography.h3,
    color: Colors.dark.text,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  cancelButton: {
    ...Typography.body,
    color: Colors.dark.textMuted,
  },
  saveButton: {
    ...Typography.body,
    color: Colors.dark.orange,
    fontWeight: "600",
  },
  disabledButton: {
    opacity: 0.5,
  },
  formScroll: {
    flex: 1,
  },
  form: {
    padding: Spacing.lg,
  },
  formGroup: {
    marginBottom: Spacing.lg,
  },
  label: {
    ...Typography.small,
    color: Colors.dark.textMuted,
    marginBottom: Spacing.sm,
  },
  input: {
    backgroundColor: Backgrounds.card,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    ...Typography.body,
    color: Colors.dark.text,
  },
  formDivider: {
    marginVertical: Spacing.lg,
    borderTopWidth: 1,
    borderTopColor: Colors.dark.border,
    paddingTop: Spacing.lg,
  },
  formDividerText: {
    ...Typography.sectionTitle,
    color: Colors.dark.textMuted,
  },
  ballLevelSelector: {
    flexDirection: "row",
    gap: Spacing.sm,
  },
  ballLevelOption: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 2,
    backgroundColor: Backgrounds.card,
    gap: Spacing.xs,
  },
  ballLevelSelected: {
    backgroundColor: Backgrounds.card,
  },
  ballLevelDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  ballLevelText: {
    ...Typography.small,
    fontWeight: "600",
  },
  detailScroll: {
    flex: 1,
  },
  detailContent: {
    padding: Spacing.lg,
  },
  profileSection: {
    alignItems: "center",
    marginBottom: Spacing.xl,
  },
  profileAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: Backgrounds.card,
    borderWidth: 3,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.md,
  },
  profileAvatarText: {
    ...Typography.h1,
    color: Colors.dark.text,
  },
  profileName: {
    ...Typography.h2,
    color: Colors.dark.text,
    marginBottom: Spacing.sm,
  },
  profileEmail: {
    ...Typography.small,
    color: Colors.dark.textMuted,
    marginTop: Spacing.xs,
  },
  levelDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  ballBadgeLarge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
    gap: Spacing.sm,
    backgroundColor: Backgrounds.card,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  ballDotLarge: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  ballTextLarge: {
    ...Typography.body,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  coachAssignment: {
    ...Typography.body,
    color: Colors.dark.textMuted,
    marginTop: Spacing.md,
  },
  section: {
    padding: Spacing.lg,
    marginBottom: Spacing.lg,
    backgroundColor: Backgrounds.card,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderRadius: BorderRadius.md,
  },
  sectionTitle: {
    ...Typography.sectionTitle,
    color: Colors.dark.textMuted,
    marginBottom: Spacing.md,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.md,
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    width: "45%",
  },
  statIcon: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  statValue: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "600",
  },
  statLabel: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
  },
  progressHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.lg,
    marginBottom: Spacing.lg,
  },
  levelBadge: {
    width: 60,
    height: 60,
    borderRadius: BorderRadius.md,
    backgroundColor: `${Colors.dark.gold}20`,
    alignItems: "center",
    justifyContent: "center",
  },
  levelNumber: {
    ...Typography.h2,
    color: Colors.dark.gold,
  },
  levelLabel: {
    ...Typography.caption,
    color: Colors.dark.gold,
  },
  xpInfo: {
    flex: 1,
  },
  xpText: {
    ...Typography.body,
    color: Colors.dark.text,
    marginBottom: Spacing.sm,
  },
  xpBar: {
    height: 8,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: 4,
    overflow: "hidden",
  },
  xpFill: {
    height: "100%",
    backgroundColor: Colors.dark.gold,
    borderRadius: 4,
  },
  skillsSection: {
    gap: Spacing.sm,
  },
  skillRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  skillLabel: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    width: 70,
  },
  skillBarContainer: {
    flex: 1,
    height: 6,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: 3,
    overflow: "hidden",
  },
  skillBarFill: {
    height: "100%",
    borderRadius: 3,
  },
  skillValue: {
    ...Typography.caption,
    color: Colors.dark.text,
    width: 30,
    textAlign: "right",
  },
  paymentSummary: {
    alignItems: "flex-start",
    marginBottom: Spacing.md,
  },
  paymentStatusBadge: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
    backgroundColor: Backgrounds.card,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  paymentStatusText: {
    ...Typography.caption,
    fontWeight: "700",
  },
  financeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: Spacing.sm,
  },
  financeLabel: {
    ...Typography.body,
    color: Colors.dark.textMuted,
  },
  financeValue: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "600",
  },
  paymentActions: {
    flexDirection: "row",
    gap: Spacing.sm,
    marginTop: Spacing.lg,
  },
  recordPaymentButton: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: Colors.dark.orange,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  recordPaymentText: {
    ...Typography.body,
    color: "#000",
    fontWeight: "700",
  },
  createInvoiceButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.xs,
    backgroundColor: Colors.dark.successNeon + "20",
    borderWidth: 1,
    borderColor: Colors.dark.successNeon + "40",
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
  },
  createInvoiceText: {
    ...Typography.body,
    color: Colors.dark.successNeon,
    fontWeight: "600",
  },
  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  contactText: {
    ...Typography.body,
    color: Colors.dark.text,
  },
  medicalSection: {
    borderLeftWidth: 3,
    borderLeftColor: Colors.dark.error,
  },
  medicalText: {
    ...Typography.body,
    color: Colors.dark.text,
    lineHeight: 22,
  },
  inviteDescription: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    marginBottom: Spacing.md,
  },
  inviteLinkButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: `${Colors.dark.orange}40`,
    padding: Spacing.md,
  },
  inviteLinkButtonCopied: {
    borderColor: `${Colors.dark.successNeon}40`,
  },
  inviteLinkContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  inviteLinkText: {
    ...Typography.body,
    color: Colors.dark.orange,
    fontWeight: "600",
  },
  inviteLinkTextCopied: {
    color: Colors.dark.successNeon,
  },
  inviteLoading: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    padding: Spacing.md,
  },
  inviteLoadingText: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
  },
  deleteButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.lg,
    marginTop: Spacing.lg,
  },
  deleteText: {
    ...Typography.body,
    color: Colors.dark.error,
  },
  deleteModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    padding: Spacing.lg,
  },
  deleteModalContent: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    width: "100%",
    maxWidth: 400,
    maxHeight: "80%",
    padding: Spacing.xl,
  },
  deleteModalHeader: {
    alignItems: "center",
    marginBottom: Spacing.lg,
  },
  deleteModalIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: `${Colors.dark.error}20`,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: Spacing.md,
  },
  deleteModalTitle: {
    ...Typography.h3,
    color: Colors.dark.text,
  },
  deleteModalSubtitle: {
    ...Typography.body,
    color: Colors.dark.textMuted,
    marginTop: Spacing.xs,
  },
  deleteOptionsLabel: {
    ...Typography.small,
    color: Colors.dark.textMuted,
    marginBottom: Spacing.md,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  deleteOptionsContainer: {
    maxHeight: 280,
  },
  deleteOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: Spacing.sm,
    gap: Spacing.md,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: BorderRadius.sm,
    borderWidth: 2,
    borderColor: Colors.dark.border,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxChecked: {
    backgroundColor: Colors.dark.error,
    borderColor: Colors.dark.error,
  },
  deleteOptionContent: {
    flex: 1,
  },
  deleteOptionLabel: {
    ...Typography.body,
    color: Colors.dark.text,
  },
  deleteOptionDesc: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  warningInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    padding: Spacing.md,
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: `${Colors.dark.warning}40`,
    marginTop: Spacing.lg,
    marginBottom: Spacing.lg,
  },
  warningText: {
    ...Typography.caption,
    color: Colors.dark.warning,
    flex: 1,
  },
  deleteModalActions: {
    flexDirection: "row",
    gap: Spacing.md,
  },
  cancelDeleteBtn: {
    flex: 1,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    alignItems: "center",
  },
  cancelDeleteBtnText: {
    ...Typography.body,
    color: Colors.dark.text,
  },
  confirmDeleteBtn: {
    flex: 1,
    flexDirection: "row",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.dark.error,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmDeleteBtnText: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "600",
  },
  btnDisabled: {
    opacity: 0.6,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.md,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  addCreditsButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: `${Colors.dark.primary}20`,
    alignItems: "center",
    justifyContent: "center",
  },
  addCreditsButtonPremium: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.primary,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
  },
  addCreditsButtonText: {
    ...Typography.caption,
    color: "#000",
    fontWeight: "700",
  },
  creditsOverview: {
    flexDirection: "row",
    gap: Spacing.md,
    marginBottom: Spacing.md,
  },
  creditStatCard: {
    flex: 1,
    backgroundColor: `${Colors.dark.primary}15`,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    alignItems: "center",
  },
  creditStatValue: {
    ...Typography.h2,
    color: Colors.dark.primary,
    fontWeight: "700",
  },
  creditStatLabel: {
    ...Typography.small,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  creditTypeRow: {
    flexDirection: "row",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  creditTypeCard: {
    flex: 1,
    borderRadius: BorderRadius.sm,
    padding: Spacing.sm,
    alignItems: "center",
  },
  creditTypeValue: {
    ...Typography.h3,
    fontWeight: "700",
  },
  creditTypeLabel: {
    ...Typography.small,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  grantCreditsButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: `${Colors.dark.primary}40`,
    backgroundColor: `${Colors.dark.primary}10`,
  },
  grantCreditsText: {
    ...Typography.body,
    color: Colors.dark.primary,
    fontWeight: "600",
  },
  sessionCount: {
    ...Typography.caption,
    color: Colors.dark.xpCyan,
    fontWeight: "600",
  },
  sessionsList: {
    gap: Spacing.sm,
  },
  sessionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.sm,
    padding: Spacing.sm,
  },
  sessionDateBlock: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  sessionIndicator: {
    width: 3,
    height: 32,
    borderRadius: 2,
  },
  sessionDate: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "500",
  },
  sessionTime: {
    ...Typography.small,
    color: Colors.dark.textMuted,
  },
  sessionBadges: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  sessionTypeBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
  },
  sessionTypeText: {
    ...Typography.small,
    color: Colors.dark.textMuted,
  },
  paymentBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
  },
  paymentDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  paymentBadgeText: {
    ...Typography.small,
    fontWeight: "600",
  },
  emptySessionsState: {
    alignItems: "center",
    paddingVertical: Spacing.xl,
    gap: Spacing.sm,
  },
  emptySessionsText: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
  },
  packageCardsList: {
    gap: Spacing.sm,
    marginTop: Spacing.md,
  },
  packageCard: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    padding: Spacing.md,
  },
  packageCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.sm,
  },
  packageTypeBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
  },
  packageTypeText: {
    ...Typography.caption,
    fontWeight: "600",
  },
  packageStatusBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
  },
  packageStatusText: {
    ...Typography.caption,
    fontWeight: "600",
  },
  packageCardBody: {
    alignItems: "center",
    marginBottom: Spacing.sm,
  },
  packageCreditsLabel: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    marginBottom: 2,
  },
  packageCreditsValue: {
    ...Typography.h2,
    fontWeight: "700",
  },
  packageCardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  packageExpiryText: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
  },
  packageHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  packagePaymentBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
  },
  packagePaymentText: {
    ...Typography.caption,
    fontWeight: "600",
  },
  packageCreditsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    width: "100%",
  },
  packagePriceBlock: {
    alignItems: "center",
  },
  packagePriceValue: {
    ...Typography.h3,
    fontWeight: "700",
  },
  markPaidButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.xs,
    paddingVertical: Spacing.sm,
    marginTop: Spacing.sm,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: `${Colors.dark.successNeon}40`,
    backgroundColor: `${Colors.dark.successNeon}10`,
  },
  markPaidText: {
    ...Typography.caption,
    color: Colors.dark.successNeon,
    fontWeight: "600",
  },
  packagesGrid: {
    gap: Spacing.md,
  },
  premiumPackageCard: {
    backgroundColor: Backgrounds.elevated,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: "rgba(200, 255, 61, 0.15)",
    padding: Spacing.lg,
    overflow: "hidden",
  },
  premiumPackageCardUnpaid: {
    borderColor: "rgba(255, 152, 0, 0.25)",
  },
  packageGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 60,
  },
  premiumPackageHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.md,
  },
  packageTypeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  packageIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  premiumPackageName: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  premiumUnpaidBadge: {
    backgroundColor: `${Colors.dark.orange}20`,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: `${Colors.dark.orange}30`,
  },
  premiumUnpaidText: {
    ...Typography.caption,
    color: Colors.dark.orange,
    fontWeight: "700",
    fontSize: 10,
    letterSpacing: 0.5,
  },
  premiumPaidBadge: {
    backgroundColor: `${Colors.dark.successNeon}20`,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: `${Colors.dark.successNeon}30`,
  },
  premiumPaidText: {
    ...Typography.caption,
    color: Colors.dark.successNeon,
    fontWeight: "700",
    fontSize: 10,
    letterSpacing: 0.5,
  },
  premiumCreditsSection: {
    marginBottom: Spacing.sm,
  },
  creditsDisplay: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 4,
    marginBottom: Spacing.sm,
  },
  premiumCreditsValue: {
    fontSize: 32,
    fontWeight: "800",
    letterSpacing: -1,
  },
  premiumCreditsDivider: {
    ...Typography.h3,
    color: Colors.dark.textMuted,
    fontWeight: "400",
  },
  premiumCreditsTotal: {
    ...Typography.h3,
    color: Colors.dark.textMuted,
    fontWeight: "600",
  },
  premiumCreditsLabel: {
    ...Typography.small,
    color: Colors.dark.textMuted,
    marginLeft: 4,
  },
  creditsProgressBar: {
    height: 4,
    backgroundColor: Backgrounds.elevated,
    borderRadius: 2,
    overflow: "hidden",
  },
  creditsProgressFill: {
    height: "100%",
    borderRadius: 2,
  },
  packageExpiryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: Spacing.sm,
  },
  premiumPackageExpiry: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
  },
  premiumMarkPaidButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    marginTop: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: `${Colors.dark.successNeon}40`,
    backgroundColor: `${Colors.dark.successNeon}15`,
  },
  premiumMarkPaidText: {
    ...Typography.small,
    color: Colors.dark.successNeon,
    fontWeight: "700",
  },
  emptyPackages: {
    alignItems: "center",
    paddingVertical: Spacing.xl,
    gap: Spacing.sm,
  },
  emptyPackagesText: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
  },
  premiumInviteHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  inviteIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: `${Colors.dark.xpCyan}20`,
    alignItems: "center",
    justifyContent: "center",
  },
  premiumSectionTitle: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "700",
  },
  inviteLoadingState: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
  },
  inviteLoadingStateText: {
    ...Typography.small,
    color: Colors.dark.textMuted,
  },
  premiumInviteContainer: {
    gap: Spacing.md,
  },
  inviteCodeBox: {
    backgroundColor: "rgba(0, 224, 255, 0.08)",
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: "rgba(0, 224, 255, 0.15)",
  },
  inviteCodeLabel: {
    ...Typography.caption,
    color: Colors.dark.xpCyan,
    fontWeight: "600",
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  premiumInviteCode: {
    ...Typography.h3,
    color: Colors.dark.text,
    fontWeight: "700",
    fontFamily: "monospace",
    letterSpacing: 1,
  },
  premiumCopyButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: `${Colors.dark.xpCyan}30`,
    overflow: "hidden",
  },
  premiumCopyButtonCopied: {
    borderColor: `${Colors.dark.successNeon}40`,
  },
  copyButtonGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  premiumCopyButtonText: {
    ...Typography.body,
    color: Colors.dark.xpCyan,
    fontWeight: "700",
  },
  premiumCopyButtonTextCopied: {
    color: Colors.dark.successNeon,
  },
  noInviteState: {
    alignItems: "center",
    paddingVertical: Spacing.lg,
    gap: Spacing.sm,
  },
  noInviteText: {
    ...Typography.small,
    color: Colors.dark.textMuted,
  },
  recordPaymentModalOverlay: {
    flex: 1,
    backgroundColor: Colors.dark.backgroundRoot,
    justifyContent: "flex-end",
  },
  recordPaymentModalContainer: {
    backgroundColor: Colors.dark.backgroundElevated,
    borderTopLeftRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
    maxHeight: "70%",
    paddingBottom: 34,
  },
  recordPaymentModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.border,
  },
  recordPaymentModalTitle: {
    ...Typography.h3,
    color: Colors.dark.text,
    fontWeight: "700",
  },
  recordPaymentModalClose: {
    padding: Spacing.xs,
  },
  recordPaymentModalContent: {
    padding: Spacing.lg,
  },
  noUnpaidContainer: {
    alignItems: "center",
    paddingVertical: Spacing.xl,
    gap: Spacing.md,
  },
  noUnpaidTitle: {
    ...Typography.h3,
    color: Colors.dark.successNeon,
    fontWeight: "700",
  },
  noUnpaidText: {
    ...Typography.body,
    color: Colors.dark.textMuted,
    textAlign: "center",
  },
  unpaidSectionTitle: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: Spacing.md,
  },
  unpaidPackageCard: {
    backgroundColor: Colors.dark.backgroundDefault,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    marginBottom: Spacing.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: `${Colors.dark.error}40`,
  },
  unpaidPackageInfo: {
    flex: 1,
    gap: 4,
  },
  unpaidPackageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  unpaidPackageType: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "600",
  },
  unpaidPackageCredits: {
    ...Typography.small,
    color: Colors.dark.textMuted,
  },
  unpaidPackagePrice: {
    ...Typography.body,
    color: Colors.dark.error,
    fontWeight: "700",
  },
  markPaidButtonFilled: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.dark.successNeon,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
  },
  markPaidButtonFilledText: {
    ...Typography.caption,
    color: "#000",
    fontWeight: "700",
  },
  recordPaymentModalDone: {
    backgroundColor: Colors.dark.primary,
    marginHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    alignItems: "center",
  },
  recordPaymentModalDoneText: {
    ...Typography.body,
    color: "#000",
    fontWeight: "700",
  },
  attendanceSectionPremium: {
    backgroundColor: Colors.dark.backgroundDefault,
    borderRadius: BorderRadius.xl,
    padding: 0,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: `${Colors.dark.xpCyan}20`,
  },
  attendanceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: Spacing.lg,
    backgroundColor: `${Colors.dark.xpCyan}08`,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.border,
  },
  attendanceHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
  },
  attendanceIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: `${Colors.dark.xpCyan}15`,
    alignItems: "center",
    justifyContent: "center",
  },
  attendanceTitle: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "700",
  },
  attendanceSubtitle: {
    ...Typography.small,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  downloadReportButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.dark.xpCyan,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
  },
  downloadReportText: {
    ...Typography.caption,
    color: "#000",
    fontWeight: "700",
  },
  attendanceList: {
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  attendanceCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.dark.backgroundElevated,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    gap: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.dark.border,
  },
  attendanceDateSection: {
    width: 50,
    alignItems: "center",
    paddingRight: Spacing.md,
    borderRightWidth: 1,
    borderRightColor: Colors.dark.border,
  },
  attendanceDay: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    textTransform: "uppercase",
    fontSize: 10,
  },
  attendanceDateNum: {
    ...Typography.h2,
    color: Colors.dark.text,
    fontWeight: "800",
    lineHeight: 28,
  },
  attendanceMonth: {
    ...Typography.caption,
    color: Colors.dark.xpCyan,
    textTransform: "uppercase",
    fontSize: 10,
  },
  attendanceDetails: {
    flex: 1,
    gap: 4,
  },
  attendanceTimeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  attendanceTimeText: {
    ...Typography.small,
    color: Colors.dark.textMuted,
  },
  sessionTypeChip: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
  },
  sessionTypeChipText: {
    ...Typography.caption,
    fontSize: 10,
    fontWeight: "600",
  },
  attendanceCreditsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  attendanceCreditsText: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
  },
  seriesNameText: {
    fontSize: 13,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  attendanceStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
  },
  attendanceStatusText: {
    ...Typography.caption,
    fontWeight: "700",
    fontSize: 11,
  },
  emptyAttendanceState: {
    alignItems: "center",
    paddingVertical: Spacing.xl * 2,
    gap: Spacing.md,
  },
  emptyAttendanceIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: `${Colors.dark.xpCyan}10`,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyAttendanceTitle: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "600",
  },
  emptyAttendanceText: {
    ...Typography.small,
    color: Colors.dark.textMuted,
  },
  seriesFilterContainer: {
    flexDirection: 'row',
    marginBottom: Spacing.md,
  },
  seriesFilterChip: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.lg,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    marginRight: Spacing.sm,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  seriesFilterChipActive: {
    backgroundColor: `${Colors.dark.xpCyan}20`,
    borderColor: Colors.dark.xpCyan,
  },
  seriesFilterChipText: {
    fontSize: 12,
    color: Colors.dark.textMuted,
  },
  seriesFilterChipTextActive: {
    color: Colors.dark.xpCyan,
  },
});
