import { StyleSheet, Platform } from "react-native";
import { Colors, Spacing, BorderRadius, Typography, Backgrounds, GlowColors } from "@/constants/theme";
import { TIME_COLUMN_WIDTH, HOUR_HEIGHT_60, HOUR_HEIGHT_30 } from "@/coach/components/calendar/calendarConstants";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  noCoachContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: Spacing.xl,
  },
  noCoachText: {
    ...Typography.h2,
    color: Colors.dark.text,
    marginTop: Spacing.lg,
  },
  noCoachSubtext: {
    ...Typography.body,
    color: Colors.dark.textMuted,
    marginTop: Spacing.sm,
    textAlign: "center",
  },
  header: {
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.md,
    backgroundColor: "rgba(12, 12, 15, 0.98)",
    borderTopWidth: 3,
    borderTopColor: Colors.dark.primary,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.primary + "30",
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  headerGlass: {
    position: "relative",
    paddingHorizontal: Spacing.md,
    paddingBottom: Spacing.xs,
    backgroundColor: "rgba(15, 15, 20, 0.92)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0, 212, 255, 0.2)",
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: "#00D4FF",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  headerTopLine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 3,
  },
  headerGradientOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 80,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 2,
    paddingTop: 4,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: Colors.dark.text,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  headerActions: {
    flexDirection: "row",
    gap: Spacing.sm,
  },
  toggleButton: {
    width: 30,
    height: 30,
    borderRadius: 6,
    backgroundColor: Colors.dark.primary + "15",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.dark.primary + "40",
  },
  undoButton: {
    borderWidth: 1,
    borderColor: Colors.dark.gold + "60",
    backgroundColor: Colors.dark.gold + "15",
  },
  toggleActive: {
    backgroundColor: Colors.dark.primary,
    borderColor: Colors.dark.primary,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 6,
      },
    }),
  },
  gridToggle: {
    paddingHorizontal: Spacing.sm,
    height: 30,
    borderRadius: 6,
    backgroundColor: Colors.dark.primary + "15",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.dark.primary + "40",
  },
  gridToggleText: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.dark.primary,
    letterSpacing: 0.5,
  },
  dateNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.md,
    gap: Spacing.xs,
  },
  dateNavButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: Colors.dark.primary + "15",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.dark.primary + "50",
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
      },
    }),
  },
  dateDisplay: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.lg,
    gap: Spacing.sm,
  },
  dateText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.dark.text,
    letterSpacing: 0.5,
  },
  todayBadge: {
    backgroundColor: Colors.dark.primary,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    borderRadius: 6,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 6,
      },
    }),
  },
  todayBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    color: Colors.dark.buttonText,
    letterSpacing: 1,
  },
  viewToggle: {
    flexDirection: "row",
    backgroundColor: "rgba(20, 20, 25, 0.95)",
    borderRadius: 10,
    padding: 3,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "30",
  },
  viewButton: {
    flex: 1,
    paddingVertical: Spacing.sm,
    alignItems: "center",
    borderRadius: 8,
  },
  viewButtonActive: {
    backgroundColor: Colors.dark.primary,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 6,
      },
    }),
  },
  viewButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.dark.textMuted,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  viewButtonTextActive: {
    color: Colors.dark.buttonText,
    fontWeight: "700",
  },
  viewToggleGaming: {
    flexDirection: "row",
    backgroundColor: "rgba(15, 15, 20, 0.85)",
    borderRadius: 14,
    padding: 4,
    borderWidth: 1,
    borderColor: "rgba(0, 212, 255, 0.25)",
    ...Platform.select({
      ios: {
        shadowColor: "#00D4FF",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  viewButtonGaming: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.xs,
    borderRadius: 8,
    overflow: "hidden",
    minWidth: 60,
  },
  viewButtonGamingActive: {
    ...Platform.select({
      ios: {
        shadowColor: "#00D4FF",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.7,
        shadowRadius: 10,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  viewButtonGamingGradient: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.xs,
    borderRadius: 8,
  },
  viewButtonTextGaming: {
    fontSize: 11,
    fontWeight: "700",
    color: "rgba(255, 255, 255, 0.6)",
    letterSpacing: 0.5,
  },
  viewButtonTextGamingActive: {
    fontSize: 11,
    fontWeight: "800",
    color: "#1A1A1A",
    letterSpacing: 1.5,
  },
  dateNavGaming: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 0,
    gap: Spacing.xs,
  },
  dateNavButtonGaming: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "rgba(0, 212, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(0, 212, 255, 0.35)",
    ...Platform.select({
      ios: {
        shadowColor: "#00D4FF",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  dateDisplayGaming: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    gap: Spacing.xs,
    backgroundColor: "rgba(15, 15, 20, 0.85)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(0, 212, 255, 0.2)",
  },
  dateDisplayCollapsed: {
    borderColor: "rgba(0, 212, 255, 0.5)",
    backgroundColor: "rgba(0, 212, 255, 0.08)",
  },
  collapseIndicator: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginLeft: 4,
  },
  collapseIndicatorExpanded: {
    backgroundColor: "rgba(0, 212, 255, 0.15)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  collapseHintText: {
    fontSize: 9,
    fontWeight: "700",
    color: "#00D4FF",
    letterSpacing: 0.5,
  },
  dateTextGaming: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.dark.text,
    letterSpacing: 0.8,
  },
  todayBadgeGaming: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#00D4FF",
    ...Platform.select({
      ios: {
        shadowColor: "#00D4FF",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.7,
        shadowRadius: 8,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  todayBadgeTextGaming: {
    fontSize: 9,
    fontWeight: "800",
    color: "#1A1A1A",
    letterSpacing: 1.2,
  },
  headerSecondRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  headerBookButton: {
    borderRadius: 20,
    overflow: "hidden",
  },
  headerBookButtonGradient: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
  },
  headerBookButtonText: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.dark.buttonText,
    letterSpacing: 0.5,
  },
  compactDateRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingBottom: 2,
  },
  togglesRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingBottom: 4,
  },
  dateDisplayCompact: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 160,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 6,
  },
  viewToggleCompact: {
    flexDirection: "row",
    backgroundColor: "rgba(15, 15, 20, 0.85)",
    borderRadius: 8,
    padding: 2,
    borderWidth: 1,
    borderColor: "rgba(0, 212, 255, 0.2)",
  },
  viewButtonCompact: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  viewButtonCompactActive: {
    backgroundColor: "#00D4FF",
  },
  viewButtonTextCompact: {
    fontSize: 11,
    fontWeight: "700",
    color: "rgba(255, 255, 255, 0.5)",
  },
  viewButtonTextCompactActive: {
    color: "#1A1A1A",
    fontWeight: "800",
  },
  filterDot: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.dark.gold,
  },
  filterOverlayBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-start",
    paddingTop: 120,
  },
  filterOverlayContent: {
    marginHorizontal: 16,
    backgroundColor: "rgba(20, 20, 28, 0.98)",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(0, 212, 255, 0.25)",
  },
  filterOverlayHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  filterOverlayTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: Colors.dark.text,
    letterSpacing: 1.5,
  },
  filterSectionLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.dark.textMuted,
    letterSpacing: 1,
    marginBottom: 8,
    marginTop: 12,
  },
  filterChipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  courtHeaders: {
    flexDirection: "row",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    backgroundColor: Backgrounds.card,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.04)",
  },
  timeColumnHeader: {
    width: TIME_COLUMN_WIDTH,
  },
  filterSection: {
    backgroundColor: Backgrounds.card,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
  },
  locationFilterContainer: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.gold + "15",
    maxHeight: 46,
  },
  locationFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: BorderRadius.xs,
    backgroundColor: Backgrounds.elevated,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  locationFilterChipActive: {
    backgroundColor: Colors.dark.gold + "20",
    borderColor: Colors.dark.gold,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.gold,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
      },
    }),
  },
  locationFilterText: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.dark.textSecondary,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  locationFilterTextActive: {
    color: Colors.dark.gold,
    fontWeight: "700",
  },
  courtFilterContainer: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    maxHeight: 46,
  },
  courtFilterContent: {
    gap: Spacing.sm,
    alignItems: "center",
  },
  courtFilterChip: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: BorderRadius.xs,
    backgroundColor: Backgrounds.elevated,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  courtFilterChipActive: {
    backgroundColor: GlowColors.primary + "15",
    borderColor: GlowColors.primary + "60",
    ...Platform.select({
      ios: {
        shadowColor: GlowColors.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
      },
    }),
  },
  courtFilterText: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.dark.textMuted,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  courtFilterTextActive: {
    color: GlowColors.primary,
    fontWeight: "700",
  },
  courtHeader: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    backgroundColor: Backgrounds.elevated,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  courtHeaderWithDivider: {
    borderLeftWidth: 1,
    borderLeftColor: "rgba(255,255,255,0.12)",
  },
  courtHeaderText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.3,
  },
  calendarScroll: {
    flex: 1,
    backgroundColor: Backgrounds.card,
  },
  calendarGrid: {
    flexDirection: "row",
    paddingHorizontal: Spacing.md,
    paddingBottom: 200,
  },
  timeColumn: {
    width: TIME_COLUMN_WIDTH,
    backgroundColor: Backgrounds.card,
    borderRightWidth: 1,
    borderRightColor: "rgba(255,255,255,0.08)",
  },
  timeSlot: {
    height: HOUR_HEIGHT_60,
    justifyContent: "flex-start",
    alignItems: "flex-end",
    paddingRight: 10,
    paddingTop: 2,
  },
  timeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.3,
  },
  courtLanesContainer: {
    flexDirection: "row",
    position: "relative",
    overflow: "visible",
  },
  courtLane: {
    position: "relative",
    backgroundColor: Backgrounds.elevated,
    overflow: "visible",
  },
  courtLaneWithDivider: {
    borderLeftWidth: 1,
    borderLeftColor: "rgba(255,255,255,0.10)",
  },
  hourSlot: {
    height: HOUR_HEIGHT_60,
    position: "relative",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
    overflow: "visible",
  },
  hourSlotEven: {
    backgroundColor: Backgrounds.elevated,
  },
  hourSlotOdd: {
    backgroundColor: Backgrounds.card,
  },
  hourLine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  halfHourLine: {
    position: "absolute",
    top: HOUR_HEIGHT_60 / 2,
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  sessionBlock: {
    position: "absolute",
    left: 4,
    right: 4,
    borderRadius: 6,
    overflow: "hidden",
    borderLeftWidth: 3,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  sessionBlockActive: {
    borderLeftWidth: 3,
    ...Platform.select({
      ios: {
        shadowColor: GlowColors.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  sessionGradient: {
    flex: 1,
    paddingHorizontal: 8,
    paddingVertical: 6,
    justifyContent: "center",
  },
  sessionText: {
    fontSize: 12,
    fontWeight: "900",
    color: "#000000",
    letterSpacing: 0.3,
  },
  sessionTime: {
    fontSize: 10,
    fontWeight: "700",
    color: "rgba(0, 0, 0, 0.9)",
    letterSpacing: 0.3,
  },
  blockedBlock: {
    position: "absolute",
    left: 2,
    right: 2,
    borderRadius: BorderRadius.xs,
    backgroundColor: "rgba(255, 68, 68, 0.12)",
    padding: Spacing.xs,
    borderWidth: 1,
    borderColor: "rgba(255, 68, 68, 0.3)",
    borderStyle: "dashed",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  blockedBlockOther: {
    position: "absolute",
    left: 2,
    right: 2,
    borderRadius: BorderRadius.xs,
    backgroundColor: "rgba(100, 100, 100, 0.3)",
    padding: Spacing.xs,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderStyle: "dashed",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  blockedText: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    fontStyle: "italic",
    textAlign: "center",
  },
  blockedTextCourt: {
    ...Typography.caption,
    color: "#FF4444",
    fontWeight: "700",
    letterSpacing: 1,
    textAlign: "center",
  },
  blockedReasonText: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    fontSize: 9,
    textAlign: "center",
    marginTop: 2,
  },
  hourSlotSelected: {
    backgroundColor: Colors.dark.primary + "25",
    borderColor: Colors.dark.primary + "60",
    borderWidth: 1,
    borderStyle: "dashed",
  },
  selectedCellOverlay: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.dark.primary + "40",
    justifyContent: "center",
    alignItems: "center",
  },
  selectionToolbar: {
    position: "absolute",
    left: 12,
    right: 12,
    paddingVertical: 16,
    paddingHorizontal: Spacing.lg,
    backgroundColor: "#1C2233",
    borderRadius: 16,
    borderWidth: 2,
    borderColor: Colors.dark.primary,
    elevation: 20,
    zIndex: 9999,
    boxShadow: "0px -4px 20px rgba(0, 212, 255, 0.3)",
  },
  selectionToolbarContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  selectionCancelBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,68,68,0.2)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,68,68,0.4)",
  },
  selectionCount: {
    ...Typography.body,
    color: "#FFF",
    fontWeight: "700",
    flex: 1,
    textAlign: "center",
  },
  selectionBlockBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FF4444",
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: BorderRadius.md,
  },
  selectionBlockBtnText: {
    ...Typography.body,
    color: "#FFF",
    fontWeight: "800",
    fontSize: 15,
    letterSpacing: 1,
  },
  blockModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    padding: Spacing.lg,
  },
  blockModalContent: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.lg,
    padding: Spacing.xl,
    width: "100%",
    maxWidth: 360,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "30",
  },
  blockModalTitle: {
    ...Typography.h3,
    color: Colors.dark.text,
    fontWeight: "800",
    letterSpacing: 2,
    textAlign: "center",
    marginBottom: 4,
  },
  blockModalSubtitle: {
    ...Typography.body,
    color: Colors.dark.textSecondary,
    textAlign: "center",
    marginBottom: Spacing.lg,
  },
  blockModalSummary: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: BorderRadius.sm,
    padding: Spacing.md,
    marginBottom: Spacing.lg,
    gap: 8,
  },
  blockModalSummaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  blockModalCourtName: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "600",
  },
  blockModalTimeRange: {
    ...Typography.body,
    color: Colors.dark.xpCyan,
    fontWeight: "500",
  },
  blockModalReasonLabel: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    fontWeight: "700",
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  blockReasonRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: Spacing.xl,
  },
  blockReasonPill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  blockReasonPillActive: {
    borderColor: Colors.dark.primary,
    backgroundColor: Colors.dark.primary + "20",
  },
  blockReasonPillText: {
    ...Typography.caption,
    color: Colors.dark.textSecondary,
    fontWeight: "500",
  },
  blockReasonPillTextActive: {
    color: Colors.dark.primary,
  },
  blockModalActions: {
    flexDirection: "row",
    gap: 12,
  },
  blockModalCancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  blockModalCancelText: {
    ...Typography.body,
    color: Colors.dark.textSecondary,
  },
  blockModalConfirmBtn: {
    flex: 1,
    flexDirection: "row",
    gap: 6,
    paddingVertical: 12,
    borderRadius: BorderRadius.md,
    backgroundColor: "#FF4444",
    justifyContent: "center",
    alignItems: "center",
  },
  blockModalConfirmText: {
    ...Typography.body,
    color: "#1A1A1A",
    fontWeight: "700",
  },
  dateRangeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  datePickerBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.06)",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  datePickerBtnText: {
    ...Typography.body,
    color: Colors.dark.textPrimary,
    fontSize: 13,
  },
  dateRangeArrow: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
  },
  inlineDatePicker: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: BorderRadius.sm,
    padding: 12,
    marginBottom: 8,
  },
  datePickerControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  datePickerCurrentDate: {
    ...Typography.body,
    color: Colors.dark.textPrimary,
    fontWeight: "600",
  },
  datePickerDone: {
    alignSelf: "flex-end",
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 6,
    backgroundColor: Colors.dark.primary + "30",
    borderRadius: BorderRadius.sm,
  },
  datePickerDoneText: {
    ...Typography.caption,
    color: Colors.dark.primary,
    fontWeight: "700",
  },
  weekdayRow: {
    flexDirection: "row",
    gap: 6,
    flexWrap: "wrap",
  },
  weekdayPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  weekdayPillActive: {
    backgroundColor: Colors.dark.primary + "25",
    borderColor: Colors.dark.primary,
  },
  weekdayPillText: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    fontWeight: "600",
  },
  weekdayPillTextActive: {
    color: Colors.dark.primary,
  },
  coachBlockStyle: {
    position: "absolute",
    left: 2,
    right: 2,
    borderRadius: BorderRadius.xs,
    backgroundColor: "rgba(255, 165, 0, 0.15)",
    padding: Spacing.xs,
    borderWidth: 1,
    borderColor: "rgba(255, 165, 0, 0.4)",
    borderStyle: "dashed",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  coachBlockText: {
    ...Typography.caption,
    color: "#FFA500",
    fontWeight: "700",
    letterSpacing: 0.5,
    textAlign: "center",
    fontSize: 9,
  },
  busyElsewhereBlock: {
    position: "absolute",
    left: 2,
    right: 2,
    borderRadius: BorderRadius.xs,
    backgroundColor: Colors.dark.gold + "15",
    paddingHorizontal: Spacing.xs,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: Colors.dark.gold + "40",
    borderStyle: "dashed",
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  busyElsewhereText: {
    fontSize: 9,
    fontWeight: "600",
    color: Colors.dark.gold,
    letterSpacing: 0.2,
  },
  travelTimeBlock: {
    position: "absolute",
    left: 2,
    borderRadius: BorderRadius.xs,
    backgroundColor: Colors.dark.gold + "25",
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderWidth: 1,
    borderColor: Colors.dark.gold + "50",
    borderStyle: "dashed",
    flexDirection: "row",
    alignItems: "center",
    zIndex: 5,
  },
  travelTimeBlockText: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.dark.gold,
    letterSpacing: 0.3,
    textAlign: "center",
  },
  nowLine: {
    position: "absolute",
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    zIndex: 100,
  },
  nowDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.dark.error,
    marginLeft: -5,
  },
  nowLineBar: {
    flex: 1,
    height: 2,
    backgroundColor: Colors.dark.error,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    ...Typography.body,
    color: Colors.dark.text,
  },
  refreshIndicator: {
    position: "absolute",
    top: 120,
    right: Spacing.lg,
    backgroundColor: Backgrounds.elevated + "E0",
    padding: Spacing.sm,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  coachList: {
    width: "100%",
    marginTop: Spacing.xl,
    gap: Spacing.md,
  },
  coachItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Backgrounds.card,
    padding: Spacing.lg,
    borderRadius: BorderRadius.md,
    gap: Spacing.md,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  coachInfo: {
    flex: 1,
  },
  coachName: {
    ...Typography.h4,
    color: Colors.dark.text,
  },
  coachEmail: {
    ...Typography.small,
    color: Colors.dark.textMuted,
  },
  weekCardsContainer: {
    padding: Spacing.md,
    gap: Spacing.sm,
  },
  dayCard: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  dayCardToday: {
    borderColor: GlowColors.primary + "40",
    shadowColor: GlowColors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
  },
  dayCardHeader: {
    width: 70,
    alignItems: "center",
  },
  dayCardDateInfo: {
    alignItems: "center",
    marginBottom: Spacing.xs,
  },
  dayCardDayName: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    fontWeight: "600",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  dayCardDayNameToday: {
    color: GlowColors.primary,
  },
  dayCardDate: {
    ...Typography.h3,
    color: Colors.dark.text,
  },
  energyIndicator: {
    width: 60,
    height: 6,
    borderRadius: 3,
    overflow: "hidden",
  },
  energyFill: {
    height: "100%",
    borderRadius: 3,
  },
  timeDistribution: {
    flex: 1,
    flexDirection: "row",
    height: 50,
    gap: Spacing.xs,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  timeZone: {
    alignItems: "center",
    width: 30,
    height: "100%",
    justifyContent: "flex-end",
  },
  timeBar: {
    width: 20,
    borderRadius: 4,
    minHeight: 4,
  },
  timeZoneLabel: {
    ...Typography.caption,
    fontSize: 9,
    color: Colors.dark.tabIconDefault,
    marginTop: 2,
  },
  dayCardStats: {
    flexDirection: "row",
    gap: Spacing.md,
  },
  dayCardStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  dayCardStatText: {
    ...Typography.caption,
    color: Colors.dark.tabIconDefault,
  },
  overviewDayBlock: {
    marginBottom: Spacing.md,
  },
  overviewDayHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.xs,
    gap: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  overviewDayHeaderToday: {
    borderBottomColor: GlowColors.primary + "40",
  },
  overviewDayName: {
    ...Typography.h4,
    color: Colors.dark.textMuted,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    width: 36,
  },
  overviewDayNameToday: {
    color: GlowColors.primary,
  },
  overviewDayDate: {
    ...Typography.body,
    color: Colors.dark.textSecondary,
    flex: 1,
  },
  overviewDayCount: {
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: BorderRadius.full,
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  overviewDayCountText: {
    ...Typography.caption,
    color: Colors.dark.text,
    fontWeight: "700",
  },
  overviewSessionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.xs,
    paddingLeft: Spacing.md,
    gap: Spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255, 255, 255, 0.04)",
  },
  overviewSessionRowPast: {
    opacity: 0.5,
  },
  overviewSessionAccent: {
    width: 3,
    height: 36,
    borderRadius: 2,
  },
  overviewSessionTime: {
    width: 90,
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  overviewTimeText: {
    ...Typography.caption,
    color: Colors.dark.textSecondary,
    fontWeight: "600",
    fontSize: 12,
  },
  overviewTimePast: {
    color: Colors.dark.tabIconDefault,
  },
  overviewTimeDash: {
    ...Typography.caption,
    color: Colors.dark.tabIconDefault,
    fontSize: 10,
  },
  overviewSessionInfo: {
    flex: 1,
    gap: 2,
  },
  overviewSessionTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  overviewTypeLabel: {
    ...Typography.body,
    fontWeight: "700",
    fontSize: 13,
  },
  overviewLiveBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FF3B3020",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: BorderRadius.full,
  },
  overviewLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#FF3B30",
  },
  overviewLiveText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#FF3B30",
    letterSpacing: 0.5,
  },
  overviewSessionDetails: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    flexWrap: "wrap",
  },
  overviewPlayerText: {
    ...Typography.caption,
    color: Colors.dark.text,
    fontSize: 12,
  },
  overviewCourtChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  overviewCourtText: {
    ...Typography.caption,
    color: Colors.dark.tabIconDefault,
    fontSize: 11,
  },
  overviewEmpty: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    gap: Spacing.md,
  },
  overviewEmptyText: {
    ...Typography.body,
    color: Colors.dark.tabIconDefault,
  },
  weekPlannerHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
    backgroundColor: Backgrounds.card,
  },
  weekPlannerHeaderCell: {
    flex: 1,
    alignItems: "center",
    paddingVertical: Spacing.sm,
    gap: 4,
  },
  weekPlannerHeaderCellToday: {
    backgroundColor: GlowColors.primary + "10",
  },
  weekPlannerDayLetter: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.dark.tabIconDefault,
    letterSpacing: 0.5,
  },
  weekPlannerDayLetterToday: {
    color: GlowColors.primary,
  },
  weekPlannerDateCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  weekPlannerDateCircleToday: {
    backgroundColor: GlowColors.primary,
  },
  weekPlannerDateNum: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  weekPlannerDateNumToday: {
    color: Colors.dark.buttonText,
  },
  weekPlannerSessionCount: {
    fontSize: 10,
    fontWeight: "700",
    color: GlowColors.primary,
  },
  weekPlannerSessionCountEmpty: {
    fontSize: 10,
    color: Colors.dark.tabIconDefault,
  },
  weekPlannerDay: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
  },
  weekPlannerDayLabel: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    backgroundColor: Backgrounds.card + "80",
  },
  weekPlannerDayLabelToday: {
    backgroundColor: GlowColors.primary + "12",
  },
  weekPlannerDayText: {
    ...Typography.body,
    fontWeight: "700",
    color: Colors.dark.textSecondary,
    fontSize: 13,
  },
  weekPlannerDayTextToday: {
    color: GlowColors.primary,
  },
  weekPlannerDayDateText: {
    ...Typography.caption,
    color: Colors.dark.tabIconDefault,
    fontSize: 11,
  },
  weekPlannerNoSessions: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  weekPlannerNoSessionsText: {
    ...Typography.caption,
    color: Colors.dark.tabIconDefault,
    fontStyle: "italic",
    fontSize: 12,
  },
  weekPlannerSessions: {
    gap: 1,
  },
  weekPlannerSession: {
    flexDirection: "row",
    alignItems: "stretch",
    paddingVertical: 6,
    paddingHorizontal: Spacing.md,
    paddingLeft: Spacing.lg,
  },
  weekPlannerSessionPast: {
    opacity: 0.45,
  },
  weekPlannerSessionBar: {
    width: 3,
    borderRadius: 2,
    marginRight: Spacing.sm,
  },
  weekPlannerSessionContent: {
    flex: 1,
    gap: 1,
  },
  weekPlannerSessionRow1: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  weekPlannerTimeText: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.dark.textSecondary,
  },
  weekPlannerTypeBadge: {
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: BorderRadius.sm,
  },
  weekPlannerTypeText: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  weekPlannerPlayerText: {
    fontSize: 12,
    color: Colors.dark.text,
  },
  weekPlannerCourtText: {
    fontSize: 11,
    color: Colors.dark.tabIconDefault,
  },
  weekCalHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.15)",
    backgroundColor: Backgrounds.card,
  },
  weekCalTimeCol: {
    width: 50,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.sm,
  },
  weekCalTimeLabel: {
    fontSize: 9,
    fontWeight: "700",
    color: Colors.dark.tabIconDefault,
    letterSpacing: 0.5,
  },
  weekCalDayCol: {
    flex: 1,
    alignItems: "center",
    paddingVertical: Spacing.sm,
    gap: 2,
  },
  weekCalDayColToday: {
    backgroundColor: GlowColors.primary + "12",
  },
  weekCalDayLabel: {
    fontSize: 9,
    fontWeight: "700",
    color: Colors.dark.tabIconDefault,
    letterSpacing: 0.5,
  },
  weekCalDayLabelToday: {
    color: GlowColors.primary,
  },
  weekCalDateLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  weekCalDateLabelToday: {
    color: GlowColors.primary,
  },
  weekCalRow: {
    flexDirection: "row",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
    minHeight: 56,
  },
  weekCalTimeText: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.dark.tabIconDefault,
  },
  weekCalCell: {
    flex: 1,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: "rgba(255, 255, 255, 0.06)",
    padding: 2,
    gap: 2,
  },
  weekCalCellToday: {
    backgroundColor: GlowColors.primary + "06",
  },
  weekCalSessionBlock: {
    borderRadius: 4,
    borderLeftWidth: 3,
    padding: 4,
    minHeight: 40,
  },
  weekCalSessionPast: {
    opacity: 0.4,
  },
  weekCalSessionActive: {
    borderWidth: 1,
    borderColor: GlowColors.primary + "60",
  },
  weekCalSessionType: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  weekCalSessionPlayer: {
    fontSize: 10,
    color: Colors.dark.text,
    marginTop: 1,
  },
  weekCalLiveDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#FF3B30",
    position: "absolute",
    top: 3,
    right: 3,
  },
  monthDayHeaders: {
    flexDirection: "row",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    backgroundColor: Backgrounds.card,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.06)",
  },
  monthDayHeaderText: {
    flex: 1,
    fontSize: 10,
    color: Colors.dark.textMuted,
    textAlign: "center",
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  monthWeekRow: {
    flexDirection: "row",
    paddingHorizontal: Spacing.lg,
  },
  monthWeekHeavy: {
    backgroundColor: Colors.dark.error + "08",
  },
  monthWeekBusy: {
    backgroundColor: Colors.dark.gold + "08",
  },
  monthDay: {
    flex: 1,
    alignItems: "center",
    paddingVertical: Spacing.sm,
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    minHeight: 80,
    justifyContent: "space-between",
  },
  monthDayEmpty: {
    flex: 1,
    backgroundColor: Backgrounds.elevated,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.03)",
    minHeight: 80,
  },
  monthDayToday: {
    backgroundColor: GlowColors.primary + "12",
  },
  monthDayWeekend: {
    backgroundColor: Backgrounds.elevated,
  },
  monthDaySelected: {
    borderColor: GlowColors.primary,
    borderWidth: 1,
  },
  monthDayNumber: {
    ...Typography.caption,
    color: Colors.dark.text,
    fontWeight: "500",
    alignSelf: "flex-start",
  },
  monthDayNumberWeekend: {
    color: Colors.dark.textMuted,
  },
  monthDayNumberToday: {
    color: GlowColors.primary,
    fontWeight: "700",
  },
  monthLoadContainer: {
    flex: 1,
    width: 8,
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: 4,
    justifyContent: "flex-end",
    overflow: "hidden",
    marginVertical: 4,
  },
  monthLoadBar: {
    width: "100%",
    borderRadius: 4,
  },
  monthHoursText: {
    ...Typography.caption,
    fontSize: 9,
    color: Colors.dark.tabIconDefault,
    fontWeight: "600",
  },
  // Premium Month View styles (Glassmorphism)
  monthModeToggle: {
    flexDirection: "row",
    backgroundColor: Backgrounds.elevated,
    borderRadius: BorderRadius.md,
    padding: 3,
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  monthModeButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.04)",
  },
  monthModeButtonActive: {
    backgroundColor: GlowColors.primary,
    borderColor: GlowColors.primary,
    ...Platform.select({
      ios: {
        shadowColor: GlowColors.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  monthModeText: {
    fontSize: 11,
    color: Colors.dark.textMuted,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  monthModeTextActive: {
    color: "rgba(255, 255, 255, 0.06)",
    fontWeight: "800",
  },
  monthWeekRowPremium: {
    flexDirection: "row",
    paddingHorizontal: Spacing.md,
    gap: 6,
    marginBottom: 6,
  },
  monthDayCard: {
    flex: 1,
    borderRadius: BorderRadius.md,
    backgroundColor: Backgrounds.card,
    minHeight: 70,
    padding: 6,
    overflow: "hidden",
    position: "relative",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  monthDayCardEmpty: {
    flex: 1,
    borderRadius: BorderRadius.md,
    backgroundColor: Backgrounds.card,
    minHeight: 70,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.03)",
    opacity: 0.6,
  },
  monthDayCardWeekend: {
    backgroundColor: Backgrounds.elevated,
    borderColor: "rgba(255, 255, 255, 0.04)",
  },
  monthDayCardToday: {
    borderWidth: 1,
    borderColor: GlowColors.primary + "60",
    ...Platform.select({
      ios: {
        shadowColor: GlowColors.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  monthDayCardSelected: {
    borderWidth: 2,
    borderColor: Colors.dark.xpCyan,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.xpCyan,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  monthDayCardNumber: {
    fontSize: 12,
    color: "rgba(255, 255, 255, 0.7)",
    fontWeight: "700",
    letterSpacing: 0.5,
    zIndex: 2,
  },
  monthDayCardNumberWeekend: {
    color: "rgba(255, 255, 255, 0.4)",
  },
  monthDayCardNumberToday: {
    color: GlowColors.primary,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  monthLoadFillContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    borderBottomLeftRadius: BorderRadius.md,
    borderBottomRightRadius: BorderRadius.md,
    overflow: "hidden",
  },
  monthLoadFill: {
    flex: 1,
    opacity: 0.7,
  },
  monthHoursLabel: {
    position: "absolute",
    bottom: 4,
    right: 6,
    ...Typography.caption,
    fontSize: 10,
    color: GlowColors.primary,
    fontWeight: "700",
    letterSpacing: 0.5,
    zIndex: 2,
    textShadowColor: GlowColors.primary,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  monthAvailabilityIndicator: {
    position: "absolute",
    top: "50%",
    left: "50%",
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: -6,
    marginLeft: -6,
    borderWidth: 1,
    borderColor: "transparent",
  },
  monthAvailabilityOpen: {
    backgroundColor: GlowColors.primary,
    borderColor: GlowColors.primary,
    ...Platform.select({
      ios: {
        shadowColor: GlowColors.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 6,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  monthAvailabilityLimited: {
    backgroundColor: Colors.dark.gold,
    borderColor: Colors.dark.gold,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.gold,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 4,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  monthAvailabilityFull: {
    backgroundColor: Colors.dark.disabled,
    borderColor: Colors.dark.backgroundTertiary,
  },
  monthSlotsLabel: {
    position: "absolute",
    bottom: 4,
    right: 6,
    ...Typography.caption,
    fontSize: 10,
    color: Colors.dark.xpCyan,
    fontWeight: "700",
    letterSpacing: 0.5,
    textShadowColor: Colors.dark.xpCyan,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
  },
  // Week mode toggle styles
  weekModeToggle: {
    flexDirection: "row",
    backgroundColor: Backgrounds.elevated,
    borderRadius: BorderRadius.xs,
    padding: 2,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  weekModeButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
    borderRadius: BorderRadius.xs - 2,
    gap: 4,
  },
  weekModeButtonActive: {
    backgroundColor: GlowColors.primary,
  },
  weekModeText: {
    fontSize: 10,
    fontWeight: "600",
    color: Colors.dark.textMuted,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  weekModeTextActive: {
    color: "rgba(255, 255, 255, 0.06)",
    fontWeight: "700",
  },
  // Week Grid Styles (Premium Glassmorphism)
  weekGridHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
    backgroundColor: Backgrounds.card,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.06)",
  },
  weekTimeColumnHeader: {
    width: TIME_COLUMN_WIDTH,
    paddingVertical: Spacing.sm,
    alignItems: "center",
    justifyContent: "center",
    borderRightWidth: 1,
    borderRightColor: "rgba(255, 255, 255, 0.08)",
  },
  weekTimeHeaderText: {
    fontSize: 9,
    fontWeight: "700",
    color: Colors.dark.textMuted,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  weekDayHeader: {
    flex: 1,
    alignItems: "center",
    paddingVertical: Spacing.sm,
    borderLeftWidth: 1,
    borderLeftColor: "rgba(255, 255, 255, 0.06)",
  },
  weekDayHeaderToday: {
    backgroundColor: GlowColors.primary + "10",
    borderBottomWidth: 2,
    borderBottomColor: GlowColors.primary,
    ...Platform.select({
      ios: {
        shadowColor: GlowColors.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
      },
    }),
  },
  weekDayName: {
    fontSize: 9,
    fontWeight: "700",
    color: Colors.dark.textMuted,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  weekDayNameToday: {
    color: GlowColors.primary,
  },
  weekDayNumber: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.dark.text,
    marginTop: 2,
  },
  weekDayNumberToday: {
    color: GlowColors.primary,
  },
  weekGridScroll: {
    flex: 1,
    backgroundColor: Backgrounds.card,
  },
  weekGridBody: {
    flexDirection: "row",
  },
  weekTimeColumn: {
    width: TIME_COLUMN_WIDTH,
    backgroundColor: Backgrounds.card,
    borderRightWidth: 1,
    borderRightColor: "rgba(255, 255, 255, 0.08)",
  },
  weekTimeSlot: {
    justifyContent: "flex-start",
    paddingTop: 4,
    alignItems: "center",
  },
  weekTimeText: {
    fontSize: 9,
    fontWeight: "600",
    color: "#FFFFFF",
    letterSpacing: 0.3,
  },
  weekDayColumns: {
    flexDirection: "row",
    flex: 1,
  },
  weekDayColumn: {
    flex: 1,
    position: "relative",
    borderLeftWidth: 1,
    borderLeftColor: "rgba(255, 255, 255, 0.35)",
  },
  weekDayColumnToday: {
    backgroundColor: GlowColors.primary + "15",
  },
  weekHourSlot: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.25)",
  },
  weekHourLine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.5)",
  },
  weekHalfHourLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.25)",
  },
  weekSessionBlock: {
    position: "absolute",
    left: 2,
    right: 2,
    borderRadius: BorderRadius.xs,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  weekSessionBlockActive: {
    borderWidth: 1,
    borderColor: GlowColors.primary + "80",
    ...Platform.select({
      ios: {
        shadowColor: GlowColors.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 10,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  weekSessionGradient: {
    flex: 1,
    padding: 4,
    justifyContent: "center",
  },
  weekSessionText: {
    fontSize: 8,
    fontWeight: "900",
    color: "#000000",
    letterSpacing: 0.3,
    textTransform: "uppercase",
    textAlign: "center",
  },
  weekSessionTime: {
    fontSize: 7,
    fontWeight: "600",
    color: "rgba(0, 0, 0, 0.85)",
    letterSpacing: 0,
    textAlign: "center",
    marginTop: 1,
  },
  weekNowLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: Colors.dark.error,
    zIndex: 10,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.error,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 6,
      },
    }),
  },
  weekBlockedBlock: {
    position: "absolute",
    left: 2,
    right: 2,
    borderRadius: BorderRadius.sm,
    backgroundColor: "rgba(100, 100, 100, 0.4)",
    borderWidth: 1,
    borderColor: "rgba(100, 100, 100, 0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  weekBlockedText: {
    ...Typography.caption,
    fontSize: 8,
    color: Colors.dark.textMuted,
    fontWeight: "500",
  },
  // Availability mode styles - Energy Bands (Premium Glassmorphism)
  availabilityContainer: {
    flex: 1,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
  },
  energyBandsContainer: {
    flexDirection: "row",
    flex: 1,
    gap: Spacing.sm,
  },
  energyBandColumn: {
    flex: 1,
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.md,
    overflow: "hidden",
    minHeight: 280,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  energyBandToday: {
    borderColor: GlowColors.primary + "40",
    shadowColor: GlowColors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  energyBandSelected: {
    borderColor: GlowColors.primary + "60",
    shadowColor: GlowColors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 6,
  },
  energyBandHeader: {
    alignItems: "center",
    paddingVertical: Spacing.sm,
    paddingTop: Spacing.md,
  },
  energyBandDayName: {
    ...Typography.caption,
    fontSize: 11,
    color: Colors.dark.textMuted,
    fontWeight: "600",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  energyBandDayNameToday: {
    color: GlowColors.primary,
  },
  energyBandDate: {
    ...Typography.body,
    fontSize: 18,
    color: Colors.dark.text,
    fontWeight: "700",
    marginTop: 2,
  },
  energyBandDateToday: {
    color: GlowColors.primary,
  },
  energyBarContainer: {
    flex: 1,
    justifyContent: "flex-end",
    marginHorizontal: Spacing.xs,
    marginBottom: Spacing.xs,
    borderRadius: BorderRadius.sm,
    overflow: "hidden",
    backgroundColor: "rgba(20, 20, 25, 0.3)",
  },
  energyBarFill: {
    width: "100%",
    borderRadius: BorderRadius.sm,
  },
  energyBarGlow: {
    position: "absolute",
    left: "20%",
    right: "20%",
    height: 3,
    borderRadius: 2,
    opacity: 0.6,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 4,
  },
  energyBandFooter: {
    alignItems: "center",
    paddingVertical: Spacing.sm,
    paddingBottom: Spacing.md,
  },
  energyBandHours: {
    ...Typography.caption,
    fontSize: 12,
    fontWeight: "700",
  },
  energyTimeHint: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.md,
    opacity: 0.4,
  },
  energyTimeHintText: {
    ...Typography.caption,
    fontSize: 10,
    color: Colors.dark.textMuted,
  },
  energyTimeHintLine: {
    flex: 1,
    height: 1,
    backgroundColor: Colors.dark.disabled,
    marginHorizontal: Spacing.md,
    opacity: 0.3,
  },
  // Day Context Panel styles (Premium Glassmorphism)
  dayContextPanel: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    marginHorizontal: Spacing.md,
    marginTop: Spacing.sm,
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  dayContextHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
    paddingBottom: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
  },
  dayContextDate: {
    fontSize: 14,
    color: Colors.dark.text,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  dayContextTodayBadge: {
    fontSize: 9,
    color: "rgba(255, 255, 255, 0.06)",
    backgroundColor: GlowColors.primary,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    borderRadius: BorderRadius.xs,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  dayContextContent: {
    gap: Spacing.xs,
  },
  dayContextRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  dayContextLabel: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "500",
  },
  dayContextDot: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
  },
  dayContextMeta: {
    ...Typography.caption,
    color: Colors.dark.tabIconDefault,
  },
  peakPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    backgroundColor: Colors.dark.xpCyan + "15",
    borderRadius: BorderRadius.xs,
  },
  peakPillText: {
    ...Typography.caption,
    fontSize: 10,
    color: Colors.dark.xpCyan,
    fontWeight: "500",
  },
  dayContextLoadBar: {
    height: 4,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 2,
    marginTop: Spacing.xs,
    overflow: "hidden",
  },
  dayContextLoadFill: {
    height: "100%",
    borderRadius: 2,
  },
  dayContextAvailLabel: {
    ...Typography.caption,
    color: Colors.dark.tabIconDefault,
    marginBottom: Spacing.xs,
  },
  dayContextSlot: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    backgroundColor: GlowColors.primary + "10",
    borderRadius: BorderRadius.xs,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: GlowColors.primary + "15",
  },
  dayContextSlotTime: {
    ...Typography.caption,
    color: GlowColors.primary,
    fontWeight: "600",
  },
  dayContextSlotCourt: {
    ...Typography.caption,
    fontSize: 11,
    color: Colors.dark.tabIconDefault,
  },
  dayContextMoreSlots: {
    ...Typography.caption,
    color: Colors.dark.tabIconDefault,
    fontStyle: "italic",
    marginTop: Spacing.xs,
  },
  dayContextNoSlots: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    fontStyle: "italic",
  },
  dayContextAction: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    marginTop: Spacing.md,
    paddingVertical: Spacing.sm,
    backgroundColor: GlowColors.primary + "15",
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: GlowColors.primary + "40",
    ...Platform.select({
      ios: {
        shadowColor: GlowColors.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  dayContextActionText: {
    fontSize: 12,
    color: GlowColors.primary,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  dayContextActionDisabled: {
    backgroundColor: Colors.dark.backgroundTertiary,
    borderColor: Colors.dark.disabled,
  },
  dayContextActionTextDisabled: {
    color: Colors.dark.textMuted,
  },
});

export const dragModalStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    width: "90%",
    maxWidth: 360,
  },
  card: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.xl,
    padding: Spacing.xl,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
      },
      android: {
        elevation: 20,
      },
    }),
  },
  header: {
    alignItems: "center",
    marginBottom: Spacing.lg,
  },
  iconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: GlowColors.primary + "20",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: Spacing.sm,
  },
  title: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.3,
  },
  warningBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FF6B35" + "20",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
    marginTop: Spacing.xs,
  },
  warningText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#FF6B35",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  sessionInfo: {
    alignItems: "center",
    marginBottom: Spacing.lg,
  },
  sessionName: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.dark.textSecondary,
  },
  changesContainer: {
    backgroundColor: Backgrounds.elevated,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    gap: Spacing.md,
    marginBottom: Spacing.lg,
  },
  changeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  changeContent: {
    flex: 1,
  },
  changeLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.dark.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  changeValues: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  oldValue: {
    fontSize: 14,
    fontWeight: "500",
    color: Colors.dark.textSecondary,
  },
  newValue: {
    fontSize: 14,
    fontWeight: "700",
    color: GlowColors.primary,
  },
  actions: {
    flexDirection: "row",
    gap: Spacing.sm,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    backgroundColor: Backgrounds.elevated,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.dark.textSecondary,
  },
  confirmButton: {
    flex: 1.5,
    borderRadius: BorderRadius.md,
    overflow: "hidden",
  },
  confirmGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.xs,
    paddingVertical: Spacing.md,
  },
  confirmButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.dark.buttonText,
  },
});
