import { StyleSheet, Platform } from "react-native";
import { Colors, Spacing, BorderRadius, GlowColors, Backgrounds, Typography, FontSizes } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.dark.backgroundRoot,
  },

  // === GAMING AESTHETIC STYLES ===
  gamingHeader: {
    paddingBottom: Spacing.md,
  },
  gamingHeaderTopLine: {
    height: 3,
    width: "100%",
  },
  gamingHeaderContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.lg,
  },
  gamingHeaderLeft: {
    gap: Spacing.sm,
  },
  gamingTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: Colors.dark.text,
    letterSpacing: 3,
    textTransform: "uppercase",
  },
  gamingCountBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    backgroundColor: GlowColors.primary + "15",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: GlowColors.primary + "40",
    position: "relative",
    overflow: "hidden",
  },
  gamingCountGlow: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Colors.dark.xpCyan + "10",
  },
  gamingCountText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.dark.xpCyan,
  },
  gamingCountLabel: {
    fontSize: 10,
    fontWeight: "600",
    color: Colors.dark.xpCyan + "80",
    letterSpacing: 1,
  },
  gamingSearchContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: Spacing.lg,
    marginBottom: Spacing.md,
    gap: Spacing.sm,
  },
  gamingSearchBar: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    height: 48,
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.xpCyan,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
      },
      android: { elevation: 2 },
    }),
  },
  gamingSearchInput: {
    flex: 1,
    fontSize: 14,
    color: Colors.dark.text,
    letterSpacing: 0.5,
  },
  searchIconBg: {
    width: 32,
    height: 32,
    borderRadius: BorderRadius.sm,
    backgroundColor: GlowColors.primary + "15",
    alignItems: "center",
    justifyContent: "center",
  },
  sortButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    height: 48,
    gap: 4,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  sortModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "center",
    alignItems: "center",
    padding: Spacing.xl,
  },
  sortModalContent: {
    backgroundColor: Backgrounds.elevated,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    width: "100%",
    maxWidth: 320,
    overflow: "hidden",
  },
  sortModalTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.dark.text,
    textAlign: "center",
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.border,
  },
  sortOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    gap: Spacing.md,
  },
  sortOptionActive: {
    backgroundColor: Colors.dark.xpCyan + "15",
  },
  sortOptionText: {
    fontSize: 15,
    color: Colors.dark.tabIconDefault,
  },
  sortOptionTextActive: {
    color: Colors.dark.text,
    fontWeight: "600",
  },
  statusFilterRow: {
    flexDirection: "row",
    paddingHorizontal: Spacing.lg,
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  statusFilterPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(255,255,255,0.06)",
    flex: 1,
    justifyContent: "center",
  },
  statusFilterText: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.dark.tabIconDefault,
  },
  statusFilterCount: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 1,
    minWidth: 18,
    alignItems: "center",
  },
  statusFilterCountText: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.dark.tabIconDefault,
  },
  rosterFilterBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.dark.primary + "18",
    borderWidth: 1,
    borderColor: Colors.dark.primary + "40",
  },
  rosterFilterBannerText: {
    flex: 1,
    fontSize: 13,
    color: Colors.dark.primary,
    fontWeight: "500",
  },
  gamingFilterScroll: {
    marginBottom: Spacing.md,
    maxHeight: 36,
  },
  gamingFilterContent: {
    paddingHorizontal: Spacing.lg,
    gap: 4,
    alignItems: "flex-start",
  },
  gamingFilterPill: {
    flexDirection: "row",
    alignItems: "center",
    height: 28,
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.sm,
    gap: Spacing.xs,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    overflow: "hidden",
  },
  gamingFilterPillActive: {
    borderWidth: 0,
  },
  gamingFilterText: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.dark.tabIconDefault,
    letterSpacing: 0.5,
  },
  gamingFilterTextActive: {
    color: Colors.dark.buttonText,
  },
  gamingLevelDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  gamingFilterCount: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
    minWidth: 16,
    alignItems: "center",
  },
  gamingFilterCountActive: {
    backgroundColor: "rgba(0, 0, 0, 0.25)",
  },
  gamingFilterCountText: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.dark.tabIconDefault,
  },
  gamingFilterCountTextActive: {
    color: Colors.dark.buttonText,
  },
  subLevelFilterRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.md,
    gap: Spacing.sm,
    flexWrap: "wrap",
  },
  subLevelLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.dark.textMuted,
    marginRight: Spacing.xs,
  },
  subLevelPill: {
    flexDirection: "row",
    alignItems: "center",
    height: 32,
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.sm,
    gap: Spacing.xs,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  subLevelPillText: {
    fontSize: 10,
    fontWeight: "600",
    color: Colors.dark.tabIconDefault,
    letterSpacing: 0.5,
  },
  subLevelCount: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 3,
    minWidth: 18,
    alignItems: "center",
  },
  subLevelCountText: {
    fontSize: 9,
    fontWeight: "700",
    color: Colors.dark.tabIconDefault,
  },
  gamingCardContainer: {
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.sm,
    borderRadius: BorderRadius.lg,
    overflow: "hidden",
  },
  gamingCardBorder: {
    padding: 2,
    borderRadius: BorderRadius.lg,
  },
  gamingCardInner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.lg - 2,
    padding: Spacing.md,
    gap: Spacing.md,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  gamingAvatarContainer: {
    width: 54,
    height: 54,
    alignItems: "center",
    justifyContent: "center",
  },
  gamingAvatarGlow: {
    position: "absolute",
    width: 54,
    height: 54,
    borderRadius: 27,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 10,
      },
      android: {},
    }),
  },
  gamingAvatarRing: {
    position: "absolute",
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 6,
      },
      android: {},
    }),
  },
  gamingAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
  },
  gamingAvatarPhoto: {
    width: 42,
    height: 42,
    borderRadius: 21,
  },
  gamingAvatarText: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.dark.buttonText,
  },
  gamingCardInfo: {
    flex: 1,
    gap: 6,
  },
  gamingCardNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  gamingCardName: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.dark.text,
    flex: 1,
    letterSpacing: 0.3,
  },
  gamingStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 1,
  },
  gamingStatusBadgeText: {
    fontSize: 9,
    fontWeight: "600",
  },
  auditVerifiedBadge: {
    marginLeft: 2,
  },
  baselineNeededBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 5,
    paddingVertical: 2,
    backgroundColor: Colors.dark.orange + "20",
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.dark.orange + "40",
  },
  baselineNeededText: {
    fontSize: 8,
    fontWeight: "500",
    color: Colors.dark.orange,
  },
  gamingXpContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  gamingXpBarBg: {
    flex: 1,
    height: 4,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 2,
    overflow: "hidden",
  },
  gamingXpBarFill: {
    height: "100%",
    borderRadius: 2,
  },
  gamingXpText: {
    fontSize: 10,
    fontWeight: "600",
    color: Colors.dark.xpCyan,
    minWidth: 30,
    textAlign: "right",
  },
  gamingCardMeta: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: Spacing.md,
  },
  gamingLevelBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
  },
  gamingLevelDotSmall: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  gamingLevelText: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  gamingMetaText: {
    fontSize: 11,
    color: Colors.dark.tabIconDefault + "80",
  },
  creditsBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: 4,
  },
  creditsText: {
    fontSize: 10,
    fontWeight: "600",
  },
  gamingChevron: {
    padding: Spacing.xs,
  },
  gamingFab: {
    position: "absolute",
    bottom: 100,
    right: Spacing.lg,
    borderRadius: 28,
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.xpCyan,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 12,
      },
      android: { elevation: 12 },
    }),
  },
  gamingFabPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.95 }],
  },
  gamingFabGradient: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  headerAddButton: {
    borderRadius: 20,
    overflow: "hidden",
  },
  headerAddButtonGradient: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  headerAddButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.dark.buttonText,
    letterSpacing: 0.5,
  },

  // === CALM STYLES (60% - Gold Standard like Calendar/Settings) ===
  calmHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.lg,
  },
  calmHeaderLeft: {
    gap: 2,
  },
  calmTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  calmSubtitle: {
    fontSize: 14,
    color: Colors.dark.tabIconDefault,
  },
  calmAddButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.dark.backgroundSecondary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.dark.headerBorder,
  },
  calmSearchContainer: {
    paddingHorizontal: Spacing.lg,
    marginBottom: Spacing.md,
  },
  calmSearchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    height: 44,
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.dark.headerBorder,
  },
  calmSearchInput: {
    flex: 1,
    fontSize: 16,
    color: Colors.dark.text,
  },
  calmFilterScroll: {
    marginBottom: Spacing.md,
    maxHeight: 50,
  },
  calmFilterContent: {
    paddingHorizontal: Spacing.lg,
    gap: Spacing.sm,
    alignItems: "flex-start",
  },
  calmFilterPill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    height: 36,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.md,
    gap: Spacing.xs,
    borderWidth: 1,
    borderColor: Colors.dark.headerBorder,
  },
  calmFilterPillActive: {
    backgroundColor: Colors.dark.primary + "20",
    borderColor: Colors.dark.primary,
  },
  calmFilterText: {
    fontSize: 14,
    fontWeight: "500",
    color: Colors.dark.tabIconDefault,
  },
  calmFilterTextActive: {
    color: Colors.dark.primary,
    fontWeight: "600",
  },
  calmLevelDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  emptySubtext: {
    fontSize: 14,
    color: Colors.dark.textMuted,
    textAlign: "center",
  },
  calmPlayerCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.dark.backgroundSecondary,
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.sm,
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    gap: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.dark.headerBorder,
  },
  calmAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  calmAvatarText: {
    fontSize: 18,
    fontWeight: "600",
  },
  calmAvatarPhoto: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.dark.backgroundSecondary,
  },
  calmPlayerInfo: {
    flex: 1,
    gap: 4,
  },
  calmPlayerNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  calmPlayerName: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.dark.text,
    flex: 1,
  },
  calmStatusBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.xs,
  },
  calmStatusText: {
    fontSize: 11,
    fontWeight: "600",
  },
  calmPlayerMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
  },
  calmLevelBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.xs,
    borderWidth: 1,
  },
  calmLevelDotSmall: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  calmLevelText: {
    fontSize: 12,
    fontWeight: "500",
  },
  calmMetaText: {
    fontSize: 12,
    color: Colors.dark.tabIconDefault,
  },
  
  // === HUD COMMAND HEADER (keeping for reference) ===
  hudHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.primary + "30",
    position: "relative",
    overflow: "hidden",
  },
  hudHeaderBg: {
    ...StyleSheet.absoluteFillObject,
  },
  scanlineOverlay: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.03,
    backgroundColor: "transparent",
  },
  hudLeft: {
    flex: 1,
  },
  hudLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 2,
  },
  hudDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.dark.primary,
  },
  hudLabel: {
    fontSize: 9,
    fontWeight: "600",
    color: Colors.dark.primary,
    letterSpacing: 1.5,
  },
  hudTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: Colors.dark.text,
    letterSpacing: 2,
  },
  hudStatRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
  },
  hudStatValue: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  hudStatLabel: {
    fontSize: 9,
    fontWeight: "500",
    color: Colors.dark.tabIconDefault,
    letterSpacing: 0.5,
  },
  hudCenter: {
    width: 70,
    height: 70,
    alignItems: "center",
    justifyContent: "center",
  },
  hudIconOuter: {
    position: "absolute",
    width: 66,
    height: 66,
    borderRadius: 33,
    borderWidth: 3,
    borderColor: Colors.dark.primary,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 1,
        shadowRadius: 20,
      },
      android: {},
    }),
  },
  hudIconGlow: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: Colors.dark.primary + "40",
  },
  hudIconInner: {
    position: "absolute",
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: Colors.dark.primary + "25",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: Colors.dark.primary + "70",
  },
  hudRight: {
    flex: 1,
    alignItems: "flex-end",
    gap: Spacing.sm,
  },
  hudXpBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.gold + "15",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.dark.gold + "40",
  },
  hudXpValue: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.dark.gold,
  },
  hudXpLabel: {
    fontSize: 9,
    fontWeight: "500",
    color: Colors.dark.gold,
    opacity: 0.7,
  },
  hudAddButton: {
    borderRadius: 12,
    overflow: "hidden",
  },
  hudAddButtonGradient: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },

  // === TACTICAL COMMAND STRIP ===
  commandStrip: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    position: "relative",
  },
  commandStripBg: {
    ...StyleSheet.absoluteFillObject,
  },
  tacticalSearch: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Backgrounds.overlay,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "40",
    overflow: "hidden",
  },
  tacticalSearchIcon: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.dark.primary + "15",
    borderRightWidth: 1,
    borderRightColor: Colors.dark.primary + "30",
  },
  tacticalSearchInput: {
    flex: 1,
    height: 40,
    paddingHorizontal: Spacing.md,
    fontSize: 12,
    fontWeight: "500",
    color: Colors.dark.text,
    letterSpacing: 0.5,
  },
  tacticalSearchClear: {
    width: 32,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },

  // === TACTICAL FILTER STRIP ===
  filterStrip: {
    paddingVertical: Spacing.sm,
  },
  filterStripContent: {
    paddingHorizontal: Spacing.lg,
    gap: Spacing.sm,
  },
  tacticalChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    borderRadius: 8,
    paddingHorizontal: Spacing.md,
    paddingVertical: 10,
    gap: 8,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.15)",
    position: "relative",
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 4,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  tacticalChipActive: {
    borderColor: Colors.dark.primary,
    borderWidth: 2,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 12,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  tacticalChipGlow: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "transparent",
  },
  tacticalChipGlowActive: {
    backgroundColor: Colors.dark.primary + "35",
  },
  tacticalChipText: {
    fontSize: 11,
    fontWeight: "800",
    color: Colors.dark.tabIconDefault,
    letterSpacing: 1.5,
  },
  tacticalChipTextActive: {
    color: Colors.dark.primary,
    textShadowColor: Colors.dark.primary,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  tacticalChipCount: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    minWidth: 20,
    alignItems: "center",
  },
  tacticalChipCountActive: {
    backgroundColor: Colors.dark.primary + "30",
  },
  tacticalChipCountText: {
    fontSize: 9,
    fontWeight: "700",
    color: Colors.dark.tabIconDefault,
  },
  tacticalLevelIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },

  // === LOADOUT CARDS ===
  loadoutCard: {
    marginBottom: Spacing.lg,
    marginHorizontal: Spacing.md,
    borderRadius: 16,
    position: "relative",
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 20,
      },
      android: {
        elevation: 12,
      },
    }),
  },
  loadoutGlowFrame: {
    position: "absolute",
    top: -3,
    left: -3,
    right: -3,
    bottom: -3,
    borderRadius: 19,
    borderWidth: 3,
  },
  loadoutGlowFrameInner: {
    position: "absolute",
    top: -1,
    left: -1,
    right: -1,
    bottom: -1,
    borderRadius: 17,
    borderWidth: 2,
  },
  loadoutCardBg: {
    borderRadius: 16,
    borderWidth: 2,
    borderColor: Colors.dark.primary + "50",
    overflow: "hidden",
  },
  loadoutTopStrip: {
    height: 5,
    width: "100%",
  },
  loadoutContent: {
    flexDirection: "row",
    alignItems: "center",
    padding: Spacing.md,
    gap: Spacing.md,
  },
  loadoutAvatarContainer: {
    width: 64,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  loadoutAvatarGlowOuter: {
    position: "absolute",
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  loadoutAvatarGlow: {
    position: "absolute",
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  loadoutAvatarRing: {
    position: "absolute",
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 3,
  },
  loadoutAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  loadoutAvatarText: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.dark.buttonText,
  },
  loadoutTierBadge: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#0a0a0a",
  },
  loadoutTierText: {
    fontSize: 10,
    fontWeight: "800",
    color: Colors.dark.buttonText,
  },
  loadoutInfo: {
    flex: 1,
    gap: 4,
  },
  loadoutNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  loadoutName: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.dark.text,
    letterSpacing: 0.5,
    flex: 1,
  },
  loadoutStatusBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  loadoutXpContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  loadoutXpBar: {
    flex: 1,
    height: 4,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 2,
    overflow: "hidden",
  },
  loadoutXpFill: {
    height: "100%",
    borderRadius: 2,
  },
  loadoutXpText: {
    fontSize: 10,
    fontWeight: "600",
    color: Colors.dark.xpCyan,
    minWidth: 45,
    textAlign: "right",
  },
  loadoutStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  loadoutStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  loadoutStatDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  loadoutStatText: {
    fontSize: 9,
    fontWeight: "500",
    color: Colors.dark.tabIconDefault,
    letterSpacing: 0.3,
  },
  loadoutStatDivider: {
    width: 1,
    height: 10,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
  },
  loadoutAction: {
    alignItems: "center",
    justifyContent: "center",
  },
  loadoutActionButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: Colors.dark.primary + "15",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.dark.primary + "40",
  },

  // === LEGACY STYLES (keeping for compatibility) ===
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.md,
  },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  headerIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.dark.primary + "25",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.dark.primary + "50",
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.dark.primary,
    justifyContent: "center",
    alignItems: "center",
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 8,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  title: {
    fontSize: 14,
    fontWeight: "800",
    color: Colors.dark.text,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  subtitle: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  searchContainer: {
    paddingHorizontal: Spacing.lg,
    marginBottom: Spacing.md,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    height: 48,
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "60",
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  searchInput: {
    flex: 1,
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
  },
  filterContainer: {
    paddingLeft: Spacing.lg,
    marginBottom: Spacing.md,
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    marginRight: Spacing.sm,
    gap: Spacing.xs,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "50",
  },
  filterChipActive: {
    backgroundColor: Colors.dark.primary,
    borderColor: Colors.dark.primary,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  filterChipText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    fontWeight: "500",
  },
  filterChipTextActive: {
    color: Colors.dark.buttonText,
    fontWeight: "700",
  },
  levelDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: Spacing.md,
  },
  emptyText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  playerList: {
    flex: 1,
  },
  playerCardContainer: {
    marginBottom: Spacing.sm,
    borderRadius: BorderRadius.lg,
    overflow: "hidden",
  },
  playerCardGlow: {
    position: "absolute" as const,
    top: -2,
    left: -2,
    right: -2,
    bottom: -2,
    borderRadius: BorderRadius.lg + 2,
    borderWidth: 2,
    borderColor: Colors.dark.primary,
    opacity: 0.6,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 12,
      },
      android: {},
    }),
  },
  playerCardTopLine: {
    height: 3,
    width: "100%",
  },
  playerCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Backgrounds.card,
    padding: Spacing.md,
    gap: Spacing.md,
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderBottomLeftRadius: BorderRadius.lg,
    borderBottomRightRadius: BorderRadius.lg,
  },
  playerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.dark.primary + "30",
    alignItems: "center",
    justifyContent: "center",
  },
  playerInitial: {
    fontSize: Typography.h3.fontSize,
    fontWeight: "600",
    color: Colors.dark.primary,
  },
  playerInfo: {
    flex: 1,
  },
  playerNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  playerName: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.xs,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
    gap: 4,
  },
  statusText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "500",
  },
  playerDetails: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
    marginTop: 4,
  },
  levelBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  levelText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  lastLesson: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  backButton: {
    padding: Spacing.xs,
  },
  exportButton: {
    padding: Spacing.xs,
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  detailTitle: {
    ...Typography.h3,
    color: Colors.dark.text,
  },
  detailContent: {
    flex: 1,
    paddingHorizontal: Spacing.lg,
  },
  profileHeader: {
    alignItems: "center",
    marginBottom: Spacing.xl,
  },
  largeAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: Colors.dark.primary + "30",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.md,
  },
  largeInitial: {
    fontSize: 32,
    fontWeight: "600",
    color: Colors.dark.primary,
  },
  largeAvatarPhoto: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: Colors.dark.backgroundSecondary,
    marginBottom: Spacing.md,
  },
  profileName: {
    ...Typography.h2,
    color: Colors.dark.text,
  },
  profileLevel: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginTop: Spacing.xs,
  },
  profileLevelText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  infoSection: {
    marginBottom: Spacing.lg,
    marginHorizontal: Spacing.lg,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.dark.text,
    marginBottom: Spacing.sm,
    letterSpacing: 0.5,
  },
  infoCard: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    gap: Spacing.md,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  warningCard: {
    flexDirection: "row",
    gap: Spacing.md,
    borderLeftWidth: 3,
    borderLeftColor: Colors.dark.error,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
  },
  infoText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
  },
  sendInviteButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "60",
    alignSelf: "flex-start",
    backgroundColor: Colors.dark.primary + "12",
  },
  sendInviteButtonText: {
    fontSize: 13,
    color: Colors.dark.primary,
    fontWeight: "600",
  },
  medicalText: {
    flex: 1,
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
  },
  statsGrid: {
    flexDirection: "row",
    gap: Spacing.sm,
  },
  statCard: {
    flex: 1,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    alignItems: "center",
  },
  statValue: {
    fontSize: Typography.h2.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  statLabel: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.tabIconDefault,
    textAlign: "center",
  },
  notesCard: {
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    alignItems: "center",
    gap: Spacing.md,
  },
  noNotesText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  addNoteButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    backgroundColor: Colors.dark.primary + "15",
    padding: Spacing.md,
    borderRadius: BorderRadius.md,
    marginTop: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "30",
  },
  addNoteText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.primary,
    fontWeight: "600",
  },
  nextLessonSection: {
    backgroundColor: Colors.dark.primary + "15",
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.lg,
    borderLeftWidth: 3,
    borderLeftColor: Colors.dark.primary,
  },
  nextLessonHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  nextLessonTitle: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.primary,
  },
  nextLessonText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
  },
  notesSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.sm,
  },
  notesCount: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.full,
  },
  addNoteForm: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    marginTop: Spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  categoryPicker: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.xs,
    marginBottom: Spacing.md,
  },
  categoryChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.backgroundRoot,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
    borderRadius: BorderRadius.full,
  },
  categoryChipActive: {
    backgroundColor: Colors.dark.primary + "20",
    borderWidth: 1,
    borderColor: Colors.dark.primary,
  },
  categoryChipText: {
    fontSize: 11,
    color: Colors.dark.tabIconDefault,
  },
  categoryChipTextActive: {
    color: Colors.dark.primary,
  },
  noteInput: {
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    minHeight: 80,
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
    textAlignVertical: "top",
  },
  noteActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: Spacing.sm,
    marginTop: Spacing.md,
  },
  cancelButton: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  cancelButtonText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  saveNoteButton: {
    backgroundColor: Colors.dark.primary,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
    minWidth: 80,
    alignItems: "center",
  },
  saveNoteButtonDisabled: {
    opacity: 0.5,
  },
  saveNoteButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.buttonText,
  },
  emptyNotesCard: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.lg,
    padding: Spacing.xl,
    alignItems: "center",
    gap: Spacing.sm,
    marginTop: Spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  notesList: {
    marginTop: Spacing.md,
    gap: Spacing.sm,
  },
  noteCard: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  pinnedNoteCard: {
    borderWidth: 1,
    borderColor: Colors.dark.gold + "40",
    backgroundColor: Colors.dark.gold + "08",
  },
  noteHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.sm,
  },
  noteCategoryBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.backgroundRoot,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.full,
  },
  noteCategoryText: {
    fontSize: 10,
    color: Colors.dark.tabIconDefault,
  },
  noteContent: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
    lineHeight: 22,
  },
  noteFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: Spacing.sm,
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.dark.headerBorder,
  },
  noteDate: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  noteFooterActions: {
    flexDirection: "row",
    gap: Spacing.md,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
    padding: Spacing.lg,
  },
  modalContent: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.lg,
  },
  modalTitle: {
    fontSize: Typography.h3.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  formGroup: {
    marginBottom: Spacing.md,
  },
  formLabel: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    marginBottom: Spacing.xs,
  },
  formInput: {
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
  },
  levelPicker: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
  },
  formHint: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.primary,
    marginBottom: Spacing.sm,
    fontWeight: "500",
  },
  skillLevelPicker: {
    flexDirection: "row",
    gap: Spacing.md,
  },
  skillLevelOption: {
    width: 56,
    height: 56,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.dark.backgroundTertiary,
    borderWidth: 2,
    borderColor: Colors.dark.tabIconDefault + "40",
    justifyContent: "center",
    alignItems: "center",
  },
  skillLevelText: {
    fontSize: Typography.h3.fontSize,
    fontWeight: "600",
    color: Colors.dark.tabIconDefault,
  },
  levelOption: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    gap: Spacing.xs,
  },
  levelOptionWrapper: {
    borderRadius: BorderRadius.full,
  },
  levelOptionGlowOuter: {
    borderRadius: BorderRadius.full,
    padding: 2,
  },
  levelOptionGradient: {
    borderRadius: BorderRadius.full,
    overflow: "hidden",
  },
  levelOptionInner: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    gap: Spacing.xs,
  },
  levelOptionUnselected: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    gap: Spacing.xs,
  },
  levelOptionText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  levelOptionTextSelected: {
    color: Colors.dark.primary,
    fontWeight: "600",
  },
  modalActions: {
    flexDirection: "row",
    gap: Spacing.md,
    marginTop: Spacing.lg,
  },
  addCancelButton: {
    flex: 1,
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: BorderRadius.md,
    paddingVertical: Spacing.sm,
    alignItems: "center",
  },
  addSaveButton: {
    flex: 1,
    backgroundColor: Colors.dark.primary,
    borderRadius: BorderRadius.md,
    paddingVertical: Spacing.sm,
    alignItems: "center",
  },
  addSaveButtonDisabled: {
    opacity: 0.5,
  },
  addSaveButtonText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.backgroundDefault,
    fontWeight: "600",
  },
  levelReadinessCard: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.lg,
    borderWidth: 1,
    borderColor: GlowColors.primary + "30",
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
      },
      android: { elevation: 4 },
    }),
  },
  levelReadinessHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  levelReadinessIcon: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.dark.primary + "25",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.dark.primary + "40",
  },
  levelReadinessTitle: {
    flex: 1,
    fontSize: Typography.body.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
    letterSpacing: 0.5,
  },
  xpBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.xpCyan + "20",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.full,
  },
  xpBadgeText: {
    fontSize: Typography.small.fontSize,
    fontWeight: "600",
    color: Colors.dark.xpCyan,
  },
  progressContainer: {
    gap: Spacing.sm,
  },
  levelLabels: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.md,
  },
  currentLevelLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  nextLevelLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  levelDotSmall: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  levelLabelText: {
    fontSize: Typography.small.fontSize,
    fontWeight: "500",
    color: Colors.dark.text,
  },
  progressBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  progressBarBackground: {
    flex: 1,
    height: 8,
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: BorderRadius.full,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: BorderRadius.full,
  },
  progressPercent: {
    fontSize: Typography.small.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
    minWidth: 36,
    textAlign: "right",
  },
  xpRemainingText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    textAlign: "center",
    marginTop: Spacing.xs,
  },
  pillarGrid: {
    gap: Spacing.sm,
  },
  pillarItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  pillarIconContainer: {
    width: 28,
    height: 28,
    borderRadius: BorderRadius.full,
    alignItems: "center",
    justifyContent: "center",
  },
  pillarInfo: {
    flex: 1,
  },
  pillarNameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  pillarName: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.text,
    fontWeight: "500",
  },
  pillarProgressBar: {
    height: 4,
    backgroundColor: Colors.dark.tabIconDefault + "30",
    borderRadius: 2,
    overflow: "hidden",
  },
  pillarProgressFill: {
    height: "100%",
    borderRadius: 2,
  },
  pillarPercent: {
    fontSize: Typography.small.fontSize,
    fontWeight: "700",
    minWidth: 36,
    textAlign: "right",
  },
  feedbackSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginTop: Spacing.md,
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.dark.tabIconDefault + "20",
  },
  feedbackSummaryText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  ratePillarButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.xs,
    marginTop: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.dark.primary + "18",
    borderWidth: 1,
    borderColor: Colors.dark.primary + "40",
  },
  ratePillarButtonText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "700" as const,
    color: Colors.dark.primary,
  },
  baselineManagementCard: {
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.lg,
    padding: Spacing.lg,
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  baselineManagementHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
    marginBottom: Spacing.md,
  },
  baselineIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.dark.primary + "20",
    alignItems: "center",
    justifyContent: "center",
  },
  baselineManagementTitle: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  baselineManagementStatus: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    marginTop: 2,
  },
  baselineActionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
  },
  baselineStartButton: {
    backgroundColor: Colors.dark.primary,
  },
  baselineResetButton: {
    backgroundColor: Colors.dark.gold + "20",
    borderWidth: 1,
    borderColor: Colors.dark.gold + "40",
  },
  baselineActionButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.buttonText,
  },
  baselineResetButtonText: {
    color: Colors.dark.gold,
  },
  confirmModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "center",
    alignItems: "center",
    padding: Spacing.xl,
  },
  confirmModalContent: {
    width: "100%",
    maxWidth: 320,
    backgroundColor: Backgrounds.elevated,
    borderRadius: BorderRadius.lg,
    padding: Spacing.xl,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  confirmModalIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.dark.gold + "20",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.md,
  },
  confirmModalTitle: {
    fontSize: Typography.h3.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
    marginBottom: Spacing.sm,
  },
  confirmModalText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.textMuted,
    textAlign: "center",
    marginBottom: Spacing.xl,
    lineHeight: 22,
  },
  confirmModalActions: {
    flexDirection: "row",
    gap: Spacing.md,
    width: "100%",
  },
  confirmModalCancelButton: {
    flex: 1,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: BorderRadius.md,
    alignItems: "center",
  },
  confirmModalCancelText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  confirmModalConfirmButton: {
    flex: 1,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.dark.gold,
    borderRadius: BorderRadius.md,
    alignItems: "center",
  },
  confirmModalConfirmText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.buttonText,
  },
  onboardingCard: {
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.lg,
    padding: Spacing.lg,
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.xpCyan,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
      },
      android: { elevation: 4 },
    }),
  },
  onboardingHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  onboardingTitle: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  onboardingGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.md,
    marginBottom: Spacing.md,
  },
  onboardingItem: {
    minWidth: 100,
  },
  onboardingLabel: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    marginBottom: Spacing.xs,
  },
  onboardingValue: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
    fontWeight: "500",
  },
  onboardingTagSection: {
    marginTop: Spacing.sm,
  },
  onboardingTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.xs,
    marginTop: Spacing.xs,
  },
  onboardingTag: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    backgroundColor: Colors.dark.xpCyan + "20",
    borderRadius: BorderRadius.md,
  },
  onboardingTagGoal: {
    backgroundColor: Colors.dark.primary + "20",
  },
  onboardingTagNeutral: {
    backgroundColor: Colors.dark.backgroundTertiary,
  },
  onboardingTagText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.xpCyan,
  },
  onboardingTagGoalText: {
    color: Colors.dark.primary,
  },
  sectionHeader: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.dark.textMuted,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginTop: Spacing.lg,
    marginBottom: Spacing.md,
  },
  inviteModalContent: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.xl,
  },
  inviteModalHeader: {
    alignItems: "center",
    marginBottom: Spacing.xl,
  },
  inviteSuccessIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: Colors.dark.primary + "20",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.md,
  },
  inviteModalTitle: {
    fontSize: Typography.h2.fontSize,
    fontWeight: "700",
    color: Colors.dark.text,
    marginBottom: Spacing.xs,
  },
  inviteModalSubtitle: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
    textAlign: "center",
  },
  inviteCodeSection: {
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    marginBottom: Spacing.lg,
  },
  inviteCodeLabel: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    marginBottom: Spacing.md,
    textAlign: "center",
  },
  inviteCodeBox: {
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "40",
  },
  inviteCodeText: {
    fontSize: 32,
    fontWeight: "900",
    color: Colors.dark.primary,
    textAlign: "center",
    letterSpacing: 8,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  copyButton: {
    borderRadius: BorderRadius.md,
    overflow: "hidden",
  },
  copyButtonGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
  },
  copyButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.buttonText,
  },
  inviteShareButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "60",
    backgroundColor: Colors.dark.primary + "10",
    marginTop: Spacing.sm,
  },
  inviteShareButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.primary,
  },
  inviteInstructionText: {
    fontSize: 13,
    color: Colors.dark.tabIconDefault,
    textAlign: "center",
    marginTop: Spacing.sm,
    lineHeight: 18,
  },
  inviteDoneButton: {
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: BorderRadius.md,
    paddingVertical: Spacing.md,
    alignItems: "center",
    marginTop: Spacing.sm,
  },
  inviteDoneButtonText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
    fontWeight: "500",
  },
  awaitingSignupBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: Colors.dark.orange + "25",
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: Colors.dark.orange + "50",
  },
  awaitingSignupText: {
    fontSize: 8,
    fontWeight: "700",
    color: Colors.dark.orange,
    letterSpacing: 0.2,
  },
  prominentInviteCard: {
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.md,
    borderWidth: 2,
    borderColor: Colors.dark.primary + "40",
    overflow: "hidden",
  },
  prominentInviteCardTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.dark.primary,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: Spacing.sm,
  },
  prominentInviteCode: {
    fontSize: 40,
    fontWeight: "900",
    color: Colors.dark.primary,
    textAlign: "center",
    letterSpacing: 10,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
    marginVertical: Spacing.md,
  },
  prominentInviteInstruction: {
    fontSize: 13,
    color: Colors.dark.textSecondary,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: Spacing.md,
  },
  prominentCopyButton: {
    borderRadius: BorderRadius.md,
    overflow: "hidden",
    marginBottom: Spacing.sm,
  },
  prominentCopyButtonGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md + 2,
    paddingHorizontal: Spacing.lg,
  },
  prominentCopyButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.dark.buttonText,
  },
  prominentShareButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "60",
    backgroundColor: Colors.dark.primary + "10",
  },
  prominentShareButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.dark.primary,
  },
  pendingInvitePopover: {
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    width: 280,
    borderWidth: 1,
    borderColor: Colors.dark.orange + "40",
    alignItems: "center",
  },
  pendingInvitePopoverTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.dark.text,
    marginBottom: Spacing.xs,
  },
  pendingInvitePopoverCode: {
    fontSize: 28,
    fontWeight: "900",
    color: Colors.dark.orange,
    letterSpacing: 6,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
    marginVertical: Spacing.sm,
  },
  pendingInvitePopoverInstruction: {
    fontSize: 12,
    color: Colors.dark.textMuted,
    textAlign: "center",
    lineHeight: 16,
    marginBottom: Spacing.md,
  },
  pendingInviteCopyBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.dark.orange + "20",
    borderRadius: BorderRadius.md,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: Colors.dark.orange + "50",
    width: "100%",
    justifyContent: "center",
  },
  pendingInviteCopyBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.dark.orange,
  },
  pendingInviteDismissBtn: {
    marginTop: Spacing.sm,
    paddingVertical: 8,
  },
  pendingInviteDismissBtnText: {
    fontSize: 13,
    color: Colors.dark.textMuted,
    textAlign: "center",
  },

  // === PREMIUM PLAYER PROFILE STYLES ===
  premiumDetailHeader: {
    paddingBottom: Spacing.lg,
  },
  premiumHeaderTopLine: {
    height: 3,
    width: "100%",
  },
  premiumHeaderNav: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
  },
  premiumBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  premiumExportButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.dark.xpCyan + "20",
    alignItems: "center",
    justifyContent: "center",
  },
  premiumProfileCard: {
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.sm,
    padding: Spacing.md,
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  premiumAvatarContainer: {
    alignItems: "center",
    marginBottom: Spacing.sm,
    position: "relative",
  },
  premiumAvatarGlow: {
    position: "absolute",
    width: 72,
    height: 72,
    borderRadius: 36,
    opacity: 0.3,
  },
  premiumAvatarPhoto: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: Colors.dark.xpCyan,
  },
  premiumAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: Colors.dark.xpCyan + "50",
  },
  premiumInitial: {
    fontSize: 26,
    fontWeight: "700",
  },
  premiumProfileInfo: {
    alignItems: "center",
    gap: Spacing.xs,
  },
  premiumProfileName: {
    fontSize: 20,
    fontWeight: "700",
    color: Colors.dark.text,
    letterSpacing: 0.5,
  },
  premiumLevelBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.full,
  },
  premiumLevelDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  premiumLevelText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  premiumXpBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.xpCyan + "20",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    borderColor: Colors.dark.xpCyan + "40",
  },
  premiumXpText: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.dark.xpCyan,
  },
  premiumQuickStats: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: Spacing.lg,
    paddingTop: Spacing.lg,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.1)",
  },
  premiumQuickStat: {
    flex: 1,
    alignItems: "center",
  },
  premiumQuickStatValue: {
    fontSize: 24,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  premiumQuickStatLabel: {
    fontSize: 11,
    fontWeight: "500",
    color: Colors.dark.tabIconDefault,
    marginTop: 2,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  premiumQuickStatDivider: {
    width: 1,
    height: 32,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
  },

  // === ATTENDANCE HISTORY STYLES ===
  attendanceHistoryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.md,
  },
  attendanceHistoryTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  attendanceHistoryCount: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.xpCyan,
    fontWeight: "700",
    backgroundColor: Colors.dark.xpCyan + "15",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.full,
  },
  reportButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FF0000",
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: BorderRadius.full,
    borderWidth: 2,
    borderColor: "#FF0000",
  },
  reportButtonText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  emptyAttendanceCard: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.lg,
    padding: Spacing.xl,
    alignItems: "center",
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  emptyAttendanceText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
    fontWeight: "600",
  },
  emptyAttendanceSubtext: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.disabled,
  },
  attendanceHistoryList: {
    gap: Spacing.sm,
  },
  attendanceHistoryRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderLeftWidth: 3,
    borderLeftColor: GlowColors.primary,
  },
  attendanceHistoryDate: {
    flex: 1,
  },
  attendanceHistoryDateText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  attendanceHistoryTime: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    marginTop: 2,
  },
  attendanceHistoryDetails: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
  },
  attendanceHistoryType: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.xs,
  },
  attendanceHistoryTypeText: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.dark.tabIconDefault,
  },
  attendanceStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.xs,
  },
  attendanceStatusPresent: {
    backgroundColor: Colors.dark.primary + "20",
  },
  attendanceStatusAbsent: {
    backgroundColor: Colors.dark.error + "20",
  },
  attendanceStatusPending: {
    backgroundColor: Colors.dark.gold + "20",
  },
  attendanceStatusCancelled: {
    backgroundColor: "#E53935" + "30",  // Red background for cancelled
  },
  attendanceStatusText: {
    fontSize: 11,
    fontWeight: "600",
  },
  attendanceStatusTextPresent: {
    color: Colors.dark.primary,
  },
  attendanceStatusTextAbsent: {
    color: Colors.dark.error,
  },
  attendanceStatusTextPending: {
    color: Colors.dark.gold,
  },
  attendanceStatusTextCancelled: {
    color: "#E53935",  // Red text for cancelled
  },
  showMoreHistoryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.xs,
    paddingVertical: Spacing.md,
    marginTop: Spacing.sm,
    backgroundColor: Colors.dark.xpCyan + "10",
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.dark.xpCyan + "30",
  },
  showMoreHistoryText: {
    fontSize: Typography.small.fontSize,
    fontWeight: "700",
    color: Colors.dark.xpCyan,
    letterSpacing: 0.5,
  },
  
  // Series attendance summary styles
  seriesSummaryContainer: {
    marginBottom: Spacing.lg,
  },
  seriesSummaryTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.dark.xpCyan,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: Spacing.sm,
  },
  seriesSummaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
  },
  seriesSummaryCard: {
    flex: 1,
    minWidth: 140,
    backgroundColor: Colors.dark.xpCyan + "10",
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.dark.xpCyan + "30",
  },
  seriesSummaryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: Spacing.sm,
  },
  seriesSummaryDay: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.dark.xpCyan,
  },
  seriesSummaryTime: {
    fontSize: 12,
    color: Colors.dark.tabIconDefault,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.xs,
  },
  seriesSummaryStats: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  seriesSummaryStat: {
    alignItems: "center",
  },
  seriesSummaryStatValue: {
    fontSize: 18,
    fontWeight: "700",
  },
  seriesSummaryStatLabel: {
    fontSize: 9,
    color: Colors.dark.tabIconDefault,
    textTransform: "uppercase",
  },
  
  // Series group section styles
  seriesGroupSection: {
    marginBottom: Spacing.md,
  },
  seriesGroupHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.dark.xpCyan + "15",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.sm,
    borderLeftWidth: 3,
    borderLeftColor: Colors.dark.xpCyan,
  },
  seriesGroupHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  seriesGroupDay: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.dark.xpCyan,
  },
  seriesGroupTime: {
    fontSize: 12,
    color: Colors.dark.tabIconDefault,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: BorderRadius.xs,
  },
  seriesGroupCount: {
    backgroundColor: Colors.dark.xpCyan + "30",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: BorderRadius.full,
  },
  seriesGroupCountText: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.dark.xpCyan,
  },

  // === EDIT ATTENDANCE MODAL STYLES ===
  attendanceEditButton: {
    padding: 8,
    marginLeft: 8,
  },
  editAttendanceModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  editAttendanceModalContent: {
    backgroundColor: Backgrounds.elevated,
    borderRadius: 16,
    padding: 24,
    width: "85%",
    maxWidth: 340,
  },
  editAttendanceModalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.dark.text,
    textAlign: "center",
    marginBottom: 4,
  },
  editAttendanceModalSubtitle: {
    fontSize: 14,
    color: Colors.dark.textSecondary,
    textAlign: "center",
    marginBottom: 20,
  },
  editAttendanceOption: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 12,
    backgroundColor: Backgrounds.card,
    marginBottom: 8,
    gap: 12,
  },
  editAttendanceOptionSelected: {
    borderWidth: 1,
    borderColor: Colors.dark.primary,
  },
  editAttendanceOptionText: {
    fontSize: 16,
    color: Colors.dark.text,
    fontWeight: "500",
  },
  editAttendanceNote: {
    fontSize: 12,
    color: Colors.dark.textSecondary,
    textAlign: "center",
    marginTop: 16,
    fontStyle: "italic",
  },
  paymentsSection: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.md,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  paymentsSectionTitle: {
    ...Typography.h3,
    color: Colors.dark.text,
    fontWeight: "700",
    marginBottom: Spacing.md,
  },
  paymentsSummary: {
    alignItems: "flex-start",
    marginBottom: Spacing.md,
  },
  paymentsStatusBadge: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
    backgroundColor: Backgrounds.card,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  paymentsStatusText: {
    ...Typography.caption,
    fontWeight: "700",
  },
  paymentsFinanceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: Spacing.sm,
  },
  paymentsFinanceLabel: {
    ...Typography.body,
    color: Colors.dark.textMuted,
  },
  paymentsFinanceValue: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "600",
  },
  paymentsActions: {
    flexDirection: "row",
    gap: Spacing.sm,
    marginTop: Spacing.lg,
  },
  paymentsRecordButton: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: Colors.dark.orange,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  paymentsRecordText: {
    ...Typography.body,
    color: Colors.dark.buttonText,
    fontWeight: "700",
  },
  paymentsCreateInvoiceButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.xs,
    backgroundColor: Colors.dark.successNeon + "20",
    borderWidth: 1,
    borderColor: Colors.dark.successNeon + "40",
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
  },
  paymentsCreateInvoiceText: {
    ...Typography.body,
    color: Colors.dark.successNeon,
    fontWeight: "600",
  },
  recordPaymentOverlay: {
    flex: 1,
    backgroundColor: Colors.dark.backgroundRoot,
    justifyContent: "flex-end",
  },
  recordPaymentContainer: {
    backgroundColor: Backgrounds.elevated,
    borderTopLeftRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
    maxHeight: "70%",
    paddingBottom: 34,
  },
  recordPaymentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.border,
  },
  recordPaymentTitle: {
    ...Typography.h3,
    color: Colors.dark.text,
    fontWeight: "700",
  },
  recordPaymentClose: {
    padding: Spacing.xs,
  },
  recordPaymentContent: {
    padding: Spacing.lg,
  },
  noUnpaidBox: {
    alignItems: "center",
    paddingVertical: Spacing.xl,
    gap: Spacing.md,
  },
  noUnpaidTitleText: {
    ...Typography.h3,
    color: Colors.dark.successNeon,
    fontWeight: "700",
  },
  noUnpaidSubText: {
    ...Typography.body,
    color: Colors.dark.textMuted,
    textAlign: "center",
  },
  unpaidTitle: {
    ...Typography.caption,
    color: Colors.dark.textMuted,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: Spacing.md,
  },
  unpaidCard: {
    backgroundColor: Backgrounds.card,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    marginBottom: Spacing.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: `${Colors.dark.error}40`,
  },
  unpaidInfo: {
    flex: 1,
    gap: 4,
  },
  unpaidRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  unpaidType: {
    ...Typography.body,
    color: Colors.dark.text,
    fontWeight: "600",
  },
  unpaidCredits: {
    ...Typography.small,
    color: Colors.dark.textMuted,
  },
  unpaidPrice: {
    ...Typography.body,
    color: Colors.dark.error,
    fontWeight: "700",
  },
  markPaidBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.dark.successNeon,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
  },
  markPaidBtnText: {
    ...Typography.caption,
    color: Colors.dark.buttonText,
    fontWeight: "700",
  },
  recordPaymentDone: {
    backgroundColor: Colors.dark.primary,
    marginHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    alignItems: "center",
  },
  recordPaymentDoneText: {
    ...Typography.body,
    color: Colors.dark.buttonText,
    fontWeight: "700",
  },

  // === ROSTER TAB SWITCHER ===
  rosterTabSwitcher: {
    flexDirection: "row",
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.md,
    marginBottom: Spacing.xs,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: BorderRadius.md,
    padding: 3,
    gap: 3,
  },
  rosterTabButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 8,
    borderRadius: BorderRadius.sm,
  },
  rosterTabButtonActive: {
    backgroundColor: Colors.dark.primary,
  },
  rosterTabText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.dark.tabIconDefault,
    letterSpacing: 0.3,
  },
  rosterTabTextActive: {
    color: Colors.dark.buttonText,
  },

  // === ARCHIVE / RESTORE ACTION BUTTONS ===
  archiveActionBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.06)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  restoreActionBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Colors.dark.primary + "20",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.dark.primary + "50",
  },
});

export const strokeTimelineStyles = StyleSheet.create({
  strokeRow: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: BorderRadius.sm,
    padding: Spacing.sm,
    marginBottom: Spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  strokeHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.xs,
  },
  strokeName: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.dark.text,
  },
  latestBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
  },
  latestBadgeText: {
    fontSize: 11,
    fontWeight: "600",
  },
  miniTimeline: {
    flexDirection: "row",
    gap: 5,
    marginTop: 4,
    alignItems: "center",
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  strokeNote: {
    fontSize: 12,
    color: Colors.dark.textMuted,
    marginTop: 6,
    fontStyle: "italic",
  },
  playerNoteCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: BorderRadius.sm,
    padding: Spacing.sm,
    marginTop: Spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  playerNoteText: {
    fontSize: 13,
    color: Colors.dark.textSecondary,
    flex: 1,
    lineHeight: 18,
  },

  // === JUNIOR ASSESSMENT STYLES ===
  juniorAssessCard: {
    marginTop: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1.5,
    borderColor: "#C8FF3D45",
    overflow: "hidden",
  },
  juniorAssessCardGradient: {
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.md,
    gap: Spacing.sm,
  },
  juniorAssessPriorResult: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    paddingBottom: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: "#C8FF3D20",
    marginBottom: Spacing.xs,
  },
  juniorAssessScore: {
    fontSize: FontSizes.lg,
    fontWeight: "800",
    color: "#C8FF3D",
    letterSpacing: -0.5,
  },
  juniorAssessDate: {
    fontSize: FontSizes.xs,
    color: Colors.dark.textMuted,
    flex: 1,
    textAlign: "right",
  },
  juniorAssessCardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  juniorAssessIconWrap: {
    width: 44,
    height: 44,
    borderRadius: BorderRadius.md,
    backgroundColor: "#C8FF3D18",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#C8FF3D30",
  },
  juniorAssessCardText: {
    flex: 1,
    gap: 2,
  },
  juniorAssessBtnText: {
    fontSize: FontSizes.md,
    fontWeight: "700",
    color: "#C8FF3D",
  },
  juniorAssessCardSub: {
    fontSize: FontSizes.xs,
    color: Colors.dark.textMuted,
    fontWeight: "500",
  },
  assessedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
  },
  assessedBadgeText: {
    fontSize: FontSizes.xs,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  ustaAssessedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
  },
  ustaAssessedBadgeText: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
});
