// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ota-update-sheet.tsx": () => import("../components/mockups/ota-update-sheet.tsx"),
  "./components/mockups/landing/LandingBoldAthletic.tsx": () => import("../components/mockups/landing/LandingBoldAthletic.tsx"),
  "./components/mockups/landing/LandingBrightAcademy.tsx": () => import("../components/mockups/landing/LandingBrightAcademy.tsx"),
  "./components/mockups/landing/LandingDarkElite.tsx": () => import("../components/mockups/landing/LandingDarkElite.tsx"),
  "./components/mockups/coach-dashboard/CleanCommand.tsx": () => import("../components/mockups/coach-dashboard/CleanCommand.tsx"),
  "./components/mockups/coach-dashboard/CoachCockpit.tsx": () => import("../components/mockups/coach-dashboard/CoachCockpit.tsx"),
  "./components/mockups/coach-dashboard/LiveCourt.tsx": () => import("../components/mockups/coach-dashboard/LiveCourt.tsx"),
  "./components/mockups/proplayer-collapse/VariantA.tsx": () => import("../components/mockups/proplayer-collapse/VariantA.tsx"),
  "./components/mockups/proplayer-collapse/VariantB.tsx": () => import("../components/mockups/proplayer-collapse/VariantB.tsx"),
  "./components/mockups/proplayer-collapse/VariantC.tsx": () => import("../components/mockups/proplayer-collapse/VariantC.tsx"),
  "./components/mockups/play-redesign/VariantCleanup.tsx": () => import("../components/mockups/play-redesign/VariantCleanup.tsx"),
  "./components/mockups/play-redesign/VariantHubTabs.tsx": () => import("../components/mockups/play-redesign/VariantHubTabs.tsx"),
  "./components/mockups/play-redesign/VariantSmartFeed.tsx": () => import("../components/mockups/play-redesign/VariantSmartFeed.tsx")
};
