import { StyleSheet, Platform } from 'react-native';
import { Colors, Spacing, BorderRadius, Typography } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.lg,
    paddingTop: Spacing.sm,
  },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  headerIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.dark.primary + "25",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.dark.primary + "50",
  },
  title: {
    fontSize: 14,
    fontWeight: "800",
    color: Colors.dark.text,
    letterSpacing: 2,
  },
  hudHeader: {
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.md,
  },
  headerPanel: {
    overflow: "visible",
  },
  hudHeaderContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.md,
  },
  hudSigilContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  hudTitleContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  hudTitleGlow: {
    position: "absolute",
    width: 120,
    height: 40,
    backgroundColor: Colors.dark.primary + "30",
    borderRadius: 20,
    top: -5,
  },
  hudTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: Colors.dark.text,
    letterSpacing: 4,
    textShadowColor: Colors.dark.primary,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  hudSubtitle: {
    fontSize: 10,
    fontWeight: "600",
    color: Colors.dark.primary,
    letterSpacing: 2,
    marginTop: 2,
  },
  hudStatusContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    backgroundColor: Colors.dark.primary + "20",
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "40",
  },
  hudStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.dark.primary,
  },
  hudStatusText: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.dark.primary,
    letterSpacing: 1,
  },
  gameHeader: {
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.xs,
    position: 'relative',
  },
  gameHeaderGradient: {
    ...StyleSheet.absoluteFillObject,
    borderBottomLeftRadius: BorderRadius.lg,
    borderBottomRightRadius: BorderRadius.lg,
  },
  gameHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  levelBadgeContainer: {
    alignItems: 'center',
  },
  levelBadge: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  levelNumber: {
    fontSize: 20,
    fontWeight: '900',
    color: Colors.dark.buttonText,
  },
  levelLabelContainer: {
    marginTop: 2,
  },
  levelLabel: {
    fontSize: 8,
    fontWeight: '700',
    color: Colors.dark.primary,
    letterSpacing: 1,
  },
  gameHeaderCenter: {
    flex: 1,
  },
  gameHeaderTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: Colors.dark.text,
    letterSpacing: 2,
    marginBottom: 4,
  },
  xpBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  xpBarBackground: {
    flex: 1,
    height: 6,
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: 3,
    overflow: 'hidden',
  },
  xpBarFill: {
    height: '100%',
    backgroundColor: Colors.dark.primary,
    borderRadius: 3,
  },
  xpText: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.dark.xpCyan,
  },
  gameHeaderStats: {
    alignItems: 'flex-end',
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: 18,
    fontWeight: '800',
    color: Colors.dark.text,
  },
  statLabel: {
    fontSize: 9,
    fontWeight: '600',
    color: Colors.dark.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  headerDivider: {
    height: 1,
    backgroundColor: Colors.dark.primary + '20',
    marginTop: Spacing.md,
    marginHorizontal: -Spacing.md,
  },
  compactHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.primary + '20',
  },
  compactHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  compactLevelBadge: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: Colors.dark.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compactLevelText: {
    fontSize: 16,
    fontWeight: '800',
    color: Colors.dark.buttonText,
  },
  compactTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.dark.text,
    letterSpacing: 1,
  },
  compactXpRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    marginTop: 2,
  },
  compactXpBar: {
    width: 80,
    height: 4,
    backgroundColor: Colors.dark.backgroundTertiary,
    borderRadius: 2,
    overflow: 'hidden',
  },
  compactXpFill: {
    height: '100%',
    backgroundColor: Colors.dark.primary,
    borderRadius: 2,
  },
  compactXpText: {
    fontSize: 10,
    fontWeight: '600',
    color: Colors.dark.xpCyan,
  },
  compactHeaderRight: {
    alignItems: 'flex-end',
  },
  compactStatValue: {
    fontSize: 16,
    fontWeight: '800',
    color: Colors.dark.text,
  },
  compactStatLabel: {
    fontSize: 8,
    fontWeight: '600',
    color: Colors.dark.textMuted,
    letterSpacing: 0.5,
  },
  pillTabContainer: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.backgroundSecondary,
  },
  pillTabScroll: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    gap: Spacing.xs,
  },
  pillTab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: Spacing.md,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderWidth: 1,
    borderColor: Colors.dark.border,
  },
  pillTabActive: {
    backgroundColor: Colors.dark.backgroundTertiary,
    borderColor: Colors.dark.primary + "40",
  },
  pillTabIconContainer: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pillTabText: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.dark.textMuted,
  },
  pillTabTextActive: {
    color: Colors.dark.text,
    fontWeight: '700',
  },
  glowToolsContainer: {
    paddingVertical: Spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  glowToolsScroll: {
    paddingHorizontal: Spacing.md,
    gap: Spacing.sm,
  },
  glowToolButton: {
    alignItems: 'center',
    gap: 4,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.sm,
  },
  glowToolButtonActive: {
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  glowToolIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  glowToolLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: Colors.dark.textMuted,
  },
  feedbackHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.sm,
  },
  feedbackSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.dark.text,
  },
  feedbackSectionSubtitle: {
    fontSize: 12,
    color: Colors.dark.textMuted,
  },
  feedbackCountBadge: {
    backgroundColor: Colors.dark.gold + '20',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: 12,
  },
  feedbackCountText: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.dark.gold,
  },
  feedbackGroup: {
    paddingHorizontal: Spacing.md,
    marginBottom: Spacing.md,
  },
  feedbackGroupTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.dark.textMuted,
    marginBottom: Spacing.sm,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  feedbackSessionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.dark.gold + '30',
  },
  feedbackSessionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    flex: 1,
  },
  feedbackSessionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.dark.gold + '20',
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedbackSessionType: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.dark.text,
  },
  feedbackSessionTime: {
    fontSize: 12,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  feedbackSessionRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  pendingBadge: {
    backgroundColor: Colors.dark.gold + '20',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: 8,
  },
  pendingBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: Colors.dark.gold,
  },
  periodToggleRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
    gap: Spacing.xs,
  },
  periodToggleButton: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderWidth: 1,
    borderColor: Colors.dark.border,
  },
  periodToggleButtonActive: {
    backgroundColor: Colors.dark.gold + '20',
    borderColor: Colors.dark.gold,
  },
  periodToggleText: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.dark.textMuted,
  },
  periodToggleTextActive: {
    color: Colors.dark.gold,
  },
  weekNavHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
  },
  weekNavArrow: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.dark.backgroundSecondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weekNavCenter: {
    flex: 1,
    alignItems: 'center',
    gap: Spacing.xs,
  },
  weekNavLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.dark.text,
  },
  todayButton: {
    backgroundColor: Colors.dark.primary + '20',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: 12,
  },
  todayButtonText: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.dark.primary,
  },
  dayAccordionContainer: {
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
  },
  dayAccordion: {
    marginBottom: Spacing.md,
  },
  dayAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.dark.backgroundSecondary,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.dark.gold + '30',
  },
  dayAccordionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  dayAccordionRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  dayAccordionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.dark.text,
  },
  dayAccordionCount: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.dark.gold,
  },
  dayAccordionLabel: {
    fontSize: 12,
    color: Colors.dark.textMuted,
  },
  dayFeedbackBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.dark.gold + '20',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    borderRadius: 10,
    marginRight: Spacing.sm,
  },
  dayFeedbackBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.dark.gold,
  },
  dayAccordionContent: {
    paddingTop: Spacing.sm,
    paddingLeft: Spacing.md,
  },
  daySessionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.sm,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    borderLeftWidth: 3,
    borderLeftColor: Colors.dark.primary,
  },
  daySessionCardNeedsFeedback: {
    borderColor: Colors.dark.gold + '40',
    borderWidth: 1,
    borderLeftWidth: 3,
  },
  daySessionLeft: {
    flex: 1,
  },
  daySessionTime: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.dark.primary,
  },
  daySessionType: {
    fontSize: 13,
    fontWeight: '500',
    color: Colors.dark.text,
    marginTop: 2,
  },
  daySessionDuration: {
    fontSize: 11,
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  daySessionRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  richSessionCard: {
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.dark.border,
    overflow: 'hidden',
  },
  richSessionCardNeedsFeedback: {
    borderColor: Colors.dark.gold + '50',
    backgroundColor: Colors.dark.gold + '08',
  },
  richSessionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.border,
  },
  richSessionTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  richSessionTimeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: 6,
  },
  richSessionTimeText: {
    fontSize: 13,
    fontWeight: '700',
  },
  richSessionTypeBadge: {
    backgroundColor: Colors.dark.backgroundTertiary,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    borderRadius: 4,
  },
  richSessionTypeText: {
    fontSize: 11,
    fontWeight: '600',
    color: Colors.dark.textMuted,
  },
  richSessionDuration: {
    fontSize: 11,
    color: Colors.dark.textMuted,
  },
  sessionDateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: Colors.dark.xpCyan + '15',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 'auto',
  },
  sessionDateText: {
    fontSize: 10,
    fontWeight: '600',
    color: Colors.dark.xpCyan,
  },
  ballLevelBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
  },
  ballLevelDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  ballLevelText: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  richSessionBody: {
    padding: Spacing.md,
  },
  richSessionPlayersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  playerAvatarStack: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  playerAvatarCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Colors.dark.primary + '30',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: Colors.dark.backgroundSecondary,
  },
  playerAvatarText: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.dark.primary,
  },
  playerAvatarMore: {
    backgroundColor: Colors.dark.backgroundTertiary,
  },
  playerAvatarMoreText: {
    fontSize: 10,
    fontWeight: '600',
    color: Colors.dark.textMuted,
  },
  playerNamesContainer: {
    flex: 1,
  },
  playerNamesText: {
    fontSize: 13,
    fontWeight: '500',
    color: Colors.dark.text,
  },
  richSessionFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: Spacing.sm,
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.dark.border + '50',
  },
  xpRewardBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.dark.gold + '20',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: 6,
  },
  xpRewardText: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.dark.gold,
  },
  richCompletedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  richCompletedText: {
    fontSize: 12,
    fontWeight: '500',
    color: Colors.dark.primary,
  },
  feedbackActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  feedbackActionText: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.dark.gold,
  },
  gameTabBar: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    gap: Spacing.sm,
  },
  gameTab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderWidth: 1,
    borderColor: 'transparent',
    position: 'relative',
    overflow: 'hidden',
  },
  gameTabActive: {
    borderColor: Colors.dark.primary + '50',
    backgroundColor: Colors.dark.backgroundSecondary,
  },
  gameTabText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.dark.textMuted,
  },
  gameTabTextActive: {
    color: Colors.dark.primary,
    fontWeight: '700',
  },
  gameTabIndicator: {
    position: 'absolute',
    bottom: 0,
    left: Spacing.sm,
    right: Spacing.sm,
    height: 2,
    backgroundColor: Colors.dark.primary,
    borderRadius: 1,
  },
  neoTabBar: {
    flexDirection: "row",
    marginHorizontal: Spacing.md,
    marginBottom: Spacing.lg,
    gap: Spacing.sm,
  },
  neoTabWrapper: {
    flex: 1,
    position: "relative",
  },
  neoTabUnderglow: {
    position: "absolute",
    bottom: -4,
    left: 8,
    right: 8,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.dark.primary,
  },
  neoTab: {
    overflow: "visible",
  },
  neoTabContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.sm,
    gap: Spacing.xs,
  },
  neoTabText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.dark.textMuted,
    letterSpacing: 0.5,
  },
  neoTabTextActive: {
    color: Colors.dark.primary,
    fontWeight: "700",
  },
  neoPeriodTab: {
    marginRight: Spacing.sm,
    minWidth: 80,
  },
  neoPeriodContent: {
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  neoPeriodText: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.dark.textMuted,
    letterSpacing: 0.5,
  },
  neoPeriodTextActive: {
    color: Colors.dark.primary,
    fontWeight: "700",
  },
  neoStatusRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
    marginBottom: Spacing.lg,
  },
  neoStatusWrapper: {
    marginBottom: Spacing.xs,
  },
  neoStatusChip: {
    minWidth: 70,
  },
  neoStatusContent: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    gap: Spacing.xs,
  },
  neoStatusText: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.dark.textMuted,
    letterSpacing: 0.3,
  },
  neoStatusBadge: {
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.dark.backgroundRoot,
    borderWidth: 1,
    borderColor: Colors.dark.backgroundTertiary,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  neoStatusBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.dark.textMuted,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  sectionTitleAccent: {
    width: 4,
    height: 20,
    backgroundColor: Colors.dark.primary,
    borderRadius: 2,
  },
  neoEmptyCard: {
    marginBottom: Spacing.lg,
  },
  neoEmptyContent: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.xl,
    paddingHorizontal: Spacing.lg,
    gap: Spacing.md,
  },
  neoEmptyText: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.dark.text,
    textAlign: "center",
    marginTop: Spacing.sm,
  },
  neoEmptySubtext: {
    fontSize: 14,
    color: Colors.dark.textMuted,
    textAlign: "center",
  },
  neoSessionWrapper: {
    marginBottom: Spacing.md,
  },
  neoSessionCard: {
    overflow: "visible",
  },
  neoSessionContent: {
    flexDirection: "row",
    alignItems: "center",
    padding: Spacing.md,
    gap: Spacing.md,
  },
  neoSessionTimeBadge: {
    backgroundColor: Colors.dark.backgroundRoot,
    borderWidth: 2,
    borderRadius: BorderRadius.sm,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    alignItems: "center",
    minWidth: 60,
  },
  neoSessionTimeText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.dark.text,
    letterSpacing: 0.5,
  },
  neoSessionDuration: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.dark.textMuted,
    marginTop: 2,
  },
  neoSessionInfo: {
    flex: 1,
  },
  neoSessionType: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.dark.text,
    letterSpacing: 1,
    marginBottom: 4,
  },
  neoSessionDate: {
    fontSize: 11,
    color: Colors.dark.textMuted,
    marginBottom: 6,
  },
  neoSessionBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginTop: 4,
  },
  neoPendingBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.gold + "15",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.xs,
    borderWidth: 1,
  },
  neoPendingText: {
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  neoXpBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: Colors.dark.gold + "25",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.xs,
  },
  neoXpText: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.dark.gold,
  },
  neoDoneBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.primary + "15",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.xs,
    borderWidth: 1,
  },
  neoDoneText: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.dark.primary,
    letterSpacing: 0.3,
  },
  neoSessionArrow: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.dark.backgroundRoot,
    alignItems: "center",
    justifyContent: "center",
  },
  tabBar: {
    flexDirection: "row",
    marginHorizontal: Spacing.lg,
    backgroundColor: `${Colors.dark.primary}10`,
    borderRadius: BorderRadius.xl,
    padding: Spacing.xs,
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: `${Colors.dark.primary}20`,
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.lg,
    gap: Spacing.sm,
  },
  tabActive: {
    backgroundColor: Colors.dark.primary,
    shadowColor: Colors.dark.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  tabText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.textMuted,
    fontWeight: "500",
  },
  tabTextActive: {
    color: Colors.dark.buttonText,
    fontWeight: "700",
  },
  content: {
    flex: 1,
    paddingHorizontal: Spacing.lg,
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  periodFilterContainer: {
    marginBottom: Spacing.lg,
    marginHorizontal: -Spacing.lg,
  },
  periodFilterContent: {
    paddingHorizontal: Spacing.lg,
    gap: Spacing.sm,
  },
  periodTab: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "40",
  },
  periodTabActive: {
    backgroundColor: Colors.dark.primary,
    borderColor: Colors.dark.primary,
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 10,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  periodTabText: {
    fontSize: 12,
    color: Colors.dark.textMuted,
    fontWeight: "500",
    letterSpacing: 0.2,
  },
  periodTabTextActive: {
    color: Colors.dark.buttonText,
    fontWeight: "600",
  },
  statusFilterRow: {
    flexDirection: "row",
    gap: Spacing.xs,
    marginBottom: Spacing.md,
    flexWrap: "wrap",
  },
  statusChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "20",
  },
  statusChipActive: {
    borderColor: Colors.dark.primary + "50",
  },
  statusChipComplete: {
    backgroundColor: Colors.dark.primary + "15",
    borderColor: Colors.dark.primary,
  },
  statusChipOpen: {
    backgroundColor: "#F39C12" + "15",
    borderColor: "#F39C12",
  },
  statusChipPending: {
    backgroundColor: Colors.dark.xpCyan + "15",
    borderColor: Colors.dark.xpCyan,
  },
  statusChipText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    fontWeight: "500",
  },
  statusChipTextActive: {
    fontWeight: "600",
  },
  statusCountBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: Colors.dark.backgroundRoot,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  statusCountBadgeActive: {
    backgroundColor: "rgba(255,255,255,0.2)",
  },
  statusCountText: {
    fontSize: 10,
    color: Colors.dark.tabIconDefault,
    fontWeight: "600",
  },
  statusCountTextActive: {
    color: Colors.dark.text,
  },
  xpRewardBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.dark.gold + "15",
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.dark.gold + "30",
  },
  xpRewardLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    flex: 1,
  },
  xpRewardTextContainer: {
    flex: 1,
  },
  xpRewardTitle: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
    fontWeight: "600",
  },
  xpRewardSubtitle: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.gold,
    marginTop: 2,
  },
  xpRewardBadgeText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.buttonText,
    fontWeight: "700",
  },
  
  // Epic XP Mission Banner
  xpMissionBanner: {
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.lg,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.dark.gold + "40",
    overflow: "hidden",
  },
  xpMissionGlowEdge: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: Colors.dark.gold,
  },
  xpMissionContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: Spacing.md,
    paddingTop: Spacing.md + 2,
  },
  xpMissionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    flex: 1,
  },
  xpMissionIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.dark.gold + "25",
    alignItems: "center",
    justifyContent: "center",
  },
  xpMissionTextContainer: {
    flex: 1,
  },
  xpMissionLabel: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.gold,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  xpMissionStats: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
    fontWeight: "500",
    marginTop: 2,
  },
  xpMissionButton: {
    borderRadius: BorderRadius.md,
    overflow: "hidden",
  },
  xpMissionButtonGradient: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
  },
  xpMissionButtonText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.buttonText,
    fontWeight: "700",
  },

  feedbackRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  sessionXpBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.gold + "20",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
  },
  sessionXpText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.gold,
    fontWeight: "600",
  },
  sectionTitle: {
    ...Typography.h3,
    color: Colors.dark.text,
    marginBottom: Spacing.md,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    fontWeight: "700",
  },
  emptyCard: {
    flex: 1,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.xl,
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.dark.primary + "45",
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  emptyText: {
    ...Typography.h4,
    color: Colors.dark.text,
  },
  emptySubtext: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
    textAlign: "center",
  },
  sessionCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(20, 20, 20, 0.95)",
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    gap: Spacing.md,
    borderWidth: 2,
    borderColor: Colors.dark.primary + "60",
    ...Platform.select({
      ios: {
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 12,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  sessionTime: {
    alignItems: "center",
    minWidth: 50,
  },
  sessionTimeText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  sessionDuration: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  sessionInfo: {
    flex: 1,
    gap: Spacing.xs,
  },
  sessionType: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
  },
  doneBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 4,
  },
  doneText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.primary,
  },
  feedbackForm: {
    flex: 1,
    paddingHorizontal: Spacing.lg,
  },
  backRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.lg,
  },
  backText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
  },
  feedbackTitle: {
    ...Typography.h2,
    color: Colors.dark.text,
  },
  feedbackTime: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  feedbackSection: {
    marginBottom: Spacing.xl,
  },
  feedbackLabel: {
    ...Typography.h4,
    color: Colors.dark.text,
    marginBottom: Spacing.sm,
  },
  feedbackLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.sm,
  },
  quickActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  applyAllButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.dark.backgroundSecondary,
  },
  applyAllText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  asExpectedButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.dark.xpCyan + "40",
    borderStyle: "dashed",
    marginBottom: Spacing.sm,
  },
  asExpectedText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.xpCyan,
  },
  intensityRow: {
    flexDirection: "row",
    gap: Spacing.sm,
  },
  intensityButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.xs,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: "transparent",
  },
  intensityDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  intensityText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  tagsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
  },
  tagChip: {
    backgroundColor: Colors.dark.backgroundSecondary,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: "transparent",
  },
  tagChipActive: {
    backgroundColor: Colors.dark.primary + "20",
    borderColor: Colors.dark.primary,
  },
  tagText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  tagTextActive: {
    color: Colors.dark.primary,
    fontWeight: "500",
  },
  noteInput: {
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
    minHeight: 80,
    textAlignVertical: "top",
  },
  playerFeedbackCard: {
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    marginTop: Spacing.sm,
    gap: Spacing.sm,
  },
  playerFeedbackHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  playerFeedbackHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  playerFeedbackName: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  playerFeedbackRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  playerFeedbackLabel: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  trendButtons: {
    flexDirection: "row",
    gap: Spacing.xs,
  },
  trendButton: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.dark.disabled,
    alignItems: "center",
    justifyContent: "center",
  },
  effortButton: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.dark.disabled,
    alignItems: "center",
    justifyContent: "center",
  },
  effortButtonText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  playerNoteInput: {
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.sm,
    padding: Spacing.sm,
    fontSize: Typography.small.fontSize,
    color: Colors.dark.text,
    marginTop: Spacing.xs,
  },
  skillChipsSection: {
    marginTop: Spacing.sm,
    gap: Spacing.xs,
  },
  skillGroupContainer: {
    marginBottom: Spacing.xs,
  },
  skillGroupHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: Spacing.xs,
  },
  skillGroupHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  skillGroupLabel: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    fontWeight: "500" as const,
  },
  skillGroupBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    marginLeft: Spacing.xs,
    paddingHorizontal: Spacing.xs,
    paddingVertical: 2,
    backgroundColor: Colors.dark.disabled + "30",
    borderRadius: BorderRadius.xs,
  },
  skillGroupBadgeText: {
    fontSize: Typography.small.fontSize - 2,
    color: Colors.dark.tabIconDefault,
  },
  skillChipsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.xs,
    marginTop: Spacing.xs,
  },
  skillChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.dark.disabled,
    backgroundColor: Colors.dark.backgroundRoot,
  },
  skillChipFocused: {
    borderColor: Colors.dark.gold + "60",
    backgroundColor: Colors.dark.gold + "10",
  },
  skillChipText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  skillWarning: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginTop: Spacing.sm,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    backgroundColor: Colors.dark.orange + "15",
    borderRadius: BorderRadius.sm,
  },
  skillWarningText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.orange,
  },
  skillProgressSummary: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
    paddingHorizontal: Spacing.sm,
  },
  skillProgressBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.sm,
  },
  skillProgressBadgeText: {
    fontSize: Typography.small.fontSize,
  },
  headerProgressBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    paddingHorizontal: Spacing.xs,
    paddingVertical: 2,
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.xs,
    marginRight: Spacing.xs,
  },
  headerProgressText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "600",
  },
  focusLinkHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginTop: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.sm,
  },
  focusLinkText: {
    fontSize: Typography.small.fontSize - 1,
    color: Colors.dark.tabIconDefault,
    fontStyle: "italic",
    flex: 1,
  },
  skillSelectorContainer: {
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.sm,
    marginTop: Spacing.xs,
    borderWidth: 1,
    borderColor: Colors.dark.disabled + "40",
  },
  skillSelectorHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.sm,
  },
  skillSelectorTitle: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.text,
    flex: 1,
  },
  skillSelectorChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.xs,
  },
  skillSelectorChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.dark.disabled,
    backgroundColor: Colors.dark.backgroundSecondary,
  },
  skillSelectorChipText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  quickSignalsSection: {
    marginTop: Spacing.sm,
    gap: Spacing.xs,
  },
  quickSignalsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.xs,
    marginTop: Spacing.xs,
  },
  quickSignalChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.dark.disabled,
    backgroundColor: Colors.dark.backgroundRoot,
  },
  quickSignalChipActive: {
    borderColor: Colors.dark.primary,
    backgroundColor: Colors.dark.primary + "15",
  },
  quickSignalText: {
    fontSize: Typography.small.fontSize - 1,
    color: Colors.dark.tabIconDefault,
  },
  quickSignalTextActive: {
    color: Colors.dark.primary,
  },
  issueToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginTop: Spacing.sm,
    paddingVertical: Spacing.xs,
  },
  issueToggleText: {
    fontSize: Typography.small.fontSize - 1,
    color: Colors.dark.tabIconDefault,
  },
  issueOptions: {
    flexDirection: "row",
    gap: Spacing.xs,
    marginTop: Spacing.xs,
  },
  issueChip: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.dark.disabled,
    backgroundColor: Colors.dark.backgroundRoot,
  },
  issueChipActive: {
    borderColor: Colors.dark.error,
    backgroundColor: Colors.dark.error + "15",
  },
  issueChipText: {
    fontSize: Typography.small.fontSize - 1,
    color: Colors.dark.tabIconDefault,
  },
  issueChipTextActive: {
    color: Colors.dark.error,
  },
  domainPreviewSection: {
    marginTop: Spacing.sm,
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.dark.disabled + "30",
  },
  domainPreviewLabel: {
    fontSize: Typography.small.fontSize - 1,
    color: Colors.dark.tabIconDefault,
    marginBottom: Spacing.xs,
  },
  domainPreviewGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.xs,
  },
  domainPreviewChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    paddingHorizontal: Spacing.xs,
    paddingVertical: 2,
    borderRadius: BorderRadius.xs,
    backgroundColor: Colors.dark.backgroundRoot,
  },
  domainPreviewUp: {
    backgroundColor: Colors.dark.primary + "15",
  },
  domainPreviewDown: {
    backgroundColor: Colors.dark.error + "15",
  },
  domainPreviewText: {
    fontSize: Typography.small.fontSize - 2,
    color: Colors.dark.tabIconDefault,
  },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    backgroundColor: Colors.dark.primary,
    borderRadius: BorderRadius.md,
    paddingVertical: Spacing.md,
    marginTop: Spacing.lg,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.buttonText,
  },
  successOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Colors.dark.backgroundRoot + "F5",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  successContent: {
    alignItems: "center",
    gap: Spacing.md,
  },
  successText: {
    ...Typography.h3,
    color: Colors.dark.primary,
    fontWeight: "600",
  },
  successSubtext: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  createTemplateButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginTop: Spacing.md,
  },
  createTemplateText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.primary,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: Spacing.md,
  },
  loadingText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  sectionSubtitle: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    marginBottom: Spacing.md,
    marginHorizontal: Spacing.lg,
  },
  progressCard: {
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.md,
  },
  progressCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
    marginBottom: Spacing.md,
  },
  playerAvatarSmall: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.dark.primary + "30",
    alignItems: "center",
    justifyContent: "center",
  },
  playerInitialSmall: {
    fontSize: Typography.h4.fontSize,
    fontWeight: "600",
    color: Colors.dark.primary,
  },
  progressPlayerInfo: {
    flex: 1,
  },
  progressPlayerName: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  progressMeta: {
    flexDirection: "row",
    gap: Spacing.sm,
    marginTop: 2,
  },
  levelDotSmall: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  levelBadgeText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.tabIconDefault,
    textTransform: "capitalize",
  },
  notesBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  notesBadgeText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  xpBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "rgba(255, 193, 7, 0.15)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
  },
  xpBadgeText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "600",
    color: Colors.dark.gold,
  },
  skillGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
  },
  skillItem: {
    width: "31%",
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.sm,
  },
  skillHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 4,
  },
  skillLabel: {
    fontSize: 10,
    color: Colors.dark.tabIconDefault,
  },
  skillRating: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  ratingValue: {
    fontSize: Typography.h4.fontSize,
    fontWeight: "700",
  },
  noRating: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.textMuted,
  },
  noProgressCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
  },
  noProgressText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.textMuted,
  },
  recentNoteCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: Spacing.sm,
    marginTop: Spacing.sm,
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.dark.disabled,
  },
  recentNoteText: {
    flex: 1,
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    fontStyle: "italic",
  },
  // Progress Engine V2 Styles
  playerDetailHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.lg,
    marginBottom: Spacing.xl,
    paddingHorizontal: Spacing.lg,
  },
  playerAvatarLarge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: Colors.dark.primary + "30",
    alignItems: "center",
    justifyContent: "center",
  },
  playerInitialLarge: {
    fontSize: 28,
    fontWeight: "700",
    color: Colors.dark.primary,
  },
  playerDetailInfo: {
    flex: 1,
  },
  playerDetailName: {
    ...Typography.h2,
    color: Colors.dark.text,
  },
  playerDetailMeta: {
    flexDirection: "row",
    gap: Spacing.sm,
    marginTop: Spacing.xs,
  },
  levelBadgeLarge: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
  },
  levelDotLarge: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  levelBadgeTextLarge: {
    fontSize: Typography.small.fontSize,
    fontWeight: "600",
  },
  xpCard: {
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.xl,
  },
  xpHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  xpTotal: {
    ...Typography.h2,
    color: Colors.dark.gold,
  },
  xpHistory: {
    marginTop: Spacing.md,
    paddingTop: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: Colors.dark.disabled,
  },
  xpHistoryTitle: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    marginBottom: Spacing.sm,
  },
  xpTransaction: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  xpAmount: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.primary,
    minWidth: 40,
  },
  xpSource: {
    flex: 1,
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  domainGrid: {
    gap: Spacing.md,
    paddingHorizontal: Spacing.lg,
  },
  domainCard: {
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
  },
  domainHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  domainName: {
    flex: 1,
    ...Typography.h4,
    color: Colors.dark.text,
  },
  progressBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  progressBarBg: {
    flex: 1,
    height: 8,
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: 4,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: 4,
  },
  progressValue: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    minWidth: 40,
    textAlign: "right",
  },
  domainMeta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  trendBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  trendText: {
    fontSize: Typography.small.fontSize,
    fontWeight: "500",
  },
  assessmentBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
  },
  assessmentText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "500",
  },
  assessmentToggle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.dark.backgroundSecondary,
    alignItems: "center",
    justifyContent: "center",
  },
  assessmentToggleActive: {
    backgroundColor: Colors.dark.gold + "30",
  },
  assessmentBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    backgroundColor: Colors.dark.gold + "15",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.md,
    borderRadius: BorderRadius.md,
  },
  assessmentBannerText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.gold,
  },
  assessmentOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.xs,
  },
  assessmentOption: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: Colors.dark.disabled,
  },
  assessmentOptionText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "500",
  },
  saveAssessmentsButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    backgroundColor: Colors.dark.gold,
    borderRadius: BorderRadius.md,
    paddingVertical: Spacing.md,
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.lg,
  },
  saveAssessmentsText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.buttonText,
  },
  momentumRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: Spacing.sm,
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.dark.backgroundRoot,
  },
  momentumText: {
    fontSize: Typography.small.fontSize,
  },
  domainXpRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginTop: Spacing.xs,
    marginBottom: Spacing.xs,
  },
  domainXpBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: Colors.dark.gold + "20",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.xs,
  },
  domainXpText: {
    fontSize: 10,
    fontWeight: "600",
    color: Colors.dark.gold,
  },
  domainObsCount: {
    fontSize: 10,
    color: Colors.dark.tabIconDefault,
  },
  domainAvgDelta: {
    fontSize: 10,
    fontWeight: "500",
  },
  trendsContainer: {
    gap: Spacing.sm,
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.lg,
  },
  plansHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.md,
  },
  addTemplateButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.dark.primary + "20",
    alignItems: "center",
    justifyContent: "center",
  },
  templatesGrid: {
    gap: Spacing.md,
  },
  templateCard: {
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
  },
  templateHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  templateTypeIndicator: {
    width: 4,
    height: 24,
    borderRadius: 2,
  },
  templateName: {
    flex: 1,
    ...Typography.h4,
    color: Colors.dark.text,
  },
  templateMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  templateMetaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  templateMetaText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  templateTypeBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
  },
  templateTypeText: {
    fontSize: Typography.caption.fontSize,
    fontWeight: "500",
  },
  templateBallLevel: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginBottom: Spacing.sm,
  },
  templateBallText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  templateNotes: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    marginBottom: Spacing.sm,
  },
  templateActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.dark.backgroundRoot,
  },
  templateActionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.sm,
  },
  templateActionText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.primary,
    fontWeight: "500",
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "flex-end",
  },
  modalScrollContainer: {
    height: "85%",
    backgroundColor: Colors.dark.backgroundSecondary,
    borderTopLeftRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
  },
  modalScrollContent: {
    flexGrow: 1,
    padding: Spacing.lg,
    paddingBottom: 120,
  },
  modalContent: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: Spacing.lg,
  },
  modalTitle: {
    ...Typography.h3,
    color: Colors.dark.text,
  },
  modalField: {
    marginBottom: Spacing.md,
  },
  modalLabel: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    marginBottom: Spacing.xs,
  },
  modalInput: {
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    fontSize: Typography.body.fontSize,
    color: Colors.dark.text,
  },
  modalTextArea: {
    minHeight: 80,
    textAlignVertical: "top",
  },
  typeButtons: {
    flexDirection: "row",
    gap: Spacing.sm,
  },
  typeButton: {
    flex: 1,
    paddingVertical: Spacing.md,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: "transparent",
  },
  typeButtonActive: {
    backgroundColor: Colors.dark.primary + "20",
    borderColor: Colors.dark.primary,
  },
  typeButtonText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  typeButtonTextActive: {
    color: Colors.dark.primary,
    fontWeight: "600",
  },
  durationButtons: {
    flexDirection: "row",
    gap: Spacing.sm,
  },
  durationButton: {
    flex: 1,
    paddingVertical: Spacing.md,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: "transparent",
  },
  durationButtonActive: {
    backgroundColor: Colors.dark.xpCyan + "20",
    borderColor: Colors.dark.xpCyan,
  },
  durationButtonText: {
    fontSize: Typography.body.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  durationButtonTextActive: {
    color: Colors.dark.xpCyan,
    fontWeight: "600",
  },
  ballLevelButtons: {
    flexDirection: "row",
    gap: Spacing.sm,
  },
  ballLevelButton: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.dark.backgroundRoot,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.dark.disabled,
  },
  ballLevelButtonActive: {
    backgroundColor: Colors.dark.disabled + "20",
  },
  saveTemplateButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    backgroundColor: Colors.dark.primary,
    borderRadius: BorderRadius.md,
    paddingVertical: Spacing.md,
    marginTop: Spacing.md,
  },
  saveTemplateText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.buttonText,
  },

  // ============== CALM DESIGN STYLES ==============
  // Tab bar - simple pills
  calmTabBar: {
    flexDirection: "row",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  calmTab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.xs,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.dark.backgroundSecondary,
  },
  calmTabActive: {
    backgroundColor: Colors.dark.primary + "20",
  },
  calmTabText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    fontWeight: "500",
  },
  calmTabTextActive: {
    color: Colors.dark.primary,
  },

  // Period filter pills
  calmPeriodScroll: {
    flexGrow: 0,
    marginBottom: Spacing.sm,
  },
  calmPeriodContent: {
    paddingHorizontal: Spacing.lg,
    gap: Spacing.xs,
  },
  calmPeriodPill: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.dark.backgroundSecondary,
    marginRight: Spacing.xs,
  },
  calmPeriodPillActive: {
    backgroundColor: Colors.dark.primary + "20",
  },
  calmPeriodText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  calmPeriodTextActive: {
    color: Colors.dark.primary,
    fontWeight: "600",
  },

  // Status filter pills
  calmStatusScroll: {
    flexGrow: 0,
    marginBottom: Spacing.md,
  },
  calmStatusContent: {
    paddingHorizontal: Spacing.lg,
    gap: Spacing.xs,
  },
  calmStatusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderWidth: 1,
    borderColor: "transparent",
    marginRight: Spacing.xs,
  },
  calmStatusText: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
  },

  // Empty state
  calmEmptyCard: {
    alignItems: "center",
    padding: Spacing.xl,
    marginHorizontal: Spacing.lg,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.lg,
  },
  calmEmptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.dark.backgroundRoot,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.md,
  },
  calmEmptyText: {
    ...Typography.body,
    color: Colors.dark.text,
    textAlign: "center",
  },
  calmEmptySubtext: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    textAlign: "center",
    marginTop: Spacing.xs,
  },

  // Session cards
  calmSessionCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.sm,
  },
  calmSessionCardNeedsFeedback: {
    borderWidth: 1,
    borderColor: Colors.dark.gold + "40",
  },
  calmSessionTimeBadge: {
    alignItems: "center",
    minWidth: 50,
  },
  calmSessionTimeText: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  calmSessionDuration: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.tabIconDefault,
  },
  calmSessionInfo: {
    flex: 1,
  },
  calmSessionType: {
    fontSize: Typography.body.fontSize,
    fontWeight: "500",
    color: Colors.dark.text,
    marginBottom: 2,
  },
  calmSessionDate: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    marginBottom: 4,
  },
  calmSessionBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginTop: 4,
  },
  calmPendingBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  calmPendingText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.gold,
  },
  calmXpText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.gold,
    fontWeight: "600",
  },
  calmDoneBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  calmDoneText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.primary,
  },

  // Session Card V2 - Gaming Style with Type Colors
  sessionCardV2: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
    backgroundColor: Colors.dark.backgroundSecondary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.sm,
    borderLeftWidth: 3,
    borderLeftColor: Colors.dark.primary,
  },
  sessionCardV2NeedsFeedback: {
    borderWidth: 1,
    borderColor: Colors.dark.gold + "40",
    shadowColor: Colors.dark.gold,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  sessionTimeBadgeV2: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 56,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.xs,
    borderRadius: BorderRadius.md,
  },
  sessionTimeTextV2: {
    fontSize: Typography.body.fontSize,
    fontWeight: "700",
  },
  sessionDurationV2: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.tabIconDefault,
    marginTop: 2,
  },
  sessionInfoV2: {
    flex: 1,
  },
  sessionTypeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginBottom: 4,
  },
  sessionTypeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  sessionTypeV2: {
    fontSize: Typography.body.fontSize,
    fontWeight: "600",
    color: Colors.dark.text,
  },
  playerAvatarsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  playerAvatarMini: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.dark.backgroundRoot,
    borderWidth: 1,
    borderColor: Colors.dark.textMuted + "40",
    alignItems: "center",
    justifyContent: "center",
  },
  sessionTypeIndicator: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  playerCountText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.tabIconDefault,
    marginLeft: Spacing.sm,
  },
  sessionDateV2: {
    fontSize: Typography.small.fontSize,
    color: Colors.dark.tabIconDefault,
    marginBottom: 4,
  },
  sessionBadgeRowV2: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginTop: 4,
  },
  feedbackNeededBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.dark.gold + "15",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
  },
  feedbackNeededText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.gold,
    fontWeight: "500",
  },
  completedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  completedText: {
    fontSize: Typography.caption.fontSize,
    color: Colors.dark.primary,
  },
});
