/**
 * Drills Seed - Standardized Drill Library
 *
 * 16 structured drills across all stages covering key skill areas.
 * Sources: USTA Player Development, Tennis Australia, KNLTB, ITF, Glow methodology
 */

import { db } from "../db";
import { sql } from "drizzle-orm";

interface DrillEntry {
  id: string;
  name: string;
  skillArea: string;
  stageRange: string[];
  instruction: string;
  repRange: string;
  milestoneCriteria: string;
  source: string;
  category: string;
  difficulty: string;
  durationMinutes: number;
  description: string;
  steps: string[];
  tips: string;
  skillTags: string[];
}

export const DRILL_LIBRARY: DrillEntry[] = [
  {
    id: "DRILL_CROSSCOURT_RALLY",
    name: "Crosscourt Cooperative Rally",
    skillArea: "TECHNIQUE",
    stageRange: ["RED", "ORANGE"],
    instruction: "Player and coach rally crosscourt from the baseline. Emphasise unit turn before the ball bounces. Count consecutive balls in the crosscourt half.",
    repRange: "3 sets of 10 balls",
    milestoneCriteria: "10 consecutive crosscourt balls without error",
    source: "USTA",
    category: "Forehand",
    difficulty: "Beginner",
    durationMinutes: 15,
    description: "A cooperative rally drill designed to build consistency and directional control on the forehand side. Focus on unit turn and clean contact.",
    steps: [
      "Position both players at the baseline, one on each side.",
      "Begin a cooperative rally hitting crosscourt only.",
      "Emphasise unit turn before the ball bounces.",
      "Count consecutive successful crosscourt balls.",
      "Switch direction after each set of 10.",
    ],
    tips: "Focus on contact quality, not pace. Let the racket do the work with a relaxed grip.",
    skillTags: ["Consistency", "Direction Control", "Rally Building"],
  },
  {
    id: "DRILL_SPLIT_STEP_TIMING",
    name: "Split-Step Timing Gate",
    skillArea: "PHYSICAL",
    stageRange: ["RED", "ORANGE", "GREEN"],
    instruction: "Coach feeds from across the net. Player waits at baseline in ready position. The moment the coach's racket contacts, player split-steps then moves to the ball. Coach calls 'late', 'on time', or 'early' after each rep.",
    repRange: "20 feeds (2 sets of 10)",
    milestoneCriteria: "Split-step timed correctly on 7 of 10 consecutive feeds",
    source: "Tennis Australia",
    category: "Footwork",
    difficulty: "Beginner",
    durationMinutes: 15,
    description: "Master the split-step — the foundation of all court movement. This drill trains you to react at the exact moment of contact.",
    steps: [
      "Stand at the baseline in ready position.",
      "Watch the coach's racket closely.",
      "The moment the coach's racket contacts the ball, jump into a split-step.",
      "Land softly with feet shoulder-width apart, then push to the ball.",
      "Coach calls 'late', 'on time', or 'early' after each rep.",
    ],
    tips: "The split-step should land just as the opponent contacts the ball. Practice the timing without the ball first.",
    skillTags: ["Footwork", "Reaction Time", "Court Coverage"],
  },
  {
    id: "DRILL_10_BALL_SERVE_LADDER",
    name: "10-Ball Serve Ladder",
    skillArea: "SERVE",
    stageRange: ["RED", "ORANGE", "GREEN", "YELLOW"],
    instruction: "Serve 10 balls to each service box. Points: 1 pt = in the box, 2 pts = hits a target cone. Repeat across 3 rounds. Track score each round.",
    repRange: "10 serves per box, 3 rounds",
    milestoneCriteria: "Score improves each round; 7 of 10 serves in target box by round 3",
    source: "USTA",
    category: "Serve",
    difficulty: "Beginner",
    durationMinutes: 20,
    description: "A structured serve consistency drill with a scoring ladder to track progress. Targets both the deuce and ad service boxes.",
    steps: [
      "Place a target cone in each service box.",
      "Serve 10 balls to the deuce court. Score: 1 pt for in, 2 pts for hitting the cone.",
      "Record your round 1 score.",
      "Serve 10 to the ad court with the same scoring.",
      "Complete 3 rounds total, aiming to improve each round.",
    ],
    tips: "Consistency before pace. Focus on a repeatable toss before worrying about power.",
    skillTags: ["Serve Consistency", "Targeting", "Routine Building"],
  },
  {
    id: "DRILL_BLOCK_RETURN_DEEP_MIDDLE",
    name: "Block Return to Deep Middle",
    skillArea: "RETURN",
    stageRange: ["ORANGE", "GREEN", "YELLOW"],
    instruction: "Coach serves at 50-60% pace. Block return to a target cone at the deep centre baseline T. No redirecting — focus on contact quality, compact swing, and depth.",
    repRange: "3 sets of 8 returns",
    milestoneCriteria: "6 of 8 block returns land within 1 metre of the deep centre target",
    source: "KNLTB",
    category: "Backhand",
    difficulty: "Intermediate",
    durationMinutes: 15,
    description: "Train the block return — a compact, neutral return that buys time and resets the rally. Essential for handling big serves.",
    steps: [
      "Place a cone on the deep centre T of the baseline.",
      "Stand in return position.",
      "Coach serves at 50-60% pace.",
      "Use a compact backswing, meet the ball early, and drive through to the target.",
      "No attempt to redirect — focus purely on depth and middle.",
    ],
    tips: "Think 'catch and push' not 'swing'. The compact swing reduces timing errors on fast serves.",
    skillTags: ["Return", "Neutralising", "Compact Swing"],
  },
  {
    id: "DRILL_APPROACH_VOLLEY_SEQUENCE",
    name: "Approach + Volley Sequence",
    skillArea: "TACTICAL",
    stageRange: ["ORANGE", "GREEN", "YELLOW"],
    instruction: "Coach feeds a short ball to mid-court. Drive approach deep cross or down the line, close to the net. Coach lobs or passes. Volley away or recover and reset.",
    repRange: "4 sets of 5 sequences",
    milestoneCriteria: "Completes approach → close → volley/reset sequence 4 of 5 attempts",
    source: "Tennis Australia",
    category: "Net Play",
    difficulty: "Intermediate",
    durationMinutes: 20,
    description: "Build the approach-volley sequence that wins points. Read the short ball, attack, close the net, and finish.",
    steps: [
      "Start at the baseline.",
      "Coach feeds a mid-court short ball.",
      "Drive the approach shot deep cross or down the line.",
      "Split-step as you close to the net.",
      "Volley the lob or pass away, or recover if needed.",
    ],
    tips: "Choose your approach direction based on your stronger side. Approach down the line to close the angle.",
    skillTags: ["Net Play", "Approach Shot", "Volleys", "Tactical Patterns"],
  },
  {
    id: "DRILL_RESET_DRILL",
    name: "Defensive Reset Drill",
    skillArea: "MENTAL",
    stageRange: ["ORANGE", "GREEN", "YELLOW", "GLOW"],
    instruction: "Coach hammers pace balls from 2m inside the baseline. Player resets crosscourt low and deep. No winners. Count consecutive successful resets. After 5, play out the point.",
    repRange: "3 rounds of 5 defensive balls + 1 live point",
    milestoneCriteria: "5 consecutive defensive resets crosscourt, then wins or constructs the live point",
    source: "Glow",
    category: "Match Tactics",
    difficulty: "Intermediate",
    durationMinutes: 15,
    description: "Train your defensive mindset. When pushed wide or deep, the right response is a safe, low crosscourt reset — not a hero shot.",
    steps: [
      "Coach stands 2 metres inside the baseline.",
      "Coach feeds 5 pace balls at different spots around the player.",
      "Player's only job: reset crosscourt, low, deep.",
      "No winners attempted — surviving is the goal.",
      "After 5 resets, play out a live point normally.",
    ],
    tips: "Use heavy topspin on the reset to clear the net with margin and land deep. Stay balanced and breathe through the pressure.",
    skillTags: ["Defence", "Resilience", "Topspin", "Mental Strength"],
  },
  {
    id: "DRILL_OVERHEAD_CONTROL",
    name: "Overhead Control Ladder",
    skillArea: "TECHNIQUE",
    stageRange: ["GREEN", "YELLOW", "GLOW"],
    instruction: "Coach lobs from service line. Player reads the lob, moves back, and hits an overhead. Zone 1 = low lob, Zone 2 = medium, Zone 3 = deep near baseline. Land overhead in open court target.",
    repRange: "3 zones × 5 overheads = 15 total",
    milestoneCriteria: "3 of 5 overheads land in the designated open-court target zone at each level",
    source: "USTA",
    category: "Net Play",
    difficulty: "Intermediate",
    durationMinutes: 20,
    description: "Build confidence and control on the overhead smash. This ladder drill progressively challenges lob depth and placement.",
    steps: [
      "Start at the T.",
      "Coach lobs from the service line (Zone 1 — low lob).",
      "Read the lob early, pivot and move back.",
      "Hit the overhead into the open court target.",
      "Progress to Zone 2 (medium) and Zone 3 (deep) after success.",
    ],
    tips: "Get sideways and point your non-racket arm at the ball. Don't wait — attack the lob early whenever possible.",
    skillTags: ["Overhead", "Net Play", "Reading Lobs", "Footwork"],
  },
  {
    id: "DRILL_TOPSPIN_NET_CLEARANCE",
    name: "Topspin Net Clearance Marker",
    skillArea: "TECHNIQUE",
    stageRange: ["GREEN", "YELLOW", "GLOW"],
    instruction: "Mark 40cm above the net. Hit 10 crosscourt forehands, clearing the marker with topspin. Coach tracks clearances, nets, and balls long.",
    repRange: "3 sets of 10 forehands",
    milestoneCriteria: "8 of 10 balls clear the 40cm marker and land in the crosscourt baseline zone",
    source: "Tennis Australia",
    category: "Forehand",
    difficulty: "Intermediate",
    durationMinutes: 15,
    description: "Use a visual net marker to develop consistent topspin forehand clearance. The marker creates immediate biofeedback on your swing path.",
    steps: [
      "Hang a rope or place a cone 40cm above the centre of the net.",
      "Rally crosscourt forehands with the coach.",
      "Goal: every ball must clear the 40cm marker with topspin.",
      "Coach tracks: clearances, nets, and balls hit long.",
      "Complete 3 sets of 10.",
    ],
    tips: "Think 'low to high' on your swing path. The topspin creates safe net clearance while pulling the ball down into the court.",
    skillTags: ["Topspin", "Forehand", "Net Clearance", "Consistency"],
  },
  {
    id: "DRILL_ITF_FITNESS_PROTOCOL",
    name: "ITF Monthly Fitness Test Protocol",
    skillArea: "PHYSICAL",
    stageRange: ["YELLOW", "GLOW"],
    instruction: "Run 4 standardised tests: (1) 20m sprint x5 with 20s recovery, (2) Spider run x3, (3) Side shuffle baseline-to-net x8, (4) Jump-rope 90s. Record times and counts monthly.",
    repRange: "1 session (~25 min total)",
    milestoneCriteria: "Personal best on at least 2 of 4 tests vs. previous month",
    source: "ITF",
    category: "Fitness & Conditioning",
    difficulty: "Advanced",
    durationMinutes: 30,
    description: "A standardised monthly fitness test to track athletic development over time. Run all four tests, record your results, and compare each month.",
    steps: [
      "Warm up with 5 min light jog and dynamic stretches.",
      "Test 1: 20m sprint x5 with 20s recovery between each. Record fastest time.",
      "Test 2: Spider run x3. Touch all 5 court markers as fast as possible.",
      "Test 3: Side shuffle baseline-to-net-and-back x8. Record total time.",
      "Test 4: Jump rope 90s for foot speed. Count total jumps.",
    ],
    tips: "Run this test fresh — not after a hard session. Your monthly improvement curve tells you more than any single result.",
    skillTags: ["Speed", "Agility", "Endurance", "Fitness Benchmark"],
  },
  {
    id: "DRILL_SERVE_DIRECTION_DISGUISE",
    name: "Serve Direction Disguise Drill",
    skillArea: "SERVE",
    stageRange: ["YELLOW", "GLOW"],
    instruction: "Serve 10 to deuce court: 5 wide, 5 T, random order. Coach watches the ball toss only and guesses direction before contact. Goal: coach wrong 4 of 10 times.",
    repRange: "2 sets of 10 serves per court side",
    milestoneCriteria: "Coach guesses direction incorrectly at least 4 of 10 serves",
    source: "Glow",
    category: "Serve",
    difficulty: "Advanced",
    durationMinutes: 20,
    description: "Learn to hide your serve direction from opponents. A consistent toss is the key to disguising whether you're going wide or T.",
    steps: [
      "Serve from the deuce court.",
      "Mix 5 wide serves and 5 T serves in random order.",
      "Coach watches only the ball toss position and guesses direction before contact.",
      "Track how many times the coach guesses wrong.",
      "Repeat from the ad court.",
    ],
    tips: "Keep your toss in the same position for every serve. Vary the direction with your arm angle and racket path — not the toss.",
    skillTags: ["Serve", "Disguise", "Toss Consistency", "Tactical Serving"],
  },
  {
    id: "DRILL_RETURN_REDIRECT",
    name: "Return Redirect Targeting",
    skillArea: "RETURN",
    stageRange: ["YELLOW", "GLOW"],
    instruction: "Coach serves at 60-70% pace. Two cones set: crosscourt deep, line mid-depth. Coach calls 'cross' or 'line' before each serve. Player redirects to called target. Progress: player chooses based on server position.",
    repRange: "3 sets of 8 returns (4 cross, 4 line per set)",
    milestoneCriteria: "5 of 8 returns land within 1m of called target",
    source: "USTA",
    category: "Backhand",
    difficulty: "Advanced",
    durationMinutes: 20,
    description: "Train the ability to redirect returns on command. This builds the flexibility to go cross or line regardless of serve speed.",
    steps: [
      "Place one cone crosscourt deep and one down the line at mid-depth.",
      "Coach serves at 60-70% pace.",
      "Before each serve, coach calls 'cross' or 'line'.",
      "Player redirects to the called target.",
      "Progress: remove the call and let player choose based on server's position.",
    ],
    tips: "Early preparation is key. The earlier you read the serve, the more time you have to redirect. Watch the server's toss.",
    skillTags: ["Return", "Redirection", "Decision Making", "Targeting"],
  },
  {
    id: "DRILL_3_SHOT_PATTERN",
    name: "3-Shot Point Construction Pattern",
    skillArea: "TACTICAL",
    stageRange: ["GREEN", "YELLOW", "GLOW"],
    instruction: "Pre-agree a 3-shot pattern (e.g. serve wide, forehand cross, inside-out). Run it 5 times cooperatively. Then switch to live play and execute when opportunity arises.",
    repRange: "3 patterns × 5 attempts = 15 reps",
    milestoneCriteria: "Completes agreed pattern 4 of 5 attempts; executes it once in live play",
    source: "Glow",
    category: "Match Tactics",
    difficulty: "Advanced",
    durationMinutes: 25,
    description: "Build tactical automaticity by drilling pre-agreed 3-shot patterns. Translating patterns from drills into match play is a key competitive skill.",
    steps: [
      "Pre-agree a 3-shot pattern with coach.",
      "Execute the pattern cooperatively 5 times in a row.",
      "Switch to live play.",
      "Identify and execute the pattern when opportunity arises naturally.",
      "Track how often you successfully execute the full pattern.",
    ],
    tips: "Start simple — one serve + two groundstrokes. Commit to the pattern even when it doesn't work perfectly. Trust the process.",
    skillTags: ["Patterns", "Serve Plus One", "Tactical Planning", "Point Construction"],
  },
  {
    id: "DRILL_PRESSURE_POINT_SIMULATION",
    name: "Pressure Point Simulation",
    skillArea: "MENTAL",
    stageRange: ["YELLOW", "GLOW"],
    instruction: "Set score to 30-40 or tiebreak 6-6. Play points normally. After each, coach calls 'executed' (ran shot plan) or 'overplayed' (went for unrealistic winner). Track over 20 pressure points.",
    repRange: "20 pressure points across 2 simulated tiebreaks",
    milestoneCriteria: "Executes percentage shot plan on 14 of 20 pressure points",
    source: "Glow",
    category: "Match Tactics",
    difficulty: "Advanced",
    durationMinutes: 30,
    description: "Simulate high-pressure match situations and practise staying process-focused. Learn to play your game plan when it matters most.",
    steps: [
      "Set the score to 30-40 or tiebreak 6-6.",
      "Play out the point normally.",
      "After each point, coach calls 'executed' or 'overplayed'.",
      "'Executed' = played your game plan, made percentage decisions.",
      "'Overplayed' = went for an unrealistic winner under pressure.",
    ],
    tips: "Pressure reveals your habits. The goal is to notice when you overplay — then do less, not more, on the next point.",
    skillTags: ["Mental Toughness", "Pressure", "Decision Making", "Match Simulation"],
  },
  {
    id: "DRILL_PILLAR_CIRCUIT",
    name: "6-Pillar Mini Circuit",
    skillArea: "PHYSICAL",
    stageRange: ["RED", "ORANGE"],
    instruction: "6 stations, 2 minutes each with 30s transition: (1) Bounce and catch, (2) Cone shuffle, (3) 5-ball rally, (4) Mirror movement, (5) Balance on one foot, (6) High-five routine.",
    repRange: "1-2 circuits (12-24 minutes total)",
    milestoneCriteria: "Completes all 6 stations; improvement on technique or footwork station",
    source: "KNLTB",
    category: "Fitness & Conditioning",
    difficulty: "Beginner",
    durationMinutes: 25,
    description: "A fun, multi-station circuit covering all six pillars of tennis development. Great for juniors and beginners to build a broad athletic foundation.",
    steps: [
      "Station 1 (2 min): Bounce and catch a ball — hand-eye coordination.",
      "Station 2 (2 min): Cone shuffle ladder — footwork and agility.",
      "Station 3 (2 min): Cooperative 5-ball rally with coach.",
      "Station 4 (2 min): Copy-cat mirror movement with partner.",
      "Station 5 (2 min): Balance on one foot, 30s each side.",
      "Station 6 (2 min): High-five routine — coordination and fun.",
    ],
    tips: "Keep energy high between stations. The 30-second transition is just enough to reset — don't sit down.",
    skillTags: ["Fitness", "Coordination", "Fun", "Juniors"],
  },
  {
    id: "DRILL_BACKHAND_TOPSPIN_BUILD",
    name: "Backhand Topspin Build Drill",
    skillArea: "TECHNIQUE",
    stageRange: ["GREEN", "YELLOW", "GLOW"],
    instruction: "Start at service line hitting backhand crosscourt mini-rallies. Every 5 balls, step back. Build from service line to full baseline. At each stage, brush up the back of the ball.",
    repRange: "5 balls per position × 4 positions = 20 balls",
    milestoneCriteria: "Clears net marker with topspin at all 4 distances, landing crosscourt",
    source: "Tennis Australia",
    category: "Backhand",
    difficulty: "Beginner",
    durationMinutes: 20,
    description: "Build the topspin backhand from short distance to full baseline. Starting close lets you feel the correct swing path before adding pace.",
    steps: [
      "Start at the service line, hitting crosscourt backhand mini-rallies.",
      "Focus on brushing up the back of the ball with a low-to-high swing.",
      "After 5 balls, take one step back.",
      "Repeat: rally, step back, until you reach the full baseline.",
      "At each stage, clear the net marker by at least 20cm.",
    ],
    tips: "Keep the grip firm at contact but relax the arm during the backswing. The swing should feel like an upward brush, not a push.",
    skillTags: ["Backhand", "Topspin", "Progressive", "Consistency"],
  },
  {
    id: "DRILL_COOPERATIVE_BASELINE_TARGET",
    name: "Cooperative Baseline Target Rally",
    skillArea: "TECHNIQUE",
    stageRange: ["RED", "ORANGE", "GREEN"],
    instruction: "Place a cone on the deep baseline T. Rally cooperatively, aiming to land each ball within 1 metre of the cone. Count consecutive successful targets. Reset on error.",
    repRange: "5 attempts to reach 8 consecutive target hits",
    milestoneCriteria: "Achieves 8 consecutive balls within 1 metre of target cone",
    source: "USTA",
    category: "Forehand",
    difficulty: "Beginner",
    durationMinutes: 15,
    description: "A precision rally drill that trains depth and directional control. The target cone creates a clear, measurable goal for cooperative practice.",
    steps: [
      "Place a cone on the deep centre T of the baseline.",
      "Both players rally cooperatively, aiming at the cone.",
      "Count consecutive balls landing within 1 metre.",
      "Reset the count on any error or miss.",
      "Try to reach 8 consecutive target hits across 5 attempts.",
    ],
    tips: "Think of the cone as a magnet. Hit with intention — every ball should have a target, not just go over the net.",
    skillTags: ["Accuracy", "Depth", "Cooperative Rally", "Consistency"],
  },
];

export async function seedDrills() {
  console.log("[Seed] Starting drills seed...");

  let inserted = 0;
  let skipped = 0;

  for (const drill of DRILL_LIBRARY) {
    try {
      await db.execute(sql`
        INSERT INTO drills (id, name, skill_area, stage_range, instruction, rep_range, milestone_criteria, source,
          category, difficulty, duration_minutes, description, steps, tips, skill_tags)
        VALUES (
          ${drill.id},
          ${drill.name},
          ${drill.skillArea},
          ${JSON.stringify(drill.stageRange)}::jsonb,
          ${drill.instruction},
          ${drill.repRange},
          ${drill.milestoneCriteria},
          ${drill.source},
          ${drill.category},
          ${drill.difficulty},
          ${drill.durationMinutes},
          ${drill.description},
          ${JSON.stringify(drill.steps)}::jsonb,
          ${drill.tips},
          ${JSON.stringify(drill.skillTags)}::jsonb
        )
        ON CONFLICT (id) DO UPDATE SET
          name = EXCLUDED.name,
          skill_area = EXCLUDED.skill_area,
          stage_range = EXCLUDED.stage_range,
          instruction = EXCLUDED.instruction,
          rep_range = EXCLUDED.rep_range,
          milestone_criteria = EXCLUDED.milestone_criteria,
          source = EXCLUDED.source,
          category = EXCLUDED.category,
          difficulty = EXCLUDED.difficulty,
          duration_minutes = EXCLUDED.duration_minutes,
          description = EXCLUDED.description,
          steps = EXCLUDED.steps,
          tips = EXCLUDED.tips,
          skill_tags = EXCLUDED.skill_tags
      `);
      inserted++;
    } catch (err) {
      console.warn(`[Seed] Skipped drill ${drill.id}:`, err);
      skipped++;
    }
  }

  console.log(`[Seed] Drills done: ${inserted} upserted, ${skipped} skipped`);
}
