import { db } from "../db";
import { questTemplates } from "@shared/schema";
import { eq } from "drizzle-orm";

const TRACKED_ACTIONS = [
  "complete_session",
  "daily_login",
  "give_reaction",
  "log_match",
  "post_comment",
  "post_moment",
  "read_coach_feedback",
  "send_connection",
  "win_match",
] as const;

const DAILY_TEMPLATES = [
  {
    id: "qt-daily-session",
    name: "On Court Today",
    description: "Attend any training session today",
    iconName: "tennisball",
    iconColor: "#10B981",
    questType: "daily",
    category: "training",
    targetAction: "complete_session",
    targetCount: 1,
    xpReward: 60,
    currencyReward: 0,
    difficulty: "easy",
    order: 10,
    isActive: true,
  },
  {
    id: "qt-daily-session-2",
    name: "Court Time",
    description: "Show up and attend your scheduled session",
    iconName: "calendar",
    iconColor: "#22D3EE",
    questType: "daily",
    category: "training",
    targetAction: "complete_session",
    targetCount: 1,
    xpReward: 55,
    currencyReward: 0,
    difficulty: "easy",
    order: 14,
    isActive: true,
  },
  {
    id: "qt-daily-session-3",
    name: "Training Grind",
    description: "Put in the work on court today",
    iconName: "barbell",
    iconColor: "#EF4444",
    questType: "daily",
    category: "training",
    targetAction: "complete_session",
    targetCount: 1,
    xpReward: 65,
    currencyReward: 0,
    difficulty: "easy",
    order: 15,
    isActive: true,
  },
  {
    id: "qt-daily-match-log",
    name: "Match Ready",
    description: "Log a match result today",
    iconName: "trophy",
    iconColor: "#F59E0B",
    questType: "daily",
    category: "performance",
    targetAction: "log_match",
    targetCount: 1,
    xpReward: 75,
    currencyReward: 0,
    difficulty: "medium",
    order: 20,
    isActive: true,
  },
  {
    id: "qt-daily-match-day",
    name: "Match Day",
    description: "Get out there and play — log a match result",
    iconName: "tennisball",
    iconColor: "#F59E0B",
    questType: "daily",
    category: "performance",
    targetAction: "log_match",
    targetCount: 1,
    xpReward: 80,
    currencyReward: 0,
    difficulty: "medium",
    order: 23,
    isActive: true,
  },
  {
    id: "qt-daily-win",
    name: "Win of the Day",
    description: "Win a match today",
    iconName: "trophy",
    iconColor: "#F59E0B",
    questType: "daily",
    category: "performance",
    targetAction: "win_match",
    targetCount: 1,
    xpReward: 100,
    currencyReward: 0,
    difficulty: "hard",
    order: 24,
    isActive: true,
  },
  {
    id: "qt-daily-match-win",
    name: "Victory Lap",
    description: "Win a match and record the result",
    iconName: "medal",
    iconColor: "#F59E0B",
    questType: "daily",
    category: "performance",
    targetAction: "win_match",
    targetCount: 1,
    xpReward: 90,
    currencyReward: 0,
    difficulty: "hard",
    order: 25,
    isActive: true,
  },
  {
    id: "qt-daily-post",
    name: "Share Your Day",
    description: "Post a moment from your tennis journey",
    iconName: "image",
    iconColor: "#EC4899",
    questType: "daily",
    category: "social",
    targetAction: "post_moment",
    targetCount: 1,
    xpReward: 40,
    currencyReward: 0,
    difficulty: "easy",
    order: 30,
    isActive: true,
  },
  {
    id: "qt-daily-community-post",
    name: "Community Voice",
    description: "Share a moment or update with your academy community",
    iconName: "megaphone",
    iconColor: "#6366F1",
    questType: "daily",
    category: "social",
    targetAction: "post_moment",
    targetCount: 1,
    xpReward: 35,
    currencyReward: 0,
    difficulty: "easy",
    order: 34,
    isActive: true,
  },
  {
    id: "qt-daily-post-2",
    name: "Story Time",
    description: "Post an update about your tennis journey today",
    iconName: "camera",
    iconColor: "#3B82F6",
    questType: "daily",
    category: "social",
    targetAction: "post_moment",
    targetCount: 1,
    xpReward: 40,
    currencyReward: 0,
    difficulty: "easy",
    order: 36,
    isActive: true,
  },
  {
    id: "qt-daily-react",
    name: "Social Star",
    description: "React to a post from the community",
    iconName: "star",
    iconColor: "#F59E0B",
    questType: "daily",
    category: "social",
    targetAction: "give_reaction",
    targetCount: 1,
    xpReward: 30,
    currencyReward: 0,
    difficulty: "easy",
    order: 31,
    isActive: true,
  },
  {
    id: "qt-daily-reaction",
    name: "Show Some Love",
    description: "React to a post in the academy community",
    iconName: "heart",
    iconColor: "#EC4899",
    questType: "daily",
    category: "social",
    targetAction: "give_reaction",
    targetCount: 1,
    xpReward: 20,
    currencyReward: 0,
    difficulty: "easy",
    order: 33,
    isActive: true,
  },
  {
    id: "qt-daily-reaction-2",
    name: "Good Vibes",
    description: "Spread positivity by reacting to a community post",
    iconName: "sparkles",
    iconColor: "#EC4899",
    questType: "daily",
    category: "social",
    targetAction: "give_reaction",
    targetCount: 1,
    xpReward: 15,
    currencyReward: 0,
    difficulty: "easy",
    order: 35,
    isActive: true,
  },
  {
    id: "qt-daily-comment",
    name: "Team Player",
    description: "Leave a comment on a teammate's post",
    iconName: "chatbubble",
    iconColor: "#EC4899",
    questType: "daily",
    category: "social",
    targetAction: "post_comment",
    targetCount: 1,
    xpReward: 20,
    currencyReward: 0,
    difficulty: "easy",
    order: 37,
    isActive: true,
  },
  {
    id: "qt-daily-comment-2",
    name: "Hype Your Mates",
    description: "Leave an encouraging comment on someone's post",
    iconName: "chatbubbles",
    iconColor: "#10B981",
    questType: "daily",
    category: "social",
    targetAction: "post_comment",
    targetCount: 1,
    xpReward: 20,
    currencyReward: 0,
    difficulty: "easy",
    order: 38,
    isActive: true,
  },
  {
    id: "qt-daily-friend",
    name: "Court Buddy",
    description: "Send a connection request to a player you trained with",
    iconName: "person-add",
    iconColor: "#6366F1",
    questType: "daily",
    category: "social",
    targetAction: "send_connection",
    targetCount: 1,
    xpReward: 30,
    currencyReward: 0,
    difficulty: "easy",
    order: 32,
    isActive: true,
  },
  {
    id: "qt-daily-connection",
    name: "Expand Your Network",
    description: "Send a connection request to a fellow player",
    iconName: "people",
    iconColor: "#0EA5E9",
    questType: "daily",
    category: "social",
    targetAction: "send_connection",
    targetCount: 1,
    xpReward: 30,
    currencyReward: 0,
    difficulty: "easy",
    order: 38,
    isActive: true,
  },
  {
    id: "qt-daily-checkin",
    name: "Daily Check-In",
    description: "Open the app and check your progress today",
    iconName: "checkmark-circle",
    iconColor: "#22D3EE",
    questType: "daily",
    category: "consistency",
    targetAction: "daily_login",
    targetCount: 1,
    xpReward: 15,
    currencyReward: 0,
    difficulty: "easy",
    order: 40,
    isActive: true,
  },
  {
    id: "qt-daily-open-app",
    name: "Daily Opener",
    description: "Open the app and check in today",
    iconName: "phone-portrait",
    iconColor: "#6366F1",
    questType: "daily",
    category: "consistency",
    targetAction: "daily_login",
    targetCount: 1,
    xpReward: 10,
    currencyReward: 0,
    difficulty: "easy",
    order: 45,
    isActive: true,
  },
  {
    id: "qt-daily-feedback",
    name: "Coach's Corner",
    description: "Read your latest coach feedback",
    iconName: "reader",
    iconColor: "#F59E0B",
    questType: "daily",
    category: "consistency",
    targetAction: "read_coach_feedback",
    targetCount: 1,
    xpReward: 30,
    currencyReward: 0,
    difficulty: "easy",
    order: 41,
    isActive: true,
  },
  {
    id: "qt-daily-feedback-2",
    name: "Study Your Craft",
    description: "Review what your coach said about your technique",
    iconName: "book",
    iconColor: "#8B5CF6",
    questType: "daily",
    category: "consistency",
    targetAction: "read_coach_feedback",
    targetCount: 1,
    xpReward: 35,
    currencyReward: 0,
    difficulty: "easy",
    order: 46,
    isActive: true,
  },
];

const WEEKLY_TEMPLATES = [
  {
    id: "qt-weekly-match-log",
    name: "Match Logger",
    description: "Log at least 2 match results this week",
    iconName: "trophy",
    iconColor: "#F59E0B",
    questType: "weekly",
    category: "performance",
    targetAction: "log_match",
    targetCount: 2,
    xpReward: 180,
    currencyReward: 0,
    difficulty: "medium",
    order: 10,
    isActive: true,
  },
  {
    id: "qt-weekly-match",
    name: "Match Day",
    description: "Win a match this week",
    iconName: "trophy",
    iconColor: "#EF4444",
    questType: "weekly",
    category: "performance",
    targetAction: "win_match",
    targetCount: 1,
    xpReward: 200,
    currencyReward: 0,
    difficulty: "hard",
    order: 11,
    isActive: true,
  },
  {
    id: "qt-weekly-sessions",
    name: "Session Warrior",
    description: "Complete 2 training sessions this week",
    iconName: "tennisball",
    iconColor: "#10B981",
    questType: "weekly",
    category: "training",
    targetAction: "complete_session",
    targetCount: 2,
    xpReward: 150,
    currencyReward: 0,
    difficulty: "medium",
    order: 12,
    isActive: true,
  },
  {
    id: "qt-weekly-sessions-3",
    name: "Hat Trick",
    description: "Complete 3 training sessions this week",
    iconName: "tennisball",
    iconColor: "#10B981",
    questType: "weekly",
    category: "training",
    targetAction: "complete_session",
    targetCount: 3,
    xpReward: 220,
    currencyReward: 0,
    difficulty: "hard",
    order: 13,
    isActive: true,
  },
  {
    id: "qt-weekly-consistency",
    name: "Consistent Grinder",
    description: "Complete at least 4 sessions this week",
    iconName: "calendar",
    iconColor: "#10B981",
    questType: "weekly",
    category: "training",
    targetAction: "complete_session",
    targetCount: 4,
    xpReward: 280,
    currencyReward: 0,
    difficulty: "legendary",
    order: 13,
    isActive: true,
  },
  {
    id: "qt-weekly-content",
    name: "Content Creator",
    description: "Share 3 moments with your academy community",
    iconName: "image",
    iconColor: "#EC4899",
    questType: "weekly",
    category: "social",
    targetAction: "post_moment",
    targetCount: 3,
    xpReward: 120,
    currencyReward: 0,
    difficulty: "medium",
    order: 20,
    isActive: true,
  },
  {
    id: "qt-weekly-social-posts",
    name: "Social Pro",
    description: "Share 2 moments with your academy community",
    iconName: "image",
    iconColor: "#EC4899",
    questType: "weekly",
    category: "social",
    targetAction: "post_moment",
    targetCount: 2,
    xpReward: 100,
    currencyReward: 0,
    difficulty: "easy",
    order: 20,
    isActive: true,
  },
  {
    id: "qt-weekly-reactions",
    name: "Hype Machine",
    description: "React to 5 posts from your academy community",
    iconName: "heart",
    iconColor: "#EC4899",
    questType: "weekly",
    category: "social",
    targetAction: "give_reaction",
    targetCount: 5,
    xpReward: 90,
    currencyReward: 0,
    difficulty: "easy",
    order: 21,
    isActive: true,
  },
  {
    id: "qt-weekly-connections",
    name: "Network Builder",
    description: "Connect with 2 new players this week",
    iconName: "people",
    iconColor: "#6366F1",
    questType: "weekly",
    category: "social",
    targetAction: "send_connection",
    targetCount: 2,
    xpReward: 130,
    currencyReward: 0,
    difficulty: "medium",
    order: 31,
    isActive: true,
  },
  {
    id: "qt-weekly-coach-feedback",
    name: "Feedback Seeker",
    description: "Read coach feedback at least 2 times this week",
    iconName: "reader",
    iconColor: "#F59E0B",
    questType: "weekly",
    category: "consistency",
    targetAction: "read_coach_feedback",
    targetCount: 2,
    xpReward: 120,
    currencyReward: 0,
    difficulty: "easy",
    order: 30,
    isActive: true,
  },
  {
    id: "qt-weekly-daily-streak",
    name: "Week Warrior",
    description: "Log in to the app every day for 7 consecutive days",
    iconName: "flame",
    iconColor: "#EF4444",
    questType: "weekly",
    category: "consistency",
    targetAction: "daily_login",
    targetCount: 7,
    xpReward: 300,
    currencyReward: 0,
    difficulty: "hard",
    order: 40,
    isActive: true,
  },
  {
    id: "qt-weekly-matches-played",
    name: "Competitive Week",
    description: "Log 3 match results this week",
    iconName: "tennisball",
    iconColor: "#F59E0B",
    questType: "weekly",
    category: "performance",
    targetAction: "log_match",
    targetCount: 3,
    xpReward: 250,
    currencyReward: 0,
    difficulty: "hard",
    order: 14,
    isActive: true,
  },
];

const MONTHLY_TEMPLATES = [
  {
    id: "qt-monthly-attend",
    name: "Iron Attendance",
    description: "Complete 8 training sessions this month",
    iconName: "tennisball",
    iconColor: "#10B981",
    questType: "monthly",
    category: "training",
    targetAction: "complete_session",
    targetCount: 8,
    xpReward: 500,
    currencyReward: 0,
    difficulty: "hard",
    order: 10,
    isActive: true,
  },
  {
    id: "qt-monthly-sessions-12",
    name: "Month Grinder",
    description: "Complete 12 training sessions this month",
    iconName: "tennisball",
    iconColor: "#10B981",
    questType: "monthly",
    category: "training",
    targetAction: "complete_session",
    targetCount: 12,
    xpReward: 700,
    currencyReward: 0,
    difficulty: "legendary",
    order: 10,
    isActive: true,
  },
  {
    id: "qt-monthly-matches",
    name: "Match Champion",
    description: "Win 3 matches this month",
    iconName: "trophy",
    iconColor: "#F59E0B",
    questType: "monthly",
    category: "performance",
    targetAction: "win_match",
    targetCount: 3,
    xpReward: 600,
    currencyReward: 0,
    difficulty: "legendary",
    order: 20,
    isActive: true,
  },
  {
    id: "qt-monthly-matches-5",
    name: "Match Machine",
    description: "Log 5 match results this month",
    iconName: "trophy",
    iconColor: "#F59E0B",
    questType: "monthly",
    category: "performance",
    targetAction: "log_match",
    targetCount: 5,
    xpReward: 650,
    currencyReward: 0,
    difficulty: "hard",
    order: 20,
    isActive: true,
  },
  {
    id: "qt-monthly-social",
    name: "Social Butterfly",
    description: "Share 10 posts in your academy community this month",
    iconName: "people",
    iconColor: "#EC4899",
    questType: "monthly",
    category: "social",
    targetAction: "post_moment",
    targetCount: 10,
    xpReward: 400,
    currencyReward: 0,
    difficulty: "hard",
    order: 30,
    isActive: true,
  },
  {
    id: "qt-monthly-posts",
    name: "Community Pillar",
    description: "Make 8 posts in the academy community this month",
    iconName: "people",
    iconColor: "#EC4899",
    questType: "monthly",
    category: "social",
    targetAction: "post_moment",
    targetCount: 8,
    xpReward: 450,
    currencyReward: 0,
    difficulty: "hard",
    order: 30,
    isActive: true,
  },
  {
    id: "qt-monthly-connections",
    name: "Well Connected",
    description: "Build 5 new player connections this month",
    iconName: "git-network",
    iconColor: "#6366F1",
    questType: "monthly",
    category: "social",
    targetAction: "send_connection",
    targetCount: 5,
    xpReward: 400,
    currencyReward: 0,
    difficulty: "medium",
    order: 31,
    isActive: true,
  },
  {
    id: "qt-monthly-feedback-reads",
    name: "Feedback Champion",
    description: "Read coach feedback 10 times this month",
    iconName: "reader",
    iconColor: "#F59E0B",
    questType: "monthly",
    category: "consistency",
    targetAction: "read_coach_feedback",
    targetCount: 10,
    xpReward: 500,
    currencyReward: 0,
    difficulty: "hard",
    order: 40,
    isActive: true,
  },
  {
    id: "qt-monthly-streak-20",
    name: "Unstoppable",
    description: "Log in to the app 20 days this month",
    iconName: "flame",
    iconColor: "#EF4444",
    questType: "monthly",
    category: "consistency",
    targetAction: "daily_login",
    targetCount: 20,
    xpReward: 800,
    currencyReward: 0,
    difficulty: "legendary",
    order: 41,
    isActive: true,
  },
];

export async function seedQuestTemplates() {
  console.log("[QuestSeed] Starting quest template seeding...");

  let added = 0;
  let skipped = 0;

  const allTemplates = [
    ...DAILY_TEMPLATES,
    ...WEEKLY_TEMPLATES,
    ...MONTHLY_TEMPLATES,
  ];

  for (const template of allTemplates) {
    const existing = await db
      .select()
      .from(questTemplates)
      .where(eq(questTemplates.id, template.id))
      .limit(1);

    if (existing.length > 0) {
      skipped++;
      continue;
    }

    await db.insert(questTemplates).values({
      id: template.id,
      academyId: null,
      name: template.name,
      description: template.description,
      iconName: template.iconName,
      iconColor: template.iconColor,
      questType: template.questType,
      category: template.category,
      targetAction: template.targetAction,
      targetCount: template.targetCount,
      xpReward: template.xpReward,
      currencyReward: template.currencyReward,
      difficulty: template.difficulty,
      order: template.order,
      isActive: template.isActive,
    });

    added++;
    console.log(`[QuestSeed] Added: ${template.name} (${template.questType})`);
  }

  const daily = allTemplates.filter((t) => t.questType === "daily").length;
  const weekly = allTemplates.filter((t) => t.questType === "weekly").length;
  const monthly = allTemplates.filter((t) => t.questType === "monthly").length;

  console.log(
    `[QuestSeed] Done. Added ${added} templates, skipped ${skipped} existing.`
  );
  console.log(
    `[QuestSeed] Catalog: ${daily} daily, ${weekly} weekly, ${monthly} monthly`
  );

  return { success: true, added, skipped };
}
