import { db } from "../db";
import { levelTests } from "../../shared/schema";

const SCORING_KEY = { 1: "Beginning", 2: "Developing", 3: "Competent" };

const USTA_ASSESSMENT_ITEMS = [
  // ========== RED 3 ==========
  {
    id: "usta_red3_baseline_rally",
    levelId: "RED_3",
    name: "Cooperative Rally",
    testType: "usta_assessment",
    description: "Player can cooperatively rally with a partner from the baseline, keeping the ball in play.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red3_baseline_drop_hits",
    levelId: "RED_3",
    name: "Drop-Hit Variations",
    testType: "usta_assessment",
    description: "Player can drop-hit to the side, high, low, and deep targets.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red3_serve_basic",
    levelId: "RED_3",
    name: "Basic Serve into Box",
    testType: "usta_assessment",
    description: "Player can serve the ball into the service box from inside the service line.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red3_net_blocking_volley",
    levelId: "RED_3",
    name: "Blocking Volley Form",
    testType: "usta_assessment",
    description: "Player demonstrates correct blocking volley form at the net.",
    metrics: {
      category: "Net Play",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red3_transition_recover",
    levelId: "RED_3",
    name: "Move and Recover to Center",
    testType: "usta_assessment",
    description: "Player moves to ball and recovers to center court position.",
    metrics: {
      category: "Transition",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red3_game_serve_starts",
    levelId: "RED_3",
    name: "Understands Serve Starts Point",
    testType: "usta_assessment",
    description: "Player understands that the serve starts the point and demonstrates this understanding in play.",
    metrics: {
      category: "Game",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },

  // ========== RED 2 ==========
  {
    id: "usta_red2_baseline_rally_unit_turn",
    levelId: "RED_2",
    name: "Rally with Unit Turn",
    testType: "usta_assessment",
    description: "Player rallies from the service line using a unit turn to prepare.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red2_serve_overhand",
    levelId: "RED_2",
    name: "Overhand Serve Forehand and Backhand Side",
    testType: "usta_assessment",
    description: "Player can execute an overhand serve to both the forehand and backhand service box.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red2_return_second_serve_deep",
    levelId: "RED_2",
    name: "Return Second Serve Deep",
    testType: "usta_assessment",
    description: "Player returns a second serve with depth, pushing the ball back deep in the court.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red2_net_approach_volley",
    levelId: "RED_2",
    name: "Approach Plus Volley Combination",
    testType: "usta_assessment",
    description: "Player executes an approach shot followed by a volley finish at the net.",
    metrics: {
      category: "Net Play",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red2_net_split_step",
    levelId: "RED_2",
    name: "Split-Step Before Volley",
    testType: "usta_assessment",
    description: "Player performs a split-step before executing a volley at the net.",
    metrics: {
      category: "Net Play",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red2_transition_recovery_shuffle",
    levelId: "RED_2",
    name: "Recovery Shuffle to Center",
    testType: "usta_assessment",
    description: "Player uses a shuffle step to recover to center court after wide balls.",
    metrics: {
      category: "Transition",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },

  // ========== RED 1 ==========
  {
    id: "usta_red1_baseline_crosscourt_dtl",
    levelId: "RED_1",
    name: "Rally Crosscourt and Down the Line",
    testType: "usta_assessment",
    description: "Player can intentionally direct groundstrokes crosscourt and down the line.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red1_baseline_topspin_slice",
    levelId: "RED_1",
    name: "Topspin and Slice Groundstrokes",
    testType: "usta_assessment",
    description: "Player demonstrates developing topspin and slice on groundstrokes.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red1_serve_slice_continental",
    levelId: "RED_1",
    name: "Developing Slice Serve with Continental Grip",
    testType: "usta_assessment",
    description: "Player uses a continental grip and attempts a slice serve.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red1_return_direction",
    levelId: "RED_1",
    name: "Return Second Serve with Direction",
    testType: "usta_assessment",
    description: "Player can aim the return of a second serve to a specific direction.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red1_net_approach_volley_sequence",
    levelId: "RED_1",
    name: "Approach One Side, Volley to Other Sequence",
    testType: "usta_assessment",
    description: "Player approaches to one side then volleys to the opposite side of the court.",
    metrics: {
      category: "Net Play",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red1_transition_on_the_rise",
    levelId: "RED_1",
    name: "On-the-Rise Timing on Deep Balls",
    testType: "usta_assessment",
    description: "Player demonstrates timing to hit balls on the rise when opponents hit deep.",
    metrics: {
      category: "Transition",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_red1_game_open_stance",
    levelId: "RED_1",
    name: "Open/Semi-Open Stance on Wide Balls",
    testType: "usta_assessment",
    description: "Player uses an open or semi-open stance when running for wide balls.",
    metrics: {
      category: "Game",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },

  // ========== ORANGE 3 ==========
  {
    id: "usta_orange3_baseline_rally_depth",
    levelId: "ORANGE_3",
    name: "Rally to Center with Depth",
    testType: "usta_assessment",
    description: "Player rallies crosscourt to the center of the court with consistent depth.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange3_baseline_slice_inside",
    levelId: "ORANGE_3",
    name: "Slice Forehand and Backhand from Inside Box",
    testType: "usta_assessment",
    description: "Player can slice forehand and backhand from inside the service box area.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange3_serve_consistent",
    levelId: "ORANGE_3",
    name: "Consistent Serve in Box",
    testType: "usta_assessment",
    description: "Player consistently serves the ball into the correct service box.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange3_return_depth",
    levelId: "ORANGE_3",
    name: "Returns with Depth",
    testType: "usta_assessment",
    description: "Player returns serves with consistent depth past the service line.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange3_net_volley_approach",
    levelId: "ORANGE_3",
    name: "Volley from Approach Shot",
    testType: "usta_assessment",
    description: "Player executes a proper volley after approaching the net.",
    metrics: {
      category: "Net Play",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange3_net_overhead",
    levelId: "ORANGE_3",
    name: "Overhead to Both Sides",
    testType: "usta_assessment",
    description: "Player can hit an overhead smash to both sides of the court.",
    metrics: {
      category: "Net Play",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange3_game_doubles_positioning",
    levelId: "ORANGE_3",
    name: "Understands Basic Doubles Positioning",
    testType: "usta_assessment",
    description: "Player understands and demonstrates basic doubles court positioning.",
    metrics: {
      category: "Game",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },

  // ========== ORANGE 2 ==========
  {
    id: "usta_orange2_baseline_topspin_speed",
    levelId: "ORANGE_2",
    name: "Increased Topspin with Speed",
    testType: "usta_assessment",
    description: "Player generates increased topspin combined with ball speed on groundstrokes.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange2_baseline_slice_low",
    levelId: "ORANGE_2",
    name: "Slice on Low Midcourt Balls",
    testType: "usta_assessment",
    description: "Player uses a slice shot effectively on low midcourt balls.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange2_serve_faster_spin",
    levelId: "ORANGE_2",
    name: "Faster First Serve Plus Spin Second Serve",
    testType: "usta_assessment",
    description: "Player serves a faster first serve and uses spin on the second serve.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange2_serve_direct_fh_bh",
    levelId: "ORANGE_2",
    name: "Directs Serve Forehand or Backhand",
    testType: "usta_assessment",
    description: "Player can direct the serve to the opponent's forehand or backhand side.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange2_transition_short_ball",
    levelId: "ORANGE_2",
    name: "Recognizes Short Ball to Attack",
    testType: "usta_assessment",
    description: "Player recognizes when a short ball is available and moves to attack it.",
    metrics: {
      category: "Transition",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange2_net_lob_passing",
    levelId: "ORANGE_2",
    name: "Lob and Passing Shot",
    testType: "usta_assessment",
    description: "Player can execute a lob over a net player and a passing shot down the line or crosscourt.",
    metrics: {
      category: "Net Play",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange2_transition_recover_baseline",
    levelId: "ORANGE_2",
    name: "Recovers Behind Baseline After Defense",
    testType: "usta_assessment",
    description: "Player recovers behind the baseline after playing a defensive ball.",
    metrics: {
      category: "Transition",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },

  // ========== ORANGE 1 ==========
  {
    id: "usta_orange1_baseline_on_rise",
    levelId: "ORANGE_1",
    name: "Deep Baseline Shots on the Rise",
    testType: "usta_assessment",
    description: "Player can hit groundstrokes on the rise from deep in the court.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange1_baseline_tempo_change",
    levelId: "ORANGE_1",
    name: "Changes Tempo Offense and Defense",
    testType: "usta_assessment",
    description: "Player intentionally changes the tempo of play between offensive and defensive situations.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange1_serve_3_spots",
    levelId: "ORANGE_1",
    name: "Serve to 3 Spots: Wide, Body, T",
    testType: "usta_assessment",
    description: "Player can serve to wide, body, and T spots on command.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange1_transition_attack_second_serve",
    levelId: "ORANGE_1",
    name: "Attacks Weak Second Serve to Net",
    testType: "usta_assessment",
    description: "Player recognizes a weak second serve and attacks it, following to the net.",
    metrics: {
      category: "Transition",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange1_net_swing_volley",
    levelId: "ORANGE_1",
    name: "Swing Volley on High Midcourt Ball",
    testType: "usta_assessment",
    description: "Player executes a swing volley on high midcourt balls.",
    metrics: {
      category: "Net Play",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange1_net_deep_short_angle",
    levelId: "ORANGE_1",
    name: "Deep Plus Short-Angle Volley with Spin",
    testType: "usta_assessment",
    description: "Player can hit a deep volley and a short-angle volley with spin.",
    metrics: {
      category: "Net Play",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange1_game_dynamic_split_step",
    levelId: "ORANGE_1",
    name: "Dynamic Split-Step on Opponent Contact",
    testType: "usta_assessment",
    description: "Player times the dynamic split-step to occur as the opponent makes contact.",
    metrics: {
      category: "Game",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_orange1_game_serve_plus_1",
    levelId: "ORANGE_1",
    name: "Serve Plus 1 Pattern Executed",
    testType: "usta_assessment",
    description: "Player executes a planned serve plus one shot pattern to set up the point.",
    metrics: {
      category: "Game",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },

  // ========== GREEN 2 ==========
  {
    id: "usta_green2_baseline_depth_direction",
    levelId: "GREEN_2",
    name: "Depth and Direction from Baseline",
    testType: "usta_assessment",
    description: "Player consistently hits groundstrokes with depth and directional control.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_green2_baseline_inside_out_fh",
    levelId: "GREEN_2",
    name: "Developing Inside-Out Forehand",
    testType: "usta_assessment",
    description: "Player is developing an inside-out forehand pattern from the backhand corner.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_green2_serve_direct_fh_bh",
    levelId: "GREEN_2",
    name: "Directs First Serve to Forehand or Backhand",
    testType: "usta_assessment",
    description: "Player can direct the first serve to the opponent's forehand or backhand side consistently.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_green2_return_step_in",
    levelId: "GREEN_2",
    name: "Step-In Second Serve Return to Open Court",
    testType: "usta_assessment",
    description: "Player steps in to return the second serve and directs it to the open court.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_green2_net_passing_shots",
    levelId: "GREEN_2",
    name: "Developing Passing Shots DTL, Angle, Lob",
    testType: "usta_assessment",
    description: "Player is developing passing shots down the line, angled, and with a lob.",
    metrics: {
      category: "Net Play",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_green2_net_overhead_movement",
    levelId: "GREEN_2",
    name: "Overhead Movement: Drop-Step and Crossover",
    testType: "usta_assessment",
    description: "Player uses drop-step and crossover footwork to position for overhead smashes.",
    metrics: {
      category: "Net Play",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_green2_transition_wider_lower_split",
    levelId: "GREEN_2",
    name: "Wider, Lower Base on Split-Step",
    testType: "usta_assessment",
    description: "Player uses a wider and lower athletic stance on the split-step to improve reaction.",
    metrics: {
      category: "Transition",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },

  // ========== GREEN 1 ==========
  {
    id: "usta_green1_baseline_keep_deep",
    levelId: "GREEN_1",
    name: "Keeps Opponent Deep via Height, Spin, Speed",
    testType: "usta_assessment",
    description: "Player uses height, spin, and speed variations to keep the opponent pinned deep.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_green1_baseline_drop_shot",
    levelId: "GREEN_1",
    name: "Drop Shot Inside Baseline",
    testType: "usta_assessment",
    description: "Player can execute a drop shot from inside the baseline to change the pace.",
    metrics: {
      category: "Baseline",
      head_feet_hands: "Hands",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_green1_serve_wide_body_t",
    levelId: "GREEN_1",
    name: "Serve to Wide, Body, T Consistently",
    testType: "usta_assessment",
    description: "Player consistently serves to wide, body, and T targets from both sides.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_green1_return_on_rise",
    levelId: "GREEN_1",
    name: "Returns on the Rise",
    testType: "usta_assessment",
    description: "Player consistently returns serves by hitting the ball on the rise.",
    metrics: {
      category: "Serve/Return",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_green1_net_multiple_modes",
    levelId: "GREEN_1",
    name: "Multiple Net-Entry Modes: Slice, Drive Volley, Sneak",
    testType: "usta_assessment",
    description: "Player uses slice approach, drive volley, and sneak approaches to come to net.",
    metrics: {
      category: "Net Play",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_green1_net_scissor_kick_overhead",
    levelId: "GREEN_1",
    name: "Scissor-Kick on Deeper Overheads",
    testType: "usta_assessment",
    description: "Player uses a scissor-kick technique to hit overheads on deeper lobs.",
    metrics: {
      category: "Net Play",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_green1_game_split_step_timing",
    levelId: "GREEN_1",
    name: "Split-Step Timing Slightly After Opponent Contact",
    testType: "usta_assessment",
    description: "Player times the split-step to land slightly after opponent makes contact.",
    metrics: {
      category: "Game",
      head_feet_hands: "Feet",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
  {
    id: "usta_green1_game_doubles_poach",
    levelId: "GREEN_1",
    name: "Doubles Poach and Switch Coordination",
    testType: "usta_assessment",
    description: "Player can execute a poach at the net and switches with their partner in doubles.",
    metrics: {
      category: "Game",
      head_feet_hands: "Head",
      scoring_key: SCORING_KEY,
      target_score: 3,
    },
  },
];

export async function seedUstaAssessmentItems() {
  console.log("[UstaAssessmentSeed] Seeding USTA assessment items...");

  for (const item of USTA_ASSESSMENT_ITEMS) {
    await db
      .insert(levelTests)
      .values({
        id: item.id,
        levelId: item.levelId,
        testType: item.testType,
        name: item.name,
        description: item.description,
        metrics: item.metrics,
      })
      .onConflictDoNothing();
  }

  console.log(`[UstaAssessmentSeed] Seeded ${USTA_ASSESSMENT_ITEMS.length} USTA assessment items.`);
  return { success: true, count: USTA_ASSESSMENT_ITEMS.length };
}
