// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing/LandingBoldAthletic.tsx": () => import("../components/mockups/landing/LandingBoldAthletic.tsx"),
  "./components/mockups/landing/LandingBrightAcademy.tsx": () => import("../components/mockups/landing/LandingBrightAcademy.tsx"),
  "./components/mockups/landing/LandingDarkElite.tsx": () => import("../components/mockups/landing/LandingDarkElite.tsx"),
  "./components/mockups/coach-dashboard/CleanCommand.tsx": () => import("../components/mockups/coach-dashboard/CleanCommand.tsx"),
  "./components/mockups/coach-dashboard/CoachCockpit.tsx": () => import("../components/mockups/coach-dashboard/CoachCockpit.tsx"),
  "./components/mockups/coach-dashboard/LiveCourt.tsx": () => import("../components/mockups/coach-dashboard/LiveCourt.tsx")
};
