export interface TimezoneOption {
  value: string;
  label: string;
}

export const IANA_TIMEZONES: TimezoneOption[] = [
  { value: "Pacific/Midway", label: "Midway Island (SST, UTC-11)" },
  { value: "Pacific/Honolulu", label: "Hawaii (HST, UTC-10)" },
  { value: "America/Anchorage", label: "Alaska (AKST, UTC-9)" },
  { value: "America/Los_Angeles", label: "Los Angeles (PST, UTC-8)" },
  { value: "America/Phoenix", label: "Phoenix (MST, UTC-7)" },
  { value: "America/Denver", label: "Denver (MST, UTC-7)" },
  { value: "America/Chicago", label: "Chicago (CST, UTC-6)" },
  { value: "America/Mexico_City", label: "Mexico City (CST, UTC-6)" },
  { value: "America/New_York", label: "New York (EST, UTC-5)" },
  { value: "America/Toronto", label: "Toronto (EST, UTC-5)" },
  { value: "America/Bogota", label: "Bogota (COT, UTC-5)" },
  { value: "America/Lima", label: "Lima (PET, UTC-5)" },
  { value: "America/Caracas", label: "Caracas (VET, UTC-4)" },
  { value: "America/Halifax", label: "Halifax (AST, UTC-4)" },
  { value: "America/Manaus", label: "Manaus (AMT, UTC-4)" },
  { value: "America/La_Paz", label: "La Paz (BOT, UTC-4)" },
  { value: "America/Santiago", label: "Santiago (CLT, UTC-4)" },
  { value: "America/St_Johns", label: "Newfoundland (NST, UTC-3:30)" },
  { value: "America/Sao_Paulo", label: "Sao Paulo (BRT, UTC-3)" },
  { value: "America/Buenos_Aires", label: "Buenos Aires (ART, UTC-3)" },
  { value: "Atlantic/South_Georgia", label: "South Georgia (GST, UTC-2)" },
  { value: "Atlantic/Azores", label: "Azores (AZOT, UTC-1)" },
  { value: "Atlantic/Cape_Verde", label: "Cape Verde (CVT, UTC-1)" },
  { value: "Europe/London", label: "London (GMT, UTC+0)" },
  { value: "Europe/Lisbon", label: "Lisbon (WET, UTC+0)" },
  { value: "Africa/Casablanca", label: "Casablanca (WET, UTC+0)" },
  { value: "Europe/Amsterdam", label: "Amsterdam (CET, UTC+1)" },
  { value: "Europe/Berlin", label: "Berlin (CET, UTC+1)" },
  { value: "Europe/Brussels", label: "Brussels (CET, UTC+1)" },
  { value: "Europe/Madrid", label: "Madrid (CET, UTC+1)" },
  { value: "Europe/Paris", label: "Paris (CET, UTC+1)" },
  { value: "Europe/Rome", label: "Rome (CET, UTC+1)" },
  { value: "Europe/Stockholm", label: "Stockholm (CET, UTC+1)" },
  { value: "Europe/Warsaw", label: "Warsaw (CET, UTC+1)" },
  { value: "Africa/Lagos", label: "Lagos (WAT, UTC+1)" },
  { value: "Africa/Tunis", label: "Tunis (CET, UTC+1)" },
  { value: "Europe/Athens", label: "Athens (EET, UTC+2)" },
  { value: "Europe/Bucharest", label: "Bucharest (EET, UTC+2)" },
  { value: "Europe/Helsinki", label: "Helsinki (EET, UTC+2)" },
  { value: "Europe/Istanbul", label: "Istanbul (TRT, UTC+3)" },
  { value: "Europe/Kyiv", label: "Kyiv (EET, UTC+2)" },
  { value: "Africa/Cairo", label: "Cairo (EET, UTC+2)" },
  { value: "Africa/Johannesburg", label: "Johannesburg (SAST, UTC+2)" },
  { value: "Africa/Nairobi", label: "Nairobi (EAT, UTC+3)" },
  { value: "Asia/Riyadh", label: "Riyadh (AST, UTC+3)" },
  { value: "Asia/Kuwait", label: "Kuwait (AST, UTC+3)" },
  { value: "Asia/Baghdad", label: "Baghdad (AST, UTC+3)" },
  { value: "Asia/Aden", label: "Aden (AST, UTC+3)" },
  { value: "Asia/Tehran", label: "Tehran (IRST, UTC+3:30)" },
  { value: "Asia/Dubai", label: "Dubai (GST, UTC+4)" },
  { value: "Asia/Muscat", label: "Muscat (GST, UTC+4)" },
  { value: "Asia/Tbilisi", label: "Tbilisi (GET, UTC+4)" },
  { value: "Asia/Baku", label: "Baku (AZT, UTC+4)" },
  { value: "Asia/Yerevan", label: "Yerevan (AMT, UTC+4)" },
  { value: "Indian/Mauritius", label: "Mauritius (MUT, UTC+4)" },
  { value: "Asia/Kabul", label: "Kabul (AFT, UTC+4:30)" },
  { value: "Asia/Karachi", label: "Karachi (PKT, UTC+5)" },
  { value: "Asia/Tashkent", label: "Tashkent (UZT, UTC+5)" },
  { value: "Asia/Yekaterinburg", label: "Yekaterinburg (YEKT, UTC+5)" },
  { value: "Asia/Colombo", label: "Colombo (IST, UTC+5:30)" },
  { value: "Asia/Kolkata", label: "India (IST, UTC+5:30)" },
  { value: "Asia/Kathmandu", label: "Kathmandu (NPT, UTC+5:45)" },
  { value: "Asia/Almaty", label: "Almaty (ALMT, UTC+6)" },
  { value: "Asia/Dhaka", label: "Dhaka (BST, UTC+6)" },
  { value: "Asia/Omsk", label: "Omsk (OMST, UTC+6)" },
  { value: "Asia/Yangon", label: "Yangon (MMT, UTC+6:30)" },
  { value: "Asia/Bangkok", label: "Bangkok (ICT, UTC+7)" },
  { value: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh (ICT, UTC+7)" },
  { value: "Asia/Jakarta", label: "Jakarta (WIB, UTC+7)" },
  { value: "Asia/Novosibirsk", label: "Novosibirsk (NOVT, UTC+7)" },
  { value: "Asia/Phnom_Penh", label: "Phnom Penh (ICT, UTC+7)" },
  { value: "Asia/Vientiane", label: "Vientiane (ICT, UTC+7)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong (HKT, UTC+8)" },
  { value: "Asia/Kuala_Lumpur", label: "Kuala Lumpur (MYT, UTC+8)" },
  { value: "Asia/Krasnoyarsk", label: "Krasnoyarsk (KRAT, UTC+7)" },
  { value: "Asia/Makassar", label: "Makassar/Bali (WITA, UTC+8)" },
  { value: "Asia/Manila", label: "Manila (PHT, UTC+8)" },
  { value: "Asia/Shanghai", label: "China (CST, UTC+8)" },
  { value: "Asia/Singapore", label: "Singapore (SGT, UTC+8)" },
  { value: "Asia/Taipei", label: "Taipei (CST, UTC+8)" },
  { value: "Asia/Ulaanbaatar", label: "Ulaanbaatar (ULAT, UTC+8)" },
  { value: "Australia/Perth", label: "Perth (AWST, UTC+8)" },
  { value: "Asia/Irkutsk", label: "Irkutsk (IRKT, UTC+8)" },
  { value: "Asia/Tokyo", label: "Tokyo (JST, UTC+9)" },
  { value: "Asia/Seoul", label: "Seoul (KST, UTC+9)" },
  { value: "Asia/Yakutsk", label: "Yakutsk (YAKT, UTC+9)" },
  { value: "Australia/Adelaide", label: "Adelaide (ACST, UTC+9:30)" },
  { value: "Australia/Darwin", label: "Darwin (ACST, UTC+9:30)" },
  { value: "Australia/Brisbane", label: "Brisbane (AEST, UTC+10)" },
  { value: "Australia/Melbourne", label: "Melbourne (AEDT, UTC+11)" },
  { value: "Australia/Sydney", label: "Sydney (AEDT, UTC+11)" },
  { value: "Asia/Vladivostok", label: "Vladivostok (VLAT, UTC+10)" },
  { value: "Pacific/Guam", label: "Guam (ChST, UTC+10)" },
  { value: "Asia/Magadan", label: "Magadan (MAGT, UTC+11)" },
  { value: "Pacific/Noumea", label: "Noumea (NCT, UTC+11)" },
  { value: "Pacific/Auckland", label: "Auckland (NZST, UTC+12)" },
  { value: "Pacific/Fiji", label: "Fiji (FJT, UTC+12)" },
];
